### ISSUE TITLE
Build error with 1.37 release

### ISSUE THREAD

**Issue by rezso** [geany/geany-plugins#1023]
The build fails in prettyprinter plugin:

In file included from /usr/include/unicode/umachine.h:52,
                 from /usr/include/unicode/utypes.h:38,
                 from /usr/include/unicode/ucnv_err.h:88,
                 from /usr/include/unicode/ucnv.h:52,
                 from /usr/include/libxml2/libxml/encoding.h:31,
                 from /usr/include/libxml2/libxml/parser.h:810,
                 from PluginEntry.h:32,
                 from PluginEntry.c:28:
PrettyPrinter.h:55:22: error: two or more data types in declaration specifiers
   55 | typedef unsigned int bool;

**Comment by codebrainz** [comment]
Could be a clash with another file including `stdbool.h` or also defining own `bool` type.

IMO, it should either include `stdbool.h` and use the standard `bool` (alias of `_Bool`) or else use `gboolean` that is already available via the `glib.h` include.

@rezso if you want to test, try removing the offending line (55) and putting `#include <stdbool.h>` on line 32.

**Comment by rezso** [comment]
I tried it, and works.
Thank you.

**Comment by codebrainz** [comment]
Then it is a bug.

**Comment by b4n** [comment]
@rezso Could you give some information on your setup?  System version, maybe libxml2 and Geany-Plugins version?
