### ISSUE TITLE
required library dev package (libenchat-dev) not mentioned in spellcheck docs

### ISSUE THREAD

**Issue by andy5995** [geany/geany-plugins#1050]
*Debian Buster
*Geany-plugins v1.37
*Geany (git) built with GTK 3 enabled

The 'libenchat-dev' package is required to build the spellcheck plugin; however, I didn't find that information in /README.md or in https://github.com/geany/geany-plugins/tree/master/spellcheck.

**Comment by elextr** [comment]
"you need to have the Enchant library installed" -- README

To build anything you always need the development versions of libraries installed _if your distro separates them_.  And different distros call the separated development packages different things, `libenchant-dev` on Debian and derivatives, `enchant-devel` on Fedora and other headgear, and probably other things elsewhere.

So its not a simple "install XXX" so its generally assumed in Geany and plugins that people building the software understand what they are doing and how their distro works.

**Comment by andy5995** [comment]
My big problem was that I haven't been doing much coding lately and am getting a bit rusty in the head. I was trying to find the .pc file and preceding './configure' with  PKG_CONFIG_PATH... forgetting that I needed to install libenchant-dev. Fortunately I only lost 5 minutes of my life.
