### ISSUE TITLE
GTK 3 not mentioned as an option requirement in spellcheck docs

### ISSUE THREAD

**Issue by andy5995** [geany/geany-plugins#1051]
*Debian Buster
*Geany-plugins v1.37
*Geany (git) built with GTK 3 enabled

The [spellcheck doc](https://github.com/geany/geany-plugins/blob/master/spellcheck/README) lists "GTK >= 2.8.0" as a requirement, but I think it should list it as "GTK >= 2.8.0 or GTK 3" because Geany itself can be built with GTK 3 enabled, and if it is, wouldn't GTK 3 be a req for the spellcheck plugin?

(related #1050)

**Comment by elextr** [comment]
Geany 1.37 switched to GTK3 by default, you can still build it with gtk2 by telling configure --enable-gtk2, but even that will go away in 1.38 (well thats the plan anyway) so references to GTK2 will slowly go away from Geany and plugins.

Note that technically GTK3 is ">=2.8.0" :grin:

See also reply on #1050
