### ISSUE TITLE
Please fix README with install steps

### ISSUE THREAD

**Issue by pgp** [geany/geany-plugins#1063]
Trying to build plugins on Mint 20.
Installed so far:
`autoconf automake libtool`

`./autogen.sh` returns the error: `./autogen.sh: 4: intltoolize: not found`

Instead, running `./configure` after having successfully run `autoconf` in the root folder, gives the error:
```
./configure: line 1974: syntax error near unexpected token `1.8'
./configure: line 1974: `AM_INIT_AUTOMAKE(1.8 foreign dist-bzip2 tar-ustar subdir-objects)'
```
Any hint?

**Comment by elextr** [comment]
Did you build Geany?

For me on Mint 20 having installed some build basics to make geany the plugins "just works".

Since your autogen.sh didn't succeed because you need intltools I'm not surprised that configure failed, synaptic tells me I have intltool and intltool-debian packages installed.

**Comment by pgp** [comment]
Ok, didn't know I needed to build Geany as well, I thought plugins build process was independent from the main application's build.
Anyway, I had to install `libglib2.0-dev` together with `intltool`.

**Comment by elextr** [comment]
Sorry I didn't mean to say you had to build Geany as well, I was just saying that the build dependencies for Geany seems to satisfy the build dependencies for Geany-plugins.  Although note that some individual plugins have additional requirements and the plugin is disabled if not met, but the build will work.
