### ISSUE TITLE
LaTeX plugin: Keyboard shurtcuts for itemize and enumerate generate wrong result

### ISSUE THREAD

**Issue by zeitgenosse** [geany/geany-plugins#1071]
If a assign a keyboard shortcut for generatin an itemize or enumerate environment, the result is

```
\begin{itemize}
  \it
\end{itemize}em
```
where the correct output should be

```
\begin{itemize}
  \item 
\end{itemize}
```

Steps to reproduce: 
* Assign some keyboard shortcut for itemize (or enumerate).
* Press that combination of keys. 

My version of Geany is 1.33 (the one shipped with recent Debian-ish distributions), the LaTeX plugin version is 0.7.

**Comment by nomadbyte** [comment]
LaTeX v0.7, Geany 1.36 (Ubuntu)

- menu:`Preferences > Keybindings > LaTeX > Insert Itemize List => Ctrl+Alt+M`
- menu:`File > New`
- menu:`Document > Set Filetype > Markup Languages > LaTeX source file`
- in the new document: `Ctrl+Alt+M`

Result:

```
\begin{itemize}
	\item 
\end{itemize}
```

**Comment by elextr** [comment]
AFAICT nothing has changed in Latex plugin in that [area](https://github.com/geany/geany-plugins/blob/7c540bf347d0f0c6f6ab5123fa8f226b2f9152ee/latex/src/latexenvironments.c#L137) since forever, looks like something in the OPs system, just in case ping @frlan

**Comment by frlan** [comment]
Sorry for the late reaction ;)

To be honest I have not even an idea what might cause that issue. This function is actually done by building up a string 

```C			
if (type == GLATEX_ENVIRONMENT_TYPE_LIST)
{
g_string_append(tmpstring, "\t\\item ");
}
``` 
and than later

```C	
GeanyDocument *doc = NULL;

	doc = document_get_current();

	if (doc != NULL && string != NULL)
	{
…
		editor_insert_text_block(doc->editor, string, pos, len, 0, TRUE);
	}
}
```

**Comment by frlan** [comment]
There was another report that indicates that's maybe related to tabs/spaces
