### ISSUE TITLE
Can't activate debugger plugin Ubuntu 20.04

### ISSUE THREAD

**Issue by dwarning** [geany/geany-plugins#1072]
Dear all,
at first i tried geany + plugins from Ubuntus standard repositories with their apt manager. I could see all the plugins in the plugin manager but no "debugger" option.
After de-installation I stepped over to self compilation geany-1.37.1 and geany-plugins-1.37. After installation of libvte-2.91 configure in plugin show me that debugger option is enabled. Compiling of both packages was fine - debugger.so was created. So I installed all things with admin right in the default location /usr/local.
Geany/Toolbox/Plugin-manager still show a lot of plugins - but no "debugger". /usr/local/lib/geany/debugger.so is available.
Same behavior is compiling from github.
For me looks that only the entry of the debugger plugin is missing. How I can check it? Where is something like log file after starting the program?
Can you help me, please.

**Comment by elextr** [comment]
`Menu->Help->Debug Messages` might help.

**Comment by dwarning** [comment]
Thank you - this helps. It seems to do with my LD_LIBRARY_PATH variable. After extend to /usr/local/lib the libgeany.so and libgeanypluginutils.so are found and successful loaded.
`
09:23:19: Geany INFO		: Loaded libvte from libvte-2.91.so

09:23:19: Geany INFO		: Loaded:   /usr/local/lib/geany/debugger.so (Debugger)

09:23:20: Geany INFO		: unknown : None (UTF-8)
`
Should I take w.r.t. the "unknown: None (UTF-8)" message?

**Comment by elextr** [comment]
On Wed, 14 Apr 2021 at 17:40, dwarning ***@***.***> wrote:

> Thank you - this helps. It seems to do with my LD_LIBRARY_PATH variable.
> After extend to /usr/local/lib the libgeany.so and libgeanypluginutils.so
> are found and successful loaded.
>
09:23:19: Geany INFO : Loaded libvte from libvte-2.91.so
>
> 09:23:19: Geany INFO : Loaded: /usr/local/lib/geany/debugger.so (Debugger)
>
> 09:23:20: Geany INFO : unknown : None (UTF-8)
> `
> Should I take w.r.t. the "unknown: None (UTF-8)" message?
>

Thats the empty document that is auto-opened if you have the relevant
preference set., so no problem.

Cheers
Lex

**Comment by frlan** [comment]
Self compiled Geany as well as plugins go to /usr/local unless you change it during configure-run. If this one is missing in default Ubuntu profile you might want to fill a feature/bug-report there.

**Comment by fei4xu** [comment]
you can change the installation path by `--prefix=/usr`
```
git clone https://github.com/geany/geany-plugins.git
cd geany-plugins/
sudo apt-get install libvte-2.91-dev
./autogen.sh --disable-all-plugins --enable-debugger --prefix=/usr
make -j8
sudo make install
```
