### ISSUE TITLE
Vimode: Can't exit insert mode if 'g' was the last entered character.

### ISSUE THREAD

**Issue by natopwns** [geany/geany-plugins#1075]
Steps to reproduce:
 - Enter insert mode.
 - Type the letter 'g'.
 - Try to exit insert mode.

Expected behavior:
Program exits insert mode.

Actual behavior:
Program stays in insert mode.

**Comment by techee** [comment]
I don't seem able to reproduce the problem. What exactly do you do? When I'm in command mode, enter insert mode using `i`, type `g` and press `<esc>`, I get back to the command mode.

**Comment by natopwns** [comment]
It's still happening for me. I just open Geany, type `i`, type `g`, and press `<esc>`, which does nothing. As soon as I type any other character, `<esc>` sends me back to command mode.
I'm using Geany from the Arch repos, maybe it has to do with that. I'll try to build from source and see if it stills does the same thing.

**Comment by techee** [comment]
> EDIT: I have "Insert Mode for Dummies" on. When I turned that off, it works now. The bug is in "Insert Mode for Dummies".

Ah, OK, I can reproduce it now. Will investigate.
