### ISSUE TITLE
Column mode editing  on Mac

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany-plugins#1076]
Please tell me how to engage column mode editing on a  Mac? Shift+command does not seem to work. I  was trying to explain this useful feature to a new user and realized that the documentation does not make this clear, nor does set keyboard short cuts.  I.e. it is a useful feature but not immediately obvious how you get it it on a Mac.  The doc reproduced below does not help either.  It would be useful during new user onboarding it this were a settable keyboard combination that could be easily found and set as needed.

 Column mode editing (rectangular selections)

There is basic support for column mode editing. To use it, create a rectangular selection by holding down the Control and Shift keys (or Alt and Shift on Windows) while selecting some text. Once a rectangular selection exists you can start editing the text within this selection and the modifications will be done for every line in the selection.

It is also possible to create a zero-column selection - this is useful to insert text on multiple lines.

**Comment by elextr** [comment]
The document you quote says **control** not command.

**Comment by elextr** [comment]
And why have you created this on Geany-plugins? There is a Geany-OSX specific repository.
