### ISSUE TITLE
Spelling suggestion drop down like auto-complete

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany-plugins#1081]
Please could Geany provide a spelling suggestions drop down like auto-complete for spelling errors rather than a mere underline as  autocomplete is so much more efficient? Thanks!

![image](https://user-images.githubusercontent.com/7548378/121760617-a061f400-cb23-11eb-9969-174f8942ac92.png)

**Comment by elextr** [comment]
Spell checker is a plugin (https://plugins.geany.org/spellcheck.html) so transferred to plugins.

**Comment by eht16** [comment]
There is already a list of suggestions in the context menu (just right-click on underlined word):

![spellcheck_suggestions](https://user-images.githubusercontent.com/617017/121768319-2e9ea000-cb4d-11eb-9b2b-8bf924c2a869.png)

This feature can be activated in the plugin preferences dialog.
I don't think it's worth the effort to implement the suggestions as an auto-complete list as most users probably are used to reach the suggestions via a context menu.

Re-open if you heavily disagree :D.

**Comment by elextr** [comment]
>  as most users probably are used to reach the suggestions via a context menu.

Just to concur, for instance that is how it works for underlined spelling here in GitHub, in Libre Office writer, Xed, Gedit, Vscode as examples.
