### ISSUE TITLE
1.37.0 fails to build on Manjaro using gcc 11.1.0

### ISSUE THREAD

**Issue by andy5995** [geany/geany-plugins#1082]
The last release (1.37.0) fails to building on Manjaro with gcc 11.1.0.

The problem is fixed with this already-merged patch: https://github.com/geany/geany-plugins/commit/ad50d3ed2ddfe11cd07954786b96725602fb4ddd by @xyproto 

So it might be time for a new release.

**Comment by elextr** [comment]
There was a performance fix (geany #2747) that was going to trigger a 1.37.2 if not a 1.38 but it hasn't happened yet, so I guess plugins need to be done too.
@b4n ?
