### ISSUE TITLE
macro trigger doesn't work anymore

### ISSUE THREAD

**Issue by edufraine** [geany/geany-plugins#1083]
Hello everyone,
I have been using geany for quite a long time now, this is the first bug I report; I hope I am doing it right.

My config : debian Bullseye with geany 1.37.1 (GTK 3.24.23, Glib 2.66.2)

My problem : my existing macros don't work, the keystroke produce nothing.
If I create a new one, it is working.

The only difference I notice is, in ~/.config/geany/plugins/Geany_Macros/settings.conf
The "C" line of the macro is 67108932 for the non-working ones and 100663364 for the new ones.

**Comment by elextr** [comment]
It would appear that the internals of GTK have changed the layout of part of the state associated with keycodes.  Unfortunately thats an internal detail Geany doesn't control.  

So my first suggestion is to try just editing the settings.conf file and replacing the old number with the new one.

Note: the numbers in hex are 0x4000044 and 0x6000044 respectively, ie the new number has one extra bit set, but what that means would have to be searched in the GTK APIs somewhere (in saying GTK I'm assuming Scintilla just passes keycodes and states directly from GTK)

**Comment by edufraine** [comment]
Thanks Elextr, it indeed works to replace the old number by the new one. 
What puzzles me is that it is the same number, regardless of the keys combinations triggering the macro.

Anyway, it is working, so thanks again.
