### ISSUE TITLE
Caps lock escape swap not working in vimode

### ISSUE THREAD

**Issue by rishabh-vasudevan** [geany/geany-plugins#1132]
I have remaped my caps lock key to escape and my escape key to caps lock using a kde function. But when I work in vimode in geany the escape key (caps lock key in hardware) does not work.

Something similar also happened in vscode but I was able to fix it with the following `Preferences → Settings → Application → Keyboard → Dispatch and select keyCode`

Is there something similar that I can do in geany?

**Comment by techee** [comment]
I don't think you can do anything in Geany itself.

I don't know how this re-mapping works but I would expect it just sends different key codes to applications so I would expect this to be transparent to applications. Geany is a GTK application so maybe one thing to try is to look for GTK problems of this kind.

Also, in GTK it is possible to remap keys using GTK key themes so you could play with those too (you just have to check if Geany was compiled as a GTK2 or GTK3 application and look for the right documentation for your GTK version).

**Comment by rishabh-vasudevan** [comment]
Thanks for the info. I decided to use this application[Key-Mapper](https://github.com/sezanzeb/key-mapper) to remap my keys. It works for GTK applications as well.
