### ISSUE TITLE
Please can someone tell me what *.Plo files are

### ISSUE THREAD

**Issue by jradxl** [geany/geany-plugins#1134]
Please can someone tell me what *.Plo files are?
Nothing comes up on a google search, and plugins have such files in a .deps dir, where perhaps they have a # in them
Thx

**Comment by elextr** [comment]
The `.deps` directory is created by the build system to save dependency data, note that directory is not in the source.  

The files in it record various dependency information so the build does not need to create it all from scratch every time its run.  They are internal to the build, not anything you should touch.
