### ISSUE TITLE
List of dependencies

### ISSUE THREAD

**Issue by MarkuBu** [geany/geany-plugins#1168]
Hi, I try to compile the Geany plugins from source on Ubuntu 20.04, but it is difficult to get all dependencies. I have to filter them out of the ./configure output. I'm still not able to compile all plugins.

It would be nice to have a list of necessary dependencies, preferably as c&p for different distributions.

**Comment by elextr** [comment]
It would be nice, but likely impractical.  Plugins are created and maintained by individuals who decide the dependencies they require.  Geany-plugins is just a collection with a small amount of common infrastructure, not a project creating plugins.

They should have documented dependencies in the `README`, but sometimes they don't update that.  And sometimes plugins become orphaned. And individual plugins maintainers most likely won't have the resources to try on different distros.

If anyone finds undocumented dependencies or issues with specific distros they are encouraged to make a PR updating the plugins README.

Note that its unlikely all plugins will compile on a specific system, some are GTK2 only and some are GTK3 only.

**Comment by eht16** [comment]
Additionally, providing concrete package names of the dependencies for multiple distributions would be very time consuming and needs constant maintenance to keep the list up to date.

It's easier to ask the distribution what to install. Since you are refering to Ubuntu, you can easily install dependencies with:

`apt-get build-dep geany-plugins`

Note: for this to work, you need to enable the `deb-src` items in `/etc/apt/sources.list`.

**Comment by MarkuBu** [comment]
> It's easier to ask the distribution what to install. Since you are refering to Ubuntu, you can easily install dependencies with:
> 
> `apt-get build-dep geany-plugins`
> 
> Note: for this to work, you need to enable the `deb-src` items in `/etc/apt/sources.list`.

Maybe this hint can be added to the readme

**Comment by elextr** [comment]
> `apt-get build-dep geany-plugins`

> Note: for this to work, you need to enable the deb-src items in /etc/apt/sources.list.

Although of course that lists the deps for the version in the Debuntu repositories.  Presumably you are building from source to get a newer version, which may have different dependencies.

**Comment by nomadbyte** [comment]
In case this may help,  [build.yml](../../.github/build.yml) lists the dependencies needed for building the plugins. Note that this is what's needed on the build host (on GitHub this is currently Ubuntu 20.04).
