### ISSUE TITLE
geany-plugin-multiterm not available for Ubuntu 20.04

### ISSUE THREAD

**Issue by babaric-dev** [geany/geany-plugins#1172]
I am trying to install `geany-plugin-multiterm` on Ubuntu 20.04. It seems the package is not on the Ubuntu repos. Anyways, here is my attempt on installing the plugin:
```
$apt install geany-plugin-multiterm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package geany-plugin-multiterm
```

P.S. The output if `uname -m` is `aarch64`. However, that should not really matter

**Comment by elextr** [comment]
It appears that multiterm has not been updated to GTK3, Ubuntu has been distributing Geany as GTK3 for some time now, and Geany itself is now only GTK3.  So GTK2 plugins cannot be used with current Geany.

**Comment by babaric-dev** [comment]
From what I can conclude, that means multiterm is deprecated. Then, are there alternatives of multiterm for GTK3? Or is there a fork of the multiterm plugin?

**Comment by elextr** [comment]
There is no alternative that I know of.

Geany plugins is a collection, its not a project that creates plugins.  Plugins are developed and maintained by individuals, that means it happens that the developer/maintainer becomes unable or uninterested in supporting the plugin.

But that also allows others to provide new/updates for plugins, but sometimes they forget/don't want to distribute them.  You could try searching github or gitlab etc.

**Comment by babaric-dev** [comment]
It isnt available. So, yeah, I closed this.

**Comment by elextr** [comment]
See also #1217, so yeah, "somebody" needs to make a new plugin.
