### ISSUE TITLE
Sorry if not really Geany, but its plugin for comparison

### ISSUE THREAD

**Issue by abdulbadii** [geany/geany-plugins#1185]
So sorry if not really Geany, but its **addon** (plugin) instead (can't find the forum to properly ask)
Is there as good as `git diff ` algorithm plugin that is capable of comparing two UTF-8 text files pretty fast?

**Comment by elextr** [comment]
You have been transferred to the plugins repository.

There is a geanyvc plugin that does some version control system interfacing, including Git, but I don't use it so don't know if it will suit you, best you try it.
