### ISSUE TITLE
Git Change Bar not working

### ISSUE THREAD

**Issue by MocioF** [geany/geany-plugins#1187]
In gentoo Git Change Bar plugin doesn't work anymore. I have built geany-1.38 and geany-plugins-1.38-r1 and libgit2 is dev-libs/libgit2-1.3.2
The plugin doesn't show any color mark in bar and no contextual menu while modified lines are selected.

**Comment by elextr** [comment]
Duplicate of 1164, 1165 and incomplete PR 1178.
