### ISSUE TITLE
Not finding plugins on windows

### ISSUE THREAD

**Issue by mj8w** [geany/geany-plugins#1189]
Geany is installed at `C:/Users/<name>/Geany 1.38`.
Plugins are installed at `C:/Users/<name>/Geany-Plugins 1.38`.
Geany menu (Tools|Plugin Manager) only shows 6 plugins, I was expecting many more.
Geany menu (Edit|Preferences) has "Enable plugin support" enabled.
I have restarted several times, and set the "Extra plugin path" to the above path.

Am I doing something wrong?

**Comment by elextr** [comment]
Normally Geany and Plugins need to be installed to the same place.

Try setting `Edit->Preferences->General->Startup` to point to the directory holding the `.dll` files in your plugins.
