### ISSUE TITLE
Spell Check: how can I delete unused languages?

### ISSUE THREAD

**Issue by FranzBias** [geany/geany-plugins#1204]
Hello everyone, this is my first post. 
I would like to **delete languages** I don't use from Geany's spell-check on Linux Mint, but I don't know which **directory** to look in to delete the respective files (I only use it_IT, de_DE, en_GB and fr_FR, all the others I don't need). It's possible?
Can someone please help me?

**Comment by eht16** [comment]
The available languages are not installed directly by Geany but by your distribution, i.e. Linux Mint.

Check your package manager for packages like "hunspell-*" or "aspell-*" or "myspell-*". You can easily uninstall all those packages with languages you do not need.
Please note that all this is independent of Geany, i.e. the languages you uninstall will be missing in other programs as well.

**Comment by FranzBias** [comment]
> The available languages are not installed directly by Geany but by your distribution, i.e. Linux Mint.
> 
> Check your package manager for packages like "hunspell-_" or "aspell-_" or "myspell-*". You can easily uninstall all those packages with languages you do not need. Please note that all this is independent of Geany, i.e. the languages you uninstall will be missing in other programs as well.

Perfect! 
I searched for 'hunspell-' and removed all the language packages I didn't need as you recommended.
Thank you very much .
