### ISSUE TITLE
Now that I've built the plugin using ./autogen.sh successfully, why doesn't the plugin appear in my Geany plugin manager

### ISSUE THREAD

**Issue by PellTheTabber1** [geany/geany-plugins#1215]
Is there something I still need to do to make the plugin usable in the Geany editor.  The plugin GeanyLaTex is not listed by my plugin manager.  There is some step I don't understand.  Does it install only due to some inclusion into a project?

Any help appreciated as I have no idea how to install the plugin on fatdog Linux which does NOT have the apt install command nor sudo.

**Comment by elextr** [comment]
See "usage" in the README, you need to do `make install` to install.   If your distro has no `sudo` and you are installing to a system directory then you need to run `make install` as superuser/root or whatever the distro calls it.

**Comment by PellTheTabber1** [comment]
The README says the the autogen which in turn calls the configure does the install?  Is this true?
Building with Autotools
^^^^^^^^^^^^^^^^^^^^^^^

You can use Autotools to build the Geany plugins in this repository.

Usage::

  ./configure [arguments] or alternatively ./autogen.sh [arguments]
  make
  sudo make install

autogen.sh will call configure in background and is only available if
you are using Geany plugins from git repository. It is not included in
release packages.

However, this will configure, build and install most of the Geany plugins.
There is some auto-detection in place which automagically disables
some of the plugins if there are insufficient build dependencies.
The following arguments can tweak the behaviour of the configure
script.

**Comment by PellTheTabber1** [comment]
Ah ok, I need to call make install, sorry about that.  Thank you.

**Comment by PellTheTabber1** [comment]
Wow, they all appear now, except that they are alphabetized and mixed with the other plugins.  But it worked!
