### ISSUE TITLE
startup always opens the file from /tmp/_dc~~~/ that contains the opened files

### ISSUE THREAD

**Issue by WhitehawkTailor** [geany/geany-plugins#1243]
Geany startup process always opens the file of the opened files from  /tmp/_dc~~~/
If it is left in this state when closing, then next open process will have two files opened from /tmp/_dc~~~/ and so on.
The Filelist.lst contains the list of file names that were open on tabs when Geany was closed.

![Geany_startup_issue](https://user-images.githubusercontent.com/76742732/227781993-35510830-4ad0-4b79-b234-2d09570bf544.png)

**Comment by elextr** [comment]
`/tmp/_dc~~~/` is not a directory Geany or Grany-plugins uses, and nor is `FilelistXXXXXXXXXX.lst`.

Close _all_ plugins and try again.

**Comment by eht16** [comment]
Closing this after no more feedback.

@WhitehawkTailor re-open if it still is a problem.

**Comment by WhitehawkTailor** [comment]
I finally solved the problem.
I used DoubleCommander as two panel file manager.
I used Geany for file editing by replacing DC internal editor.
There were an unnecessary %F on the DC setup page in the additional parameters field.
As The %F was removed the phenomena disappeared and there is no more strange file opening.

So please close the issue.
It was not a Geany problem.
thx

**Comment by WhitehawkTailor** [comment]
I should have known it immediately from the location of the extra files, since it contains dc for DoubleCommander
