### ISSUE TITLE
Geanypg doesnt work anymore

### ISSUE THREAD

**Issue by Hasenarsch** [geany/geany-plugins#1246]
After i had to invest almost 30 Minutes to get a git account, i have to say:
After the last update the geanypg iplugin is not available anymore.
What is happening ? I cant find te menu entries anymore ?

**Comment by elextr** [comment]
Without any information on the version of Geany and what platform you are running on its not possible to help you.

**Comment by Hasenarsch** [comment]
Hi

First of all, I would like to apologize for my rude tone. I was very frustrated as I needed this feature quite badly.
I verified the problem further and found out that the maintainer of the Geany plugins package ( I use Manjaro) did not add this plugin anymore. Or something went wrong during the installation.
When I built the plugin myself from the git sources , I could select it again.
So I contacted the maintainer directly and asked him what was going on.
Sorry again and thanks for your work.

Sincerely JG
