### ISSUE TITLE
TASKS not showing from.txt files geany 1.38 kubuntu 22.04, plasma 5.24.7

### ISSUE THREAD

**Issue by joomlafun** [geany/geany-plugins#1251]
Hi,

Typing TODO does not work in .txt on kubuntu 22.04 (I deactivated any other plugin)
![Screenshot_20230521_183636](https://github.com/geany/geany-plugins/assets/63743077/d3e026be-505d-4d76-894c-b91ca4adc1f4)

(Nothing relevant shows up in the debug console) ; can you try to reproduce this please?

**Comment by eht16** [comment]
The plugin only considers TODO keywords which are part of a comment. Thus you also need a document with a filetype which supports comments.

**Comment by joomlafun** [comment]
> The plugin only considers TODO keywords which are part of a comment. Thus you also need a document with a filetype which supports comments.

Thank you for the answer eht16, it works indeed with // in php
