### ISSUE TITLE
Hiding Some Type of Files in the Explorer

### ISSUE THREAD

**Issue by WIZARDELF** [geany/geany-plugins#1258]
Is there a way to hide/exclude some type of files so that they are not showing in the Explorer? If no, it will be a useful feature.

**Comment by techee** [comment]
> Is there a way to hide/exclude some type of files so that they are not showing in the Explorer? If no, it will be a useful feature.

To the original question - yes, it is possible. The plugin reads what you define in "File patterns" of the Project Properties dialog so if you set for instance "*.py", it will show only Python files.
