### ISSUE TITLE
Cannot install webhelper

### ISSUE THREAD

**Issue by TomCarroll09** [geany/geany-plugins#1269]
I have been attempting to install the webhelper plugin, i first tried to install it i tried building from source, this work after a while however the webhelper plugin was missing. i tried installing it through dnf as i am on fedora but every plugin, BUT webelper was available.
i noticed that someone else had the same problem a me, in a forum:
https://forums.linuxmint.com/viewtopic.php?t=350114

> it depends on deprecated webkitgtk, so Debian maintainers [disabled](https://salsa.debian.org/geany-team/geany-plugins/-/commits/master/debian?utf8=%E2%9C%93&search=webhelper) it. I guess it will be so until it's ported to webkit2gtk.
When i try to compile it from source i get the message:
```
checking for WEBHELPER... no
configure: error: Package requirements (gtk+-3.0 >= 2.16
                          glib-2.0 >= 2.22
                          gio-2.0 >= 2.18
                          gdk-pixbuf-2.0 >= 2.0
                          webkitgtk-3.0 >= 1.1.18
                          gthread-2.0) were not met:

Package 'webkitgtk-3.0', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables WEBHELPER_CFLAGS
and WEBHELPER_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
i installed all of these and still get the same errors.
is there any solution?

**Comment by elextr** [comment]
Seems strange, current git requires "webkit2gtk-4.0 >= ${WEBKIT_VERSION}" not "webkitgtk-3.0", what source did you build from?

**Comment by TomCarroll09** [comment]
I tried building the plugin from the source on the releases and I cloning the repo from git.

**Comment by elextr** [comment]
The update to current webkit has happened since last release, which would be why Fedora doesn't provide, it because it doesn't provide the olde webkit.

Make sure you checkout HEAD then build.

**Comment by eht16** [comment]
@TomCarroll09 I'm closing this. Geany and Geany-Plugins 2.0 are going to be released in a few days and then the mentioned update for Webkit will be included in the new release.

If you disagree or need further support, just re-open.
