### ISSUE TITLE
Error: Most Plugins not binary compatible with this release of geany. Therefore not available in  Plugin Manager Dialog

### ISSUE THREAD

**Issue by masla84** [geany/geany-plugins#1292]
After successful installation of  geany-plugins-2.0_setup.exe  with standard settings only a few plugins are available in Geany.
Error message says plugins are not binary compatible with this release of geany and needs to be recompiled.
In previous version 1.38 already some plugins were missing like git-changebar but now lot more.

Both Geany and Geany-Plugins are installed in Windows user directory. 

![grafik](https://github.com/geany/geany-plugins/assets/52318651/97da42b5-ce8a-41df-aed4-bbe80cecc711)

**Comment by elextr** [comment]
Did you install Geany 2.0 first?

**Comment by masla84** [comment]
I still have Geany 1.38 & Plugins installed, seems Geany 2.0 looks into Plugins 1.38 folder. If I rename Geany-Plugins 1.38 folder Geany 2.0 doesn't find any plugins, but no error messages anymore. 
How to tell Geany in which plugins folder it should search for? 

Am Freitag, 17. November 2023 schrieb elextr:

**Comment by elextr** [comment]
There is `Edit->Preferences->General->Startup->Extra plugin path` but the install should put the plugins in the right place.  But I don't know Windows, @eht16 any ideas?

**Comment by eht16** [comment]
On Windows, having multiple installations of Geany is not really supported. If I remember correctly, the Geany installer writes the installation directory (and so the path to the plugins location) into the registry.
The Geany-Plugins installer reads this registry key to set the installation directory. I don't know how well it works if you overrule this logic and have multiple installations in parallel. I never tested this.

So, I would suggest to uninstall all of your Geany installations and install 2.0 afterwards. Then plugins should work.
Note that copying plugin files from an old installation to a new one won't work on Windows, there are most probably never compabitle.

One more note, please be aware that we changed Geany's configuration file behavior in 2.0, many session related information (also the list of loaded plugins) has been split into a new configuration file `session.conf` but Geany 1.38 doesn't know this and tries to read the information still from `geany.conf`. And so weird things might happen when you mix Geany 1.38 and 2.0 with the same configuration directory.

**Comment by masla84** [comment]
Thanks for your answer, I don't use 1.38 anymore I just forgot to deinstall it ;-). To find the root cause I checked

- Windows registry:  HKEY_CURRENT_USER\SOFTWARE: There are 2 entries pointing to Geany(-Plugins) 2.0 directory 
- In the Preferences, plugin path was actually set to 1.38 directory, so I changed it to 2.0 path. But no success.
- Additionally, I changed path of (active) plugins to 2.0 in session.conf and geany.conf. But also no success.
- Now it becomes weird: If I activate a available plugin e.g. FileManager it works, but in the session.conf it still writes the 1.38 path to this plugin. So it ignores existing entry of same plugin to 2.0 directory.
Why is Geany still looking for 1.38 directory while preferences/registry/.conf pointing to 2.0 ?
The setting in preferences dialog seems to be ignored completely. This seems like a bug to me or is there a explanation for 
this?
![h9p0swLXXssscIZs](https://github.com/geany/geany-plugins/assets/52318651/bf4c64ba-05af-4049-a82e-4123a3d5ab73)
![grafik](https://github.com/geany/geany-plugins/assets/52318651/d65ce54b-a364-442e-ae8a-efd
![Fky00uSVMJeCNzlJ](https://github.com/geany/geany-plugins/assets/52318651/79c47451-3f6b-499c-ac50-609e79987968)
![grafik](https://github.com/geany/geany-plugins/assets/52318651/559e7ec1-d473-48c6-9eeb-5b8d85262fb8)

811f4bf6e)

**Comment by masla84** [comment]
After deinstallation of all Geany x versions and new installation of Geany 2.0 + Geany Plugins just some plugins are available. This seems similar to #1189.
Partly solved by adding Geany-Plugins 2-0\lib\geany to "Extra plugin path" in the Preferences.
But the root problem for all this trials remains: git-changebar plugin is not available.
Are there any hints how to solve that? The git-changebar.dll exists.

**Comment by elextr** [comment]
Is the right version of libgit2 available?

**Comment by masla84** [comment]
libgit2-1.7.dll is in Plugins 2.0\bin\ folder

Am Donnerstag, 30. November 2023 schrieb elextr:

**Comment by eht16** [comment]
@masla84 if this still persists, please check Help->Debug Messages in Geany, at the beginning loading of plugins is logged and also if there any errors occurred.

Alternatively, uninstall all of your Geanys, remove the config folder (or at least clean the plugin paths manually) and try again.

Re-open if it still does not work.
