### ISSUE TITLE
Geany crashes loading the Markdown plugin - GBM-DRV error

### ISSUE THREAD

**Issue by pjbroad** [geany/geany-plugins#1300]
Today, geany started crashing on startup.  I've traced this to the Markdown plugin and the latest update to the mesa package on my system.  I'm running a fully updated arch system with nvidia graphics and the LTS kernal.  The error output and the package versions are included below.  I've attached a full trace obtained when running with gdb.  Starting geany with the "--no-plugins" option or removing the markdown library from session.conf and geany.conf allows geany to start.  However, enabling the Markdown plugin from the UI also crashes geany.

`$ geany `
```
src/nv_gbm.c:242: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

Segmentation fault (core dumped)
```

`$ geany --version`
```
geany 2.0 (built on 2023-10-23 with GTK 3.24.38, GLib 2.78.0)
```

`$ pacman -Ss geany`
```
extra/geany 2.0-1 [installed]
extra/geany-plugins 2.0-1 [installed]
```

`$ pacman -Ss mesa`
```
extra/mesa 1:23.3.2-1 [installed]
```

[geany-gdb.log](https://github.com/geany/geany-plugins/files/13805011/geany-gdb.log)

**Comment by elextr** [comment]
Suggest you report to Mesa first, thats where the crash is.  Don't forget to tell them the version of Webkit2GTK your system has since its Geany calls Webkit2GTK calls Mesa where the crash is.

**Comment by pjbroad** [comment]
Thanks @elextr,.  The arch package of mesa has been updated again, reverting some of the last changes.  The Markdown plugin is working again.  Clearly a mesa issue so sorry to have wasted your time.  This issue can probably be closed.
