### ISSUE TITLE
BUG during tab-browsing with the keyboard in the sidebar when a new tab is in the sidebar

### ISSUE THREAD

**Issue by ralf3u** [geany/geany-plugins#1318]
**Conditions**
- except `File Browser` all other plugins are deactivated
- sidebar is on the left side
- in the sidebar are three tabs (from left to the right): `Symbols`, `Documents` and `Files`
- in the editor are two documents

**Steps to reproduce the issue**
1. click in the editor on the second tab-title, so the second tab is in focus
2. click in the sidebar on the tab-title `Documents`
3. close Geany
4. open Geany (result: the second tab of the editor should be in focus while in the sidebar the tab `Documents` is active)
5. click on the tab-title `Files`
6. tab-browse with the keyboard three times to the left side

**Result**
the first tab of the editor is in focus

**Expectation**
the tab `Files` of the sidebar should be in focus

**System**
Lubuntu 23.10
Geany 1.38

**Remark**
This does not only happen with the plugin `File Browser` but also with the plugin `Preview`, because in both plugins a new tab is created in the sidebar, in the plugin `File Browser` it is the Files-tab while in the plugin `Preview` it is the Preview-tab.
This issue is based on the knowledge of https://github.com/xiota/geany-preview/issues/11.

**System**
Lubuntu 23.10
Geany 1.38

**Comment by elextr** [comment]
> 6. tab-browse with the keyboard three times to the left side

Is "tab-browse" a key on your keyboard?  If not what key(s) are you pressing, ctrl+pg up/down?

If so works here (Geany 2.0,  GTK 3.24.20, GLib 2.64.6).

**Comment by ralf3u** [comment]
>[...] ctrl+pg up/down?

yes

**Comment by ralf3u** [comment]
I can imagine that Geany 2.0 will be part of Lubuntu 24.04, that will be published next month, so I can test the issue there.

**Comment by elextr** [comment]
BTW well done with the detailed report (except one omission ;-), I don't remember any changes in that area for 2.0, but maybe there were.

**Comment by ralf3u** [comment]
I can't reproduce the issue in Geany 2.0 in Lubuntu 23.10.
