### ISSUE TITLE
Default plugins folder incorrect / not found

### ISSUE THREAD

**Issue by socal-nerdtastic** [geany/geany-plugins#1321]
Fresh install on Windows of Geany and Geany plugins with default settings will install Geany to "C:\Users\Username\Geany  2.0" and the plugins to "C:\Users\Username\Geany-Plugins 2.0". In this configuration Geany does not see the plugins. I have to add "C:\Users\Username\Geany-Plugins 2.0\lib\geany" to the "Extra Plugins Path" in Geany preferences, a step which I do not see documented anywhere.

**Comment by eht16** [comment]
@socal-nerdtastic if you are curious and brave enough, you could try the Geany and Geany-Plugins installers from:
https://github.com/geany/geany-plugins/actions/runs/8679662809/artifacts/1412215267

They should work now.
But aware, these installers are created from GIT master, the current development state. Though usually this works pretty stable.
