### ISSUE TITLE
Issues compiling geany-plugins as geany is not found by pkg-config

### ISSUE THREAD

**Issue by Retro-Hax** [geany/geany-plugins#1371]
As the Title says i am having an issue compiling the geany-plugins repo :(
For geany i did as the Readme.md File explained ```./autogen.sh && make -j8 && sudo make install``` and found geany bin, include and libs files under ```/usr/local/```
Sadly geany-plugins did not seem to detect geany as a package under pkg-configs and i honestly have no idea how to fix it since even when i changed or added geanys path to it i was still meet with the same error :(
```
$ pkg-config --cflags geany
Package geany was not found in the pkg-config search path.
Perhaps you should add the directory containing `geany.pc'
to the PKG_CONFIG_PATH environment variable
Package 'geany', required by 'virtual:world', not found

$ pkg-config --libs geany
Package geany was not found in the pkg-config search path.
Perhaps you should add the directory containing `geany.pc'
to the PKG_CONFIG_PATH environment variable
Package 'geany', required by 'virtual:world', not found
```
This works obviously but i cant seem to find the buildscript to edit it :(
```
$ pkg-config --cflags ../geany/geany.pc
-DGTK -I/usr/local/include/geany -I/usr/local/include/geany/tagmanager -I/usr/local/include/geany/scintilla -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/cloudproviders -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/sysprof-6 -pthread -I/usr/include/gio-unix-2.0
$ pkg-config --libs ../geany/geany.pc
-L/usr/local/lib -lgeany -lgtk-3 -lgdk-3 -lz -lharfbuzz -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
```

**Comment by elextr** [comment]
The `geany.pc` should be installed in `$prefix/lib/pkgconfig/` where it appears your prefix is default `/usr/local`.  That should also be the default search for [`pkg-config`](https://linux.die.net/man/1/pkg-config)  but perhaps your unknown distro has configured `pkg-config` search path differently.

If that is the case you should follow the instructions `pkg-config` gave and modify the specified environment variable to include where `geany.pc` was installed before running the build for `geany-plugins`.

**Comment by Retro-Hax** [comment]
> The `geany.pc` should be installed in `$prefix/lib/pkgconfig/` where it appears your prefix is default `/usr/local`. That should also be the default search for [`pkg-config`](https://linux.die.net/man/1/pkg-config) but perhaps your unknown distro has configured `pkg-config` search path differently.
> 
> If that is the case you should follow the instructions `pkg-config` gave and modify the specified environment variable to include where `geany.pc` was installed before running the build for `geany-plugins`.

well i found that it put out the pc file for geany at ```/usr/local/lib/pkgconfig/``` so i just decided to move it to from ```/usr/local/lib/pkgconfig``` to ```/usr/lib/pkgconfig/``` which is a bit messed up and not recomenned but atleast it work on arch linux now and i can compile it sucesfully :P
sorry for the dumb question :(

**Comment by b4n** [comment]
You can also use the [`PKG_CONFIG_PATH`]( https://manpages.debian.org/testing/pkg-config/pkg-config.1.en.html#PKG_CONFIG_PATH) environment variable to tell pkg-config where to look for .pc files.
