### ISSUE TITLE
[Addons or Line Operations plugin] Ability to delete a lines content but still leave line number

### ISSUE THREAD

**Issue by advice2020** [geany/geany-plugins#1385]
Not sure if anyone would be interested in adding this to their Geany plugin.
The two plugins that I have seen that may include something like this are
-Addons
-Line Operations

I mentioned this as a request in the Discussions section of Geany (4047) but I do not think something like this is going to be added into the program itself.
Was looking to be able to setup a hotkey that would function similarly to Ctrl+K "Delete current line(s)" but instead of removing the content in the line & the line number itself, it would just delete the content but still leave the line number.
Like the "Delete current line(s)" keybinding, it would also be able to work on multiple selected lines.

Not sure if anyone else would find this useful / be interested in adding this to their plugin?
Thank You

**Comment by eht16** [comment]
There is no need to implement this in code.
It is already possbile as @b4n suggested to you in https://github.com/geany/geany/discussions/4047#discussioncomment-11266551.
