### ISSUE TITLE
compiling geanylua, lua missmatch

### ISSUE THREAD

**Issue by Erixcode** [geany/geany-plugins#1387]
hello there,
I was trying to compile geanylua, as my distro (fedora41) dropped geanylua after fedora23 (why? I don't know), I just needed to compile the geanylua so in configure:
`./configure --enable-geanylua`
got this error at the end of my configure:

```

    checking for gtk±3.0 >= 2.12
    glib-2.0 >= 2.14
    gio-2.0 >= 2.18
    ctpl >= 0.3… no
    checking for rst2html… no
    checking for lua >= 5.1
    lua < 5.2… no
    configure: error: Package requirements (lua >= 5.1
    lua < 5.2) were not met:

    Package dependency requirement ‘lua < 5.2’ could not be satisfied.
    Package ‘lua’ has version ‘5.4.0’, required version is ‘< 5.2’

    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.

```
I cannot find any lua version manager that I can use it under my distro.
I would appreciate any help to get this done

**Comment by Erixcode** [comment]
Fix:
using https://github.com/DhavalKapil/luaver I managed to compile geanylua. thanks

**Comment by eht16** [comment]
This will probably finally resolved by https://github.com/geany/geany-plugins/pull/1238.
