### ISSUE TITLE
GeanyVCS: highlight new/modified/deleted lines like in GEdit

### ISSUE THREAD

**Issue by Elinvention** [geany/geany-plugins#187]
A thing I really appreciate from GEdit is its GIT plugin: it allows you to see which lines were added/modified/deleted from the previous commit. In GeanyVCS there is the diff tool, but it isn't as convenient as GEdit's plugin. I think it would be really nice if this feature were added to GeanyVCS.

**Comment by b4n** [comment]
I have a separate plugin that implements this exactly (git changebar), I just need to take the time to polish and submit it.  I'll try to get to it soon.

**Comment by Elinvention** [comment]
Ok thank you very much!

**Comment by b4n** [comment]
See #189 :)
