### ISSUE TITLE
Webhelper: assertion `column >= 0' failed on loading plugin

### ISSUE THREAD

**Issue by frlan** [geany/geany-plugins#193]
When starting Geany with enabled webhelper plugin it is warning: 

> Breakpoint 1, handler_log (domain=0x7ffff7a6f89b "Gtk", level=G_LOG_LEVEL_CRITICAL, 
>     msg=0x7fff98020890 "IA__gtk_entry_completion_set_text_column: assertion `column >= 0' failed", data=0x0) at ../src/log.c:121
> 121	{
> (gdb) bt
> #0  handler_log (domain=0x7ffff7a6f89b "Gtk", level=G_LOG_LEVEL_CRITICAL, msg=0x7fff98020890 "IA__gtk_entry_completion_set_text_column: assertion `column >= 0' failed", 
>     data=0x0) at ../src/log.c:121
> #1  0x00007ffff5a0a473 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #2  0x00007ffff5a0a622 in g_log () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #3  0x00007fffe7ac7336 in create_toolbar (self=0x9a6810) at ../webhelper/src/gwh-browser.c:984
> #4  gwh_browser_init (self=0x9a6810) at ../webhelper/src/gwh-browser.c:1136
> #5  0x00007ffff5ce2a97 in g_type_create_instance () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #6  0x00007ffff5cc7818 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #7  0x00007ffff5cc92d1 in g_object_newv () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #8  0x00007ffff5cc991c in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
> #9  0x00007fffe7ac8109 in gwh_browser_new () at ../webhelper/src/gwh-browser.c:1232
> #10 0x00007fffe7aca04b in plugin_init (data=<optimized out>) at ../webhelper/src/gwh-plugin.c:430
> #11 0x00000000004ce946 in plugin_load (plugin=0xdc41c0) at ../src/plugins.c:614
> #12 plugin_new (fname=fname@entry=0xc96680 "/usr/local/lib/geany/webhelper.so", load_plugin=load_plugin@entry=1, add_to_list=add_to_list@entry=0) at ../src/plugins.c:769
> #13 0x00000000004d00af in load_active_plugins () at ../src/plugins.c:963
> #14 plugins_load_active () at ../src/plugins.c:1090
> #15 0x00000000004c0107 in main (argc=1, argv=0x7fffffffe168) at ../src/main.c:1177

**Comment by b4n** [comment]
@frlan It's now fixed, thanks for noticing this.
It was actually a tricky bug, because the code itself was correct, but made incorrect by some Geany's redefinitions of GTK APIs… err.
