### ISSUE TITLE
Screenshot for addons plugin is missing

### ISSUE THREAD

**Issue by PerfectCarl** [geany/geany-plugins#201]
The screenshot at url http://plugins.geany.org/images/plugins/addons/addonsb.png is missing.

It is referenced in the addons documentation here : http://plugins.geany.org/addons.html

**Comment by eht16** [comment]
Thanks for reporting.
I re-uploaded the missing image.

@dmaphy do you know why the addons images were missing on Sourceforge?
I uploaded the two images I found on geany.org in /home/geany/plugins.geany.org/plugins.geany.org/images/plugins/addons.
