### ISSUE TITLE
display images on local relative files

### ISSUE THREAD

**Issue by alusiani** [geany/geany-plugins#207]
geany-plugins-markdown-1.24-3 on fedora 21 is unable to read images from local files with relative directory specification. Some other markdown editors with markdown preview (atom, retext) do that.

When downloading a complete web page with Firefox, the images are downloades and are linked in the markdown file as follows:

![](dir/example%20image.png)

the geany plugin behaves like if the image is unreachable. It works however if the link is modified as follows:

![](file://<absolute path to dir>/example%20image.png)

**Comment by codebrainz** [comment]
The plugin uses third party Markdown processors. Depending on how the package was built, it either uses:
http://www.pell.portland.or.us/~orc/Code/discount/
Or:
https://github.com/jgm/peg-markdown
If those libraries get fixed, I can update the plugin to use the new versions.

**Comment by alusiani** [comment]
Thanks for the quick feedback. I will try to find a spare moment myself to look how the other previewers are handling that successfully, to see if there is any simple way to do that for geany.

**Comment by codebrainz** [comment]
I think #501 fixes this.

**Comment by frlan** [comment]
Should be fixed. Please reopen if you see any further action needed.
