### ISSUE TITLE
Overview: Not compiling against cairo 1.10 (e.g. on Windows)

### ISSUE THREAD

**Issue by eht16** [geany/geany-plugins#222]
The Overview plugin uses CAIRO_ANTIALIAS_GOOD which is only available since Cairo 1.12.
But on Windows, the latest available binary build of Cairo (at least on gtk.org) is 1.10 and so currently the plugin cannot be compiled (see http://nightly.geany.org/win32/build_win32_plugins_stderr.log).

We could either:
a) require Cairo 1.12 for this particular plugin
b) adjust the code to only use CAIRO_ANTIALIAS_GOOD if available
c) require Cairo 1.12 generally in G-P

c) would actually be possible, I found some binaries on http://sourceforge.net/projects/dia-installer/files/cairo/1.12.16/cairo-devel-1.12.16.zip/download.

**Comment by codebrainz** [comment]
It probably doesn't matter, it's so zoomed-out, probably any anti-alias will suffice.
