### ISSUE TITLE
Markdown: Highlight support for HTML comments

### ISSUE THREAD

**Issue by Akronix** [geany/geany-plugins#230]
Hello.

Markdown plugin does not highlight [html comments that are used in markdown as well.] (http://stackoverflow.com/questions/4823468/store-comments-in-markdown-syntax)

**Comment by codebrainz** [comment]
Hi. The syntax highlighting is provided by Geany's main editing engine called [Scintilla](http://www.scintilla.org/), so this kind of bug/enhancement request should really go to [that project's bug tracker](http://sourceforge.net/p/scintilla/feature-requests/). I find a number of problems in the Markdown highlighting as well, but the Scintilla lexers are quite complicated, being written in some kind of C++ dialect.

Thanks for reporting though.
