### ISSUE TITLE
Does not compile.

### ISSUE THREAD

**Issue by agronick** [geany/geany-plugins#231]
I needed to delete geanyprj, overview, and projectorganizer to get everything to compile. They all had local problems in the code.

**Comment by agronick** [comment]
I removed the offending plugins and fixed the build script. It can be downloaded here: https://github.com/agronick/geany-plugins

**Comment by codebrainz** [comment]
It would be more useful if you said *why* they don't compile, like showing the error messages, telling which build system you used, why you didn't just configure with `--disable-whatever-plugin` and instead physically removed several well-maintained plugins, etc. oh well...

**Comment by agronick** [comment]
You can do a git clone on the repo and it actually compiles for you? I 
didn't remove them from anything anyone cares about. I didn't commit it 
as a patch as if its a valid fix. Its a hack.

Here is error 1:
project.c:328:10: note: expected 'gboolean' but argument is of type 
'gchar *'
project.c:328:10: error: too few arguments to function 
'geany_functions->p_tm->tm_source_file_new'
project.c: In function 'geany_project_add_file':

Here is error 2:
.libs/overview_la-overviewscintilla.o: In function 
`overview_scintilla_goto_point':
/tmp/plugins/geany-plugins/overview/overview/overviewscintilla.c:443: 
undefined reference to `scintilla_get_type'
/tmp/plugins/geany-plugins/overview/overview/overviewscintilla.c:445: 
undefined reference to `scintilla_get_type'
.libs/overview_la-overviewscintilla.o: In function `on_scroll_event':
/tmp/plugins/geany-plugins/overview/overview/overviewscintilla.c:432: 
undefined reference to `scintilla_get_type'
.libs/overview_la-overviewscintilla.o: In function `on_focus_in_event':
/tmp/plugins/geany-plugins/overview/overview/overviewscintilla.c:345: 
undefined reference to `scintilla_get_type'
.libs/overview_la-overviewscintilla.o: In function `sci_get_midline_':
/tmp/plugins/geany-plugins/overview/overview/overviewscintilla.c:633: 
undefined reference to `scintilla_get_type'
.libs/overview_la-overviewscintilla.o:/tmp/plugins/geany-plugins/overview/overview/overviewscintilla.c:634: 
more undefined references to `scintilla_get_type' follow

Here is error 3:
rjorg-sidebar.c:561:40: error: 'TMTag' has no member named 'file'
   relpath = get_relative_path(path, tag->file->file_name);
                                        ^
prjorg-sidebar.c: In function 'find_tags':
prjorg-sidebar.c:572:55: error: 'TMWorkspace' has no member named 
'tags_array'
  GPtrArray *tags_array = geany_data->app->tm_workspace->tags_array;
                                                       ^
prjorg-sidebar.c:592:25: error: 'TMTag' has no member named 'scope'
    gchar *scopestr = tag->scope ? g_strconcat(tag->scope, "::", NULL) 
: g_strdup("");
                         ^
prjorg-sidebar.c:592:50: error: 'TMTag' has no member named 'scope'
    gchar *scopestr = tag->scope ? g_strconcat(tag->scope, "::", NULL) 
: g_strdup("");
                                                  ^
prjorg-sidebar.c:595:60: error: 'TMTag' has no member named 'file'
    relpath = get_relative_path(get_project_base_path(), 
tag->file->file_name);
                                                            ^
prjorg-sidebar.c:597:8: error: 'TMTag' has no member named 'line'
     tag->line, tm_tag_type_name(tag), scopestr, tag->name, 
tag->arglist ? tag->arglist : "");
        ^
prjorg-sidebar.c:597:63: error: 'TMTag' has no member named 'arglist'
     tag->line, tm_tag_type_name(tag), scopestr, tag->name, 
tag->arglist ? tag->arglist : "");
                                                               ^
prjorg-sidebar.c:597:78: error: 'TMTag' has no member named 'arglist'
     tag->line, tm_tag_type_name(tag), scopestr, tag->name, 
tag->arglist ? tag->arglist : "");


There you go. Hope that helps.

**Comment by frlan** [comment]
Which versions of Geany and plugins you have installed? What is your system? Has your sourcen being clean? Please provide configure output of plugins so we can see which versions and which libs have been found.

**Comment by frlan** [comment]
And btw: I will not merge the commit, as it is a destructive solution which could have been done with a simple change of  GP_ARG_DISABLE() for the plugin(s)

**Comment by b4n** [comment]
This "bug" is because some Geany-Plugins depend on Geany 1.25 (current development version).

If there is a bug it's only that the dependency against Geany is incorrectly low and then accepts 1.24.

We can either make all geany-plugins depend on 1.25, or introduce some other per-plugin solution like e.g. #208.

**Comment by agronick** [comment]
Jesus christ. -_- I didn't commit it as a patch. Its a hack that I made for myself. I posted it just if anyone else doesn't want to go through the trouble of finding each plugin that doesn't compile.

**Comment by agronick** [comment]
By the way the NEWS file explicitly says "Geany Plugins 1.24".

**Comment by b4n** [comment]
> By the way the NEWS file explicitly says "Geany Plugins 1.24". 

Fixed 5f28ed04e3c576542e63982f4a0571e76508dd13

The thing is, the Git version is the development version, and more than often you'll see the documentation files (like NEWS) a bit out of date (it's bad, yes), and a few plugins depending on the development version of Geany too.  Unfortunately for the moment those don't have a check for this dependency and so will just fail to build instead of disable themselves.
