### ISSUE TITLE
git-changebar crashes after loading and performing redo

### ISSUE THREAD

**Issue by techee** [geany/geany-plugins#237]
@b4n There's a (non-critical) crash in git-changebar:

1. deactivate git-changebar in plugin manager
2. make some change in a version-controlled document and undo it (so redo can be performed)
3. activate git-changebar in plugin manager
4. perform redo in the editor

This is the backtrace I get:

Program received signal SIGSEGV, Segmentation fault.
__strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
209	../sysdeps/x86_64/multiarch/../strcmp.S: No such file or directory.
(gdb) bt
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
#1  0x00007ffff5a7ffc9 in g_str_equal () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff5a7f5f0 in g_hash_table_lookup () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff5a9f3c0 in g_quark_from_static_string () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fffc8ad01ec in update_diff (
    path=0x7fffe539cdc0 <error: Cannot access memory at address 0x7fffe539cdc0>, 
    contents=0x7fffc8cd2400 <G_blob_contents>, data=0xc) at ../git-changebar/src/gcb-plugin.c:814
#5  0x00007fffc8ad046e in get_cached_blob_contents_async (user_data=<optimized out>, 
    callback=0x7fffc8ad01a0 <update_diff>, force=0, path=<optimized out>)
    at ../git-changebar/src/gcb-plugin.c:446
#6  do_update_diff_idle (doc_id=12, force=0) at ../git-changebar/src/gcb-plugin.c:847
#7  0x00007ffff5a90703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff5a8fce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff5a90048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff5a9030a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff7076447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#12 0x00007ffff79c97f1 in main_lib (argc=1, argv=0x7fffffffe1b8) at ../src/libmain.c:1215
#13 0x00007ffff75a8ec5 in __libc_start_main (main=0x4006a0 <main>, argc=1, argv=0x7fffffffe1b8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe1a8) at libc-start.c:287
#14 0x00000000004006ce in _start ()

**Comment by b4n** [comment]
@techee good catch!  Could you confirm the commit referenced above fixes the issue for you?  https://github.com/b4n/geany-plugins/commits/git-changebar/wip

**Comment by techee** [comment]
The patch fixes it for me, thanks!
