### ISSUE TITLE
multiterm plugin has no translation strings

### ISSUE THREAD

**Issue by scriptum** [geany/geany-plugins#247]
Please add them

**Comment by codebrainz** [comment]
Should probably rename this "Mutliterm plugin has no strings" :)

I think literally the only string is the description of the plugin passed to `plugin_set_info()`. I'm not sure if the `_` function-like macro is available from Vala or whether adding a generated C file to `POTFILES.in` would cause any grief.

**Comment by scriptum** [comment]
At least plugin description - thin is the one untranslated.

**Comment by b4n** [comment]
@codebrainz I just started to try and see how it would work, and apparently at least recent versions of xgettext have Vala support, so it'll work.  I'll open a PR soon

**Comment by b4n** [comment]
> I think literally the only string is the description of the plugin passed to `plugin_set_info()`.

It has, in a popup menu (and warnings, though those might not need translations as they are only logged on the messages, not really in the UI).

> I'm not sure if the `_` function-like macro is available from Vala

It is :)

> or whether adding a generated C file to `POTFILES.in` would cause any grief.

It would, as updating the translations require all the files containing translations to be available.  Using a C file generated from Vala would mean having build MultiTerm is a requirement to update translations -- and that's probably not really acceptable.
That's the same reason why I have *webhelper/src/gwh-enum-types.c* under version control, although it shouldn't be as it's a generated file.
