### ISSUE TITLE
Do not use the word "plugin" in plugins description

### ISSUE THREAD

**Issue by b4n** [geany/geany-plugins#250]
Strings like _This plugin provides_ or alike should be avoided in plugins description, and most occurrences of the "plugin" word should probably be double checked.

The point is that at the very least in the Plugin Manager any occurrences of the word "plugin" used to refer to the plugin itself is plain redundant and just makes strings longer, less clear and less consistent.

In other places it might be OK to use the word "plugin" to refer to the plugin itself, if it could be confused with something else.

**Comment by b4n** [comment]
See also #248

**Comment by frlan** [comment]
I don't have any plugin installed still having the issue. Closing
