### ISSUE TITLE
Command to compile documentation to HTML is not working

### ISSUE THREAD

**Issue by frlan** [geany/geany-plugins#255]
The provided command to compile geanylatex's documentation to HTML is not working. Provided command command is 

```
htlatex geanylatex.tex xhtml -cvalidate -interaction=batchmode
```

Happend on Debian Testing with Version 3.14159265-2.6-1.40.15

**Comment by LarsGit223** [comment]
@frlan: Is this issue still existing? I ran ```htlatex latex.tex xhtml -cvalidate -interaction=batchmode``` on my machine and it seems to work out alright. The HTML files are there afterwards and look ok.

**Comment by frlan** [comment]
@LarsGit223 It really works. Weird. Thanks for rechecking
