### ISSUE TITLE
Ctrl+tab doesn't work when Overview plugin enabled

### ISSUE THREAD

**Issue by Yanpas** [geany/geany-plugins#265]
Nuff said. As well as broken tab names and broken GOTOline function.

**Comment by codebrainz** [comment]
Works for me:
http://codebrainz.ca/screencasts/overview-ctrltab-gotoline.avi

> Nuff said

Not really :)  What OS, distro, and Geany version? What other plugins are enabled?

Can you paste your `~/.config/geany/plugins/overview/prefs.conf` file into a Gist and link it here?

**Comment by codebrainz** [comment]
Also, can you paste the contents of `Help->Debug Messages` into a gist and link it here? Just open Geany and try and do the stuff that's not working (Ctrl+Tab, goto line) and then grab the text from that Debug Messages dialog right after, so it's only showing debug output from a clean session after the broken features try to run.

**Comment by Yanpas** [comment]
Xubuntu 15.04, Geany 1.24.1 (from vivid standart sources), GTK+ 3.14 (shipped with system, gess geany was built with 3.14)
Also enabled Addons, Code nav, Debugger.
`~/.config/geany/plugins/overview/prefs.conf`:
```
[overview]
width=120
zoom=-10
show-tooltip=true
show-scrollbar=true
double-buffered=true
scroll-lines=4
overlay-enabled=true
overlay-inverted=true
visible=true
position=right
overlay-color=#000000000000
overlay-alpha=0.10000000000000001
overlay-outline-color=#000000000000
overlay-outline-alpha=0.10000000000000001
```
Debug messages (all files opened in geany do not exist on hard drive, for test I created localy: main.c etc)
```
 Loaded /usr/share/geany/python.tags (Python), 5964 tag(s).
21:14:49: Geany CRITICAL	: document_check_disk_status: assertion 'doc != NULL' failed
21:14:50: Geany CRITICAL	: document_check_disk_status: assertion 'doc != NULL' failed
21:14:51: Geany CRITICAL	: document_check_disk_status: assertion 'doc != NULL' failed
...
and so on
```

**Comment by Yanpas** [comment]
Well Ctrl+tab works, it just move you to the last tab (PAge 3) and then stops

**Comment by codebrainz** [comment]
Do mind trying without those other plugins enabled to rule out any conflicts between Overview and them?

The only majour difference I see that my Geany is built against GTK+ 2.

Also if you don't mind to paste the full debug messages into a Gist, it's useful to see all what versions and other stuff. It shouldn't contain any "sensitive" info, at most the names of the files/projects being opened.

**Comment by Yanpas** [comment]
Sorry, geany from ubuntu repos is built on gtk2 libraries.
Still the same with disabled plugins
```
21:29:58: Geany INFO		: Geany 1.24.1, en_US.UTF-8
21:29:58: Geany INFO		: GTK 2.24.27, GLib 2.44.1
21:29:58: Geany INFO		: System data dir: /usr/share/geany
21:29:58: Geany INFO		: User config dir: /home/xxx/.config/geany
21:29:58: Geany INFO		: System plugin path: /usr/lib/x86_64-linux-gnu/geany
21:29:58: Geany INFO		: Added filetype Scala (58).
21:29:58: Geany INFO		: Added filetype CUDA (59).
21:29:58: Geany INFO		: Added filetype Cython (60).
21:29:58: Geany INFO		: Added filetype Graphviz (61).
21:29:58: Geany INFO		: Added filetype Go (62).
21:29:58: Geany INFO		: Added filetype Clojure (63).
21:29:58: Geany INFO		: Added filetype Genie (64).
21:29:58: Geany INFO		: Loaded:   /usr/lib/x86_64-linux-gnu/geany/addons.so (Addons)
21:29:58: Geany INFO		: Loaded:   /usr/lib/x86_64-linux-gnu/geany/codenav.so (Code navigation)
21:29:58: Geany INFO		: Loaded:   /usr/lib/x86_64-linux-gnu/geany/debugger.so (Debugger)
21:29:58: Geany INFO		: Loaded:   /usr/lib/x86_64-linux-gnu/geany/overview.so (Overview)
21:29:59: Geany INFO		: unknown : None (UTF-8)
21:29:59: Geany CRITICAL	: document_grab_focus: assertion 'doc != NULL' failed
21:32:38: Geany INFO		: Plugin "/usr/lib/x86_64-linux-gnu/geany/addons.so" already loaded.
21:32:38: Geany INFO		: Plugin "/usr/lib/x86_64-linux-gnu/geany/codenav.so" already loaded.
21:32:38: Geany INFO		: Plugin "/usr/lib/x86_64-linux-gnu/geany/debugger.so" already loaded.
21:32:38: Geany INFO		: Plugin "/usr/lib/x86_64-linux-gnu/geany/overview.so" already loaded.
21:32:38: Geany INFO		: Added 41 plugin(s) in '/usr/lib/x86_64-linux-gnu/geany'.
21:32:39: Geany INFO		: Unloaded: /usr/lib/x86_64-linux-gnu/geany/addons.so
21:32:43: Geany INFO		: Unloaded: /usr/lib/x86_64-linux-gnu/geany/codenav.so
21:32:44: Geany INFO		: Unloaded: /usr/lib/x86_64-linux-gnu/geany/debugger.so
21:32:48: Geany CRITICAL	: is_position_on_tab_bar: assertion 'tab != NULL' failed
21:32:50: Geany INFO		: untitled.rb : Ruby (UTF-8)
21:32:51: Geany CRITICAL	: document_check_disk_status: assertion 'doc != NULL' failed
21:32:52: Geany CRITICAL	: document_check_disk_status: assertion 'doc != NULL' failed
21:32:53: Geany INFO		: untitled.c : C (UTF-8)
21:32:53: Geany INFO		: Loaded /usr/share/geany/c99.tags (C), 1618 tag(s).
21:32:55: Geany CRITICAL	: document_check_disk_status: assertion 'doc != NULL' failed
21:32:56: Geany CRITICAL	: document_check_disk_status: assertion 'doc != NULL' failed
21:33:35: Geany CRITICAL	: document_check_disk_status: assertion 'doc != NULL' failed
21:33:36: Geany CRITICAL	: document_check_disk_status: assertion 'doc != NULL' failed
21:33:37: Geany CRITICAL	: document_check_disk_status: assertion 'doc != NULL' failed
```

**Comment by Yanpas** [comment]
Latest geany building was unsuccessful too (: 
https://gist.github.com/Yanpas/6238e05fcb8f35ad1d7a
But I believe latest geany works better with overview
$ geany 
geany: error while loading shared libraries: libgeany.so.0: cannot open shared object file: No such file or directory

**Comment by codebrainz** [comment]
I think that's a bug in Ubuntu, and IIRC you need to run `ldconfig` as sudo/root, to update the loader's search paths or something.

**Comment by Yanpas** [comment]
Yes, now this plugin works fine.
Tabs' names are correct, ctrl+tab works and goto line too.

Surprisingly that this plugin is so version-dependent. 1.24 vs 1.25

`ldconfig` helped, thx :smiley_cat:
