### ISSUE TITLE
Addons: Hard coded http:// inside image link of documentation 

### ISSUE THREAD

**Issue by frlan** [geany/geany-plugins#276]
At the Addons plugi nREADME there is a "http://" image references even when accessed via https://.
This is the full http:// image URL is hard-coded.

**Comment by b4n** [comment]
I see a few solutions for this, with various pros and cons:

* Use protocol-relative URL.  This is easy, just strip the `http:`.
  * pros: easy
  * cons: URL won't work on `file://`, e.g. when the user opens it locally.  This might not be a big deal as nothing seems to generate the HTML by default.
* Use absolute (or relative) paths, not URLs:
  * pros and cons: same as above, but additionally it's not obvious where one can find the image.
* strip `http://plugins.geany.org` when generating the website:
  * pros: works everywhere
  * cons: needs to be added to the generation script
* use `https://` URLs:
  * pros: works everywhere
  * cons: requires HTTPS to work seamlessly for everyone.

**Comment by codebrainz** [comment]
There's also the Markdown README file which had and still has broken image links. It works locally but whatever magic scripts on the server breaks all the images.

**Comment by eht16** [comment]
@codebrainz I fixed the Markdown image issue yesterday manually by copying the images into the docroot. But I wasn't aware they are rsync'ed away every night when the pages are recreated.
So I added a hack in 8aca6a5f045d890d1e3105029460f461ad4173f9 to copy them again after they got deleted. Not nice but will do for the moment.

@dmaphy needs to help with this.

**Comment by eht16** [comment]
For the main issue, for now I chose some variant of option 1 from @b4n 's great list. Thanks for that.

I added another hack to the website generation scripts to replace http://plugins.geany.org/ by //plugins.geany.org/ which seems to work (https://github.com/geany/plugins.geany.org/commit/75804ae28e86c38a281b6daa4ff9fb964129689a).
So the HTTP protocol is removed at the website generation step. While this is hacky, at least I could keep proper and working image URLs in the Addons' README which isn't the most important thing but nice to have in case a user reads the plain file and manually open the image URL in a browser.

Ideally, at some point we will be able to just use SSL everywhere.

**Comment by codebrainz** [comment]
It's too bad we couldn't just use Markdown for the plugin READMEs, then they would show up properly on Github and we could use one of the many JavaScript Markdown processors for viewing on the website. We could keep all the images under source control where they need to be anyway for local installation and the links to Github ought to be stable enough.

**Comment by eht16** [comment]
I don't think we are that tied to ReST for the plugin READMEs.
I don't know about Javascript Markdown processors but I guess it's possible to use them also for the G-P website. We just need to improve the website generation scripts to alternatively work with Markdown READMEs. Maybe @dmaphy wants to work on this.
