### ISSUE TITLE
Can we have spelling corrections listed up top of right-click context menu?

### ISSUE THREAD

**Issue by SmithWillSuffice** [geany/geany-plugins#287]
It saves a heck of a lot of time when you can simply select the top context menu item as the correct spelling, like SublimeText does, or like Firefox does right now as I edit this post.   It is annoying to have to run the mouse over the "Spelling suggestion" submenu, especially when the mouse move slips off the menu area.  This'd be awesome, thanks.  (Also, if anyone can send me a note on how to tweak plugins, I might be able to hack it myself.)

**Comment by eht16** [comment]
Implemented in #290 as a configurable alternative to populate the editor menu, feedback is welcome.
