### ISSUE TITLE
plugin Numbered Bookmarks activated causes geany to crash at start-up

### ISSUE THREAD

**Issue by peter-scholtens** [geany/geany-plugins#301]
When the plugin Numbered Bookmarks is switched on, Geany crashes instantly on start-up. Running GDB shows the following warning:

Program received signal SIGSEGV, Segmentation fault.
0x00007fffd153f2f4 in SetMarker (sci=0x9fa4a0, bookmarkNumber=1, markerNumber=2, line=247) at geanynumberedbookmarks.c:885
885		fd=GetFileData(document_get_current()->file_name);

I assume that at start-up the call <b>document_get_current()</b> will return a NULL pointer? And asking a <b>file_name</b> member will cause a segfault?

Tested on geany-plugins commit 4c1137373f78bd13df9ee46c10876a3142675573 of Nov. 8th, 2015.

**Comment by frlan** [comment]
Something like this could solve the issue: 

    @@ -874,6 +874,7 @@ static gint NextFreeMarker(ScintillaObject* sci)
     static void SetMarker(ScintillaObject* sci,gint bookmarkNumber,gint markerNumber,gint line)
     {
            guint32 *markers;
     static void SetMarker(ScintillaObject* sci,gint bookmarkNumber,gint markerNumber,gint line)
     {
            guint32 *markers;
    +       GeanyDocument *doc;
            FileData *fd;
     
            /* insert new marker */
    @@ -882,6 +883,10 @@ static void SetMarker(ScintillaObject* sci,gint bookmarkNumber,gint markerNumber
            scintilla_send_message(sci,SCI_MARKERADD,line,markerNumber);
     
            /* update record of which bookmark uses which marker */
    +
    +       doc = document_get_current();
    +       g_return_if_fail(doc != NULL);
    
but I doubt that this will be without side effect.

**Comment by peter-scholtens** [comment]
I see no side effects, except the signal of the failing assertion:
** (geany:21329): CRITICAL **: SetMarker: assertion 'doc != NULL' failed

Weirdly enough, it depends on the project I select to load into geany: either no problem occurs or it crashes (or reports the warning signal when the above path is applied).

**Comment by frlan** [comment]
I could imagine this is caused by some timing. And in fact, the usage of the current document is not very good.

**Comment by codebrainz** [comment]
Aside from passing the `GeanyDocument` instead of the `ScintillaObject`, and getting to the `sci` pointer through `doc->editor->sci` or whatever, there's also a (non public) function [document_find_by_sci](https://github.com/geany/geany/blob/master/src/document.h#L244) that could be used to find the document for the scintilla widget (if it was in plugin API).
