### ISSUE TITLE
1.24 branch ?

### ISSUE THREAD

**Issue by J-Dunn** [geany/geany-plugins#302]
I want to build geany-plugins from source to apply a patch for cross-debugging but it seems that master has a requirement for geany 1.25 which is not available on my distro ( 1.24 installed ).

I don't see a branch for geany-plugins 1.24

neither do I find a changelog for  geany-plugins to see where the 1.25 condition comes from.  I suspect I should be able to build the scope plugin with what I have .

Is there no plugins version that is compatible with geany 1.24 ?

Thanks.

**Comment by frlan** [comment]
There is not post release branch of 1.24. Use 1.24 tag as basis and use a local branch.

Somthing like:

    git checkout 1.24
    git checkout -b 1.24_local

Most likely we will not set up a global branch for 1.24 as it is already quiet old.

**Comment by J-Dunn** [comment]
Thanks for the quick reply. I created a local 1.24 but configure still throws it out requiring geany 1.25

```
git checkout 1.24
Note: checking out '1.24'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 0f9e8cb... Fix typos and little rewording
bash-4.2#git checkout -b 1.24_local
Switched to a new branch '1.24_local'
```

```
./configure
....
checking for GEANY... no
configure: error: Package requirements (geany >= 1.25) were not met:

Requested 'geany >= 1.25' but version of Geany is 1.24.1
```

Is there  no changelog maintained for this project? I suspect this is a false problem for building scope.

**Comment by frlan** [comment]
You need to rerun autogen.sh here. Maybe just cleanup complete working dir or do a complete fresh clone. However, if this needs to be discussed further I'd suggest to do on the mailing list.

**Comment by frlan** [comment]
Also... scope has been under heavy development since 1.24. You might want to get a 1.26-geany-environment nevertheless.
