### ISSUE TITLE
scope working dir does not accept a dir

### ISSUE THREAD

**Issue by J-Dunn** [geany/geany-plugins#304]
I have just built a clean git clone of geany and geany-plugins. 
./configure --disable-all-plugins --enable-scope

Using Debug | Setup Program dialogue I attempt to set "Working dir" but it will not  accept a dir. In fact this seems to be a FILE open dialogue. I have to select file and click "open",  then manually edit off the file name part 

Fedora 20, using  gtk2   2.24.27

I have not worked with GTK+ recently but it seems the relevant call is :

gtk.FileChooser.set_action()
gtk.FILE_CHOOSER_ACTION_SELECT_FOLDER

https://developer.gnome.org/gtkmm/stable/classGtk_1_1FileChooser.html#ac455a88d080c044c03abb343c46b38db

**Comment by J-Dunn** [comment]
Bug fix:

geany-plugins/scope/src/program.c 

```  working_dir_entry = GTK_ENTRY(get_widget("program_working_dir_entry"));
  gtk_entry_set_max_length(working_dir_entry, PATH_MAX);
  stash_group_add_entry(group, &program_working_dir, "working_dir", "", working_dir_entry);
  ui_setup_open_button_callback(get_widget("program_working_dir_button"), NULL,
    GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER, working_dir_entry);
//    GTK_FILE_CHOOSER_ACTION_OPEN, working_dir_entry);
```

**Comment by J-Dunn** [comment]
BTW I see that these dialogues are being created using glade, so if glade is used for future work, that change may need to carried over into glade by whoever maintains that side of things. 

The change to the actual source code provided above is tested and allows selection of the directory.

**Comment by codebrainz** [comment]
Confirmed not working on Win 10 with latest release of GP.
