### ISSUE TITLE
Projectorganizer: Find in Files

### ISSUE THREAD

**Issue by derba** [geany/geany-plugins#327]
Projectorganizer plugin lets us add external directories. But Find in Files searches in a specific directory only instead of the whole project.

I have a project for my app and added external directories for some libraries. And I cannot search in the whole project.

**Comment by techee** [comment]
@derba You can - under the "Project" menu there's "Find in project files" which always uses the project root as the search directory. You can also assign a custom keybinding for it.

I wanted to make it default in Geany in https://github.com/geany/geany/pull/454 but others didn't like it so there has to be a different keybinding for project find in files.

**Comment by b4n** [comment]
@techee IIUC the OP's point is that it can sear in only *one* directory, whereas ProjectOrganizer allows for several directories.  So in the end, one can't search at once the whole set of files PrjOrg knows about.

**Comment by techee** [comment]
Aha, alright. Well, there's a problem - I'm just using Geany's FIF dialog and there you can search just inside a single directory. I guess in this case the best solution will be the project containing symlinked directories (after I fix that).

**Comment by derba** [comment]
Now symlinking works in Projectorganizer. Still, Find in Files does not work. But that seems to be a 1 character issue (use 'R' instead of 'r') in get_grep_options() in search.c of Geany itself.

This issue shows that the whole plugin architecture have its limitations. How could Geany's FIF know about PO's external directories? Maybe PO should have a "symlink external directory" button. (Except on Windows, as mklink won't to that for you easily.)

**Comment by techee** [comment]
Good point about the grep options, created a pull request to Geany here:

https://github.com/geany/geany/pull/895

> This issue shows that the whole plugin architecture have its limitations. How could Geany's FIF know about PO's external directories?

It cannot, it's something I introduced just in my plugin. Geany in general can search in just a single directory (like most other editors and I think it should stay this way). You can however pre-fill the external directory to the FIF dialog by right-clicking it in the sidebar and selecting "Find in Files...".

> Maybe PO should have a "symlink external directory" button. (Except on Windows, as mklink won't to that for you easily.)

I'd leave the symlink creation up to users - as you say, it works on just some platforms and I don't think it's something the plugin itself should do.

**Comment by techee** [comment]
@derba It appears -R isn't available in all grep implementation. However in the Find in Files dialog you can add -R to the "extra options" - it is added behind the previously set flags and at least on my machine seems to override -r.
