### ISSUE TITLE
Projectorganizer: Directory symbolic links

### ISSUE THREAD

**Issue by derba** [geany/geany-plugins#331]
I tried to use Projectorganizer to add external directories to my project, but that feature have horrible issues, especially when it comes to tagging. Another approach is to use create symbolic links to those external directories in my project directory. Unfortunately that does not work either. Directory symlinks are not followed by taggers (Geany's and GeanyCtags plugin). And dir symlinks are not visible in Project sidebar.

**Comment by techee** [comment]
Thanks, will fix.

**Comment by techee** [comment]
Should be fixed now with 

https://github.com/geany/geany-plugins/commit/e71d268faceb8bbbb71bd09e176173e02e373f56

Please let me know if it works for you.

**Comment by derba** [comment]
It took me a while to find out how to generate configure script, especially find `sudo apt-get build-dep geany-plugins` command to get all the dependencies.

It works fine. Thank you.

**Comment by techee** [comment]
Good to hear, thanks for testing.
