### ISSUE TITLE
Projectorganizer: When each file is closed then Build menu is grayed out

### ISSUE THREAD

**Issue by derba** [geany/geany-plugins#333]
Project Organizer lets users close files, while retaining them in the project. Unfortunately Geany disables Build menu in that case, even though "Independent commands" of the project may make sense. E.g. I set "gitk --all" and "git gui" here, as I do not know where else to put them and GeanyVC plugin is not advanced enough for me.

It may not be a Project Organizer bug, just somewhat inconsistent behavior with Geany. Probably I should add these commands somewhere else, if only I knew where. After all, these are not "Build" commands. Still, real build commands are not available when closing each file.

**Comment by techee** [comment]
@derba This is a Geany thing - it has nothing to do with ProjectOrganizer. But yeah, I understand your point - please create a corresponding Geany bug report.
