### ISSUE TITLE
Debugger: unable to remove breakpoints while running

### ISSUE THREAD

**Issue by Yanpas** [geany/geany-plugins#335]
Version 1.26 (grom geany-dev ppa, trusty), gcc 4.8.2. Unable to remove breakpoints while running an app in debugger. I get error `-var-create: unable to create variable object"`

**Comment by b4n** [comment]
Seems to work for me in the current development version.  Please try it, because it changed a lot since 1.26 (see #202).

**Comment by Yanpas** [comment]
Yes, it works with master version. Could you please backport current debugger to 1.2.6? Neither 1.2.5 nor 1.2.6 provide working debugger which is sad. And how soon 1.2.7 will be released? If soon - I'll just wait

**Comment by b4n** [comment]
Probably around mid March.

**Comment by Yanpas** [comment]
Thanks!
