### ISSUE TITLE
Scope: Does not run executable

### ISSUE THREAD

**Issue by codebrainz** [geany/geany-plugins#337]
I have selected an executable from a subdir of `E:\Projects` and when pressing the run button it says "The system cannot find the file specified.", which is odd since the the "Setup Program" dialog allowed me to select the file using the file dialog, so I know the file exists. Perhaps it's just a misleading error message?

Under Windows 10 using Geany and Geany 1.26 releases.

**Comment by zhekov** [comment]
It is. Scope will report such an error if it fails to run gdb, which is possible under WIn32 if you run Geany via the start menu/screen, and your System PATH does not include the gdb directory.

Select Tools -> Configuration files -> scope.conf, and set your full gdb executable name.
