### ISSUE TITLE
configure missing and autogen.sh fails

### ISSUE THREAD

**Issue by hg2581** [geany/geany-plugins#379]
According to the instructions I should be able to run either ./configure or ./autogen.sh, however, configure file is missing and autogen.sh fails because "macro AM_GLIB_GNU_GETTEXT  not found in library".

Should the ./configure file exist or should the instructions be corrected? I assume autogen.sh fails because of missing dependencies? Can they be pulled in automatically?

**Comment by b4n** [comment]
The configure is not supposed to exist in the Git tree, only in tarballs.  Git trees require you to run *autogen.sh*.  To generate it properly you need GLib's development files.

**Comment by hg2581** [comment]
I used yum to install glib-devel which I think is the Centos/RHEL version of Glib's development files. Even so, running ./autogen.sh in the geany-plugin directory failed with the exact same error message as below. Did I misunderstand what I need to do?

**Comment by frlan** [comment]
Google told me something like glib2-devel -- give it a try.

**Comment by b4n** [comment]
also you'll need gettext and others, but it shouldn't be the reason here.  Anyway, a Fedora .spec file suggests you need glib2-devel, gtk2-devel, pango-devel, gettext and intltool.

**Comment by hg2581** [comment]
Thank you, have installed all of the above. Now I get as far as:
"checking for GEANY... configure: error: Package requirements (geany >= 1.26) were not met:
No package 'geany' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GEANY_CFLAGS
and GEANY_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details."
Version 1.26 of geany is indeed installed and PKG_CONFIG_PATH is empty.

**Comment by hg2581** [comment]
I should have mentioned that geany is installed in /usr/bin/geany and can be found in the path.

**Comment by frlan** [comment]
Are there also the dev-files of Geany installed?

**Comment by hg2581** [comment]
I have the geany-libgeany-1.26 package installed. Are you thinking of another package?

**Comment by frlan** [comment]
If you are using geany-plugins from current git repo it depends on Geany 1.27. You will need to install geany 1.27 too (not yet release) or use geany-plugins 1.26

**Comment by b4n** [comment]
@hg2581 what does `pkg-config --modversion geany` tells you?  and if it says it doesn't find any packages like this, check whether you have a file named *geany.pc* somewhere, likely in */usr/lib/pkgconfig* or */usr/local/lib/pkgconfig*.  If you don't have this file anywhere on your system, then the development files for Geany aren't properly installed.

BTW, I could imagine your distro having something like *geany-devel*, *geany-libgeany-1.26-devel* or alike, in which case you should install it to get the appropriate development files.

**Comment by b4n** [comment]
But @frlan in right, if you want to build the development version of Geany-Plugins, you'll need the development version of Geany for several of them.

**Comment by hg2581** [comment]
autogen.sh from github tests for geany version 1.26, not for version 1.27.

**Comment by hg2581** [comment]
Yes, I used the git source, now I downloaded the plugins version 1.26 and tried to run ./configure but encountered the same error message. pkg-config --modversion geany tells me:
"Package geany was not found in the pkg-config search path.
Perhaps you should add the directory containing `geany.pc'
to the PKG_CONFIG_PATH environment variable
No package 'geany' found"
I then looked for geany.pc but it is not on the system. Unfortunately "yum install geany-devel" finds version 1.24 in EPEL but I have version 1.26 of geany installed from melvilletheatre.
Next step: where do I find the development files for geany 1.26 and what do I need to do?
And, could we get the current version of geany and associated files into EPEL?
Thank you for your help!

**Comment by frlan** [comment]
On 04.03.2016 21:45, hg2581 wrote:
> autogen.sh from github tests for geany version 1.26, not for version 1.27.
> 

Actually this is true. But most liekly will not work.

**Comment by frlan** [comment]
Well... either ask your distributor to package a newer version of Geany or install your complete Geany stack from source and don't depend on Centos packages. You can download the latest stable versions from geany.org or do a git clone for most recent development version from https://github.com/geany/geany

**Comment by hg2581** [comment]
How do I get any missing development files for geany? I have already installed gtk2-devel  and intltool mentioned on http://www.geany.org/manual/reference/howto.html.

Apparently geany.pc is missing?

**Comment by b4n** [comment]
*geany.pc* is installed by Geany.  If you built Geany from source, it'll likely be installed to `/usr/local/lib/pkgconfig`.  If your system doesn't use this path for looking up pkg-config files by default, alter the `PKG_CONFIG_PATH` variable before running Geany-Plugin's configure script:
`export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"`, then `./configure`.  It should also allow `pkg-config --modversion geany` to find Geany and show you the installed version number.

**Comment by codebrainz** [comment]
Also use the weird `--with-geany-libdir=/the/prefix/lib` option to Geany-Plugins' `configure` script, I think it might affect the pkg-config lookup path.

**Comment by bbrady1992** [comment]
I know this is closed, but just in case somebody else runs into this issue - I installed geany-devel and it fixed the issue.

**Comment by chaotaklon** [comment]
bbrady1992's answer works for me.

In Centos,
$ sudo yum install geany-devel

solves:
"checking for GEANY... configure: error: Package requirements (geany >= 1.26) were not met:
No package 'geany' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GEANY_CFLAGS
and GEANY_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details."
