### ISSUE TITLE
GeanyFunctions depreciation warnings

### ISSUE THREAD

**Issue by techee** [geany/geany-plugins#382]
Most of the plugins now complain about GeanyFunctions being deprecated which makes the compilation output rather noisy. I have removed GeanyFunctions from my plugins but this requires bumping API to a post-linkage-cleanup build, which is 224.

To get rid of the warnings there are two options:

1. Remove geany_functions and bump the API requirement for every plugin.
2. Guard the geany_functions declaration with a macro checking the API version.

I'd personally vote for (1) otherwise the deprecated declaration gets never removed. Is it a problem to bump the API requirement? Is it common to build new plugin versions with old Geany versions?

**Comment by eht16** [comment]
I'd also agree for (1).

I've just done this for the Addons and SpellCheck plugins.

Keeping compability with old Geany versions is a nice-to-have I'd say but not really necessary as we try to release Geany-Plugins together with Geany itself. So this should be fine.

**Comment by b4n** [comment]
Agreed, we should rather drop them.  And as it's already in 1.26 even.

**Comment by techee** [comment]
Good, will prepare a patch.
