### ISSUE TITLE
`make check` broken if MultiTerm is disabled

### ISSUE THREAD

**Issue by b4n** [geany/geany-plugins#390]
```console
Making check in po
make[1]: Entering directory `/home/travis/build/b4n/geany-plugins/_build/po'
make[1]: *** No rule to make target `../../multiterm/src/config.c', needed by `geany-plugins.pot'.  Stop.
make[1]: Leaving directory `/home/travis/build/b4n/geany-plugins/_build/po'
make: *** [check-recursive] Error 1
```

71fa02ef2f0f846d42a3082136fd236b0da49ab6 listed the *.c* in *POTFILES.in*, but those are only generated when MultiTerm is actually built.

**Comment by b4n** [comment]
I'm testing 1b587222ca0d089c4f1be6d52ba6de6422351bb7 on Travis (yeah I'm trying to resurrect TravisCI on GP)

**Comment by frlan** [comment]
Good point. But wondering what is the correct way here. This will apply to all vala plugins with translations I guess.

**Comment by b4n** [comment]
@frlan apparently putting the files in .skip seems to work, both a build with and without multiterm seem happy.  I'll prepare a proper PR
