### ISSUE TITLE
Project Organizer: Don't collapse directories on reload

### ISSUE THREAD

**Issue by codebrainz** [geany/geany-plugins#415]
The plugin seems to not collapse the directory containing the active document, but it collapses others in the tree view when reloading. It would be cool if it kept all directories that are expanded before the reload, expanded after, provided they still exist.

**Comment by techee** [comment]
Yes, I've been thinking about doing it since I created the plugin. Should be quite easy - just remembering the expanded paths and re-expanding them after reload. Will have a look at it when I have time.
