### ISSUE TITLE
[pair tag highlighter] keyword "font" in a html document

### ISSUE THREAD

**Issue by xuanzon** [geany/geany-plugins#432]
platform: windows 7 x64
geany version: 1.27
issue: every time I delete(from end of string and backspace) the keyword "font" in a html document, geany will crash.

add:
1. the keyword "image" in a html document has same issue.
2. keyword as a tag name

**Comment by b4n** [comment]
I can't seem to be able to reproduce this, neither with the current development version nor with 1.27 release (on Linux, but ti should be fairly the same).  What is the version of geany-plugins used (not Geany itself)?  Could you give exact steps to reproduce?

**Comment by b4n** [comment]
Could you check if #447 fixes this?

**Comment by LarsGit223** [comment]
@xuanzon: any feedback? Did you have time to test the fix?

**Comment by LarsGit223** [comment]
Should we close this? The ticket is 3 years old and there is no feedback to our questions and it was maybe fixed in the meantime. Can anybody reproduce this?

**Comment by elextr** [comment]
Closed no response
