### ISSUE TITLE
[markdown] Refreshing WebKit view doesn't work

### ISSUE THREAD

**Issue by belkka** [geany/geany-plugins#441]
# Error occures when I try to refresh preview.

Look screenshotes:
- [error message](http://i.imgur.com/um6JPwV.png)
- [try refresh to reproduce](http://i.imgur.com/nMV2Shk.png)

Reproducing:
1. [All is right when I edit document](http://i.imgur.com/8Dqcg1x.png)
2. [Lets try to refresh...](http://i.imgur.com/WH4jq73.png)
3. [Error](http://i.imgur.com/hmBqaPQ.png)

Also:
- [It is not any errors or messages in command line](http://i.imgur.com/1y74utE.png)
- My file: /home/ulianich/test.mkd

Sorry for russian interface and my english (I don't know how to change language in geany)

**Comment by frlan** [comment]
Can you provide out of Help->Debug messages or start Geany with debug flag? Which version are you using?

**Comment by belkka** [comment]
I don't know what it is. Some strange error appeared when I distracted
[???](http://i.imgur.com/J196E6F.png)

**Comment by codebrainz** [comment]
The Markdown plugin just feeds formatted strings to WebKit view, it never writes any files to the file system, so Refresh from WebKit's point of view doesn't make much sense here. Markdown [uses `file://.`](https://github.com/geany/geany-plugins/blob/master/markdown/src/viewer.c#L359) for the base URI, it might work somehow if a valid base URI was used, like the real URI of the uncompiled markdown text file or something.

It might also be possible to hook into WebKit's Refresh command and make it just re-update with a formatted string like it normally does. If anyone wants to implement that, I'd review it.

@belkka is your use-case that you've updated the file outside of Geany? If so, maybe you could use <kbd>Ctrl</kbd>+<kbd>R</kbd> to reload the document in Geany (it will be nagging you anyway), this should re-update the WebKit view.

**Comment by belkka** [comment]
I have not updated the file outside. I just tried to use context menu item. Actually I need not to refresh preview in this way.

```
$ geany --version
geany 1.27 (built on 2016-03-13 with GTK 2.24.30, GLib 2.46.2)
```

[geany--verbose.txt](https://github.com/geany/geany-plugins/files/310282/geany--verbose.txt)
When I tried to refresh preview via that context menu new messages did not appear.

**Comment by codebrainz** [comment]
@belkka OK, so maybe if there was a way to get WebKit to hide the Refresh menu item, since in theory it's not needed for this plugin.

**Comment by belkka** [comment]
@codebrainz In my opinion whole menu is not needed for this plugin

**Comment by codebrainz** [comment]
Closing for now, if anyone wants to provide such a patch, please create a pull request.
