### ISSUE TITLE
Project Organizer: Keeps adding more tabs to Project prefs dialog

### ISSUE THREAD

**Issue by codebrainz** [geany/geany-plugins#444]
I thought I had opened an issue about this already but I can't find it. The ProjectOrganizer plugin keeps adding tabs to the Project properties dialog each time it's shown and not removing them when it's closed.

![geany_po_proj_dialog](https://cloud.githubusercontent.com/assets/181177/15993367/777613ee-3098-11e6-9850-3fb3c62de79b.png)

**Comment by codebrainz** [comment]
I think it might be related to [using a tab index](https://github.com/geany/geany-plugins/blob/master/projectorganizer/src/prjorg-main.c#L96-L123) rather than just destroying the tab page or finding it by identity in the notebook and removing it's current index.

**Comment by b4n** [comment]
I don't see this (latest Git of everything, GTK3)

**Comment by codebrainz** [comment]
An alternative way to track/remove the tab, independent of the tab indices, [is used in the code-format plugin](https://github.com/codebrainz/code-format/blob/master/plugin.c#L118-L152).

**Comment by codebrainz** [comment]
It finally overflowed my desktop width:

![geany_po_proj_dialog_overflow](https://cloud.githubusercontent.com/assets/181177/16070382/c1d31b74-3289-11e6-98f3-7e099d610ba6.png)

**Comment by codebrainz** [comment]
> I don't see this (latest Git of everything, GTK3)

It's most likely due to having another plugin also adding Project dialogue tabs, in my case the [Code Format plugin](https://github.com/codebrainz/code-format). It also seems to interact weirdly with the normal Build tab.

**Comment by techee** [comment]
@codebrainz Yep, can reproduce it with the Code Format plugin - will have a look at it.

**Comment by techee** [comment]
Should be fixed by #448
