### ISSUE TITLE
Dangerous use of undo grouping

### ISSUE THREAD

**Issue by b4n** [geany/geany-plugins#455]
GeanyLatex may (at least technically, but I think it's a real bug) start an undo action an never end it.  This could break Geany's whole undoing capability when triggered.

The incriminated code is in `glatex_structure_lvlup()`: an undo action is started unconditionally, but ended conditionally.  That is, if `utils_string_replace_all()` returns 0 replacement for all `GLATEX_STRUCTURE`s, the undo grouping won't be ended.

**Comment by frlan** [comment]
I guess this will fix it, doesn't it?
diff --git a/geanylatex/src/latexstructure.c b/geanylatex/src/latexstructure.c
```
index b06a9d2..f16cd38 100644
--- a/geanylatex/src/latexstructure.c
+++ b/geanylatex/src/latexstructure.c
@@ -94,11 +94,10 @@ void glatex_structure_lvlup(void)
                        haystack = NULL;
                        sci_replace_sel(doc->editor->sci, tmp);
                        g_free(tmp);
-                       sci_end_undo_action(doc->editor->sci);
                        break;
                }
        }
-
+       sci_end_undo_action(doc->editor->sci);
        if (haystack != NULL)
                g_string_free(haystack, TRUE);
 }

```

**Comment by b4n** [comment]
@frlan yes something like that would fix it
