### ISSUE TITLE
Error in "Files Tree" plugin

### ISSUE THREAD

**Issue by artem-check** [geany/geany-plugins#469]
After last update, Geany 1.27

When i push "Create new file", there is no possibility to specify the file name. The file is opened immediately. To enter the file name, it is necessary to rename it.

New file with name "newfile" creates immediately. It is problem.

I have to press a lot of buttons, simply create a new file. It is very hinders the work.

**Comment by codebrainz** [comment]
There's a plugin preference called "open new files", if you uncheck that, it goes straight to allow you to rename the file right away. If the plugin kept the renamed file selected, you could just press enter again to open the file, but it doesn't so you have to re-navigate to open the file.

**Comment by artem-check** [comment]
Thank You!

I offer to set this preference to false by default. It's hard to find, and it's makes troubles.

Thanks!

**Comment by artem-check** [comment]
Every time Geany is loaded, this preference set in TRUE by default. This is problem.

**Comment by artem-check** [comment]
/home/{USER}/.config/geany/plugins/treebrowser/treebrowser.conf 

There is parameter in last line: 
open_new_file=false

Every time Geany is started, this parameters automatically sets to "true". How to fix it?

**Comment by eht16** [comment]
There is a simple typo in the code which causes that a setting with key `open_new_file` is written but `open_new_files` is read.
#473 fixes this.
