### ISSUE TITLE
[git-changebar] change bars not showing with libgit2-0.24.2

### ISSUE THREAD

**Issue by cjmayo** [geany/geany-plugins#493]
Appears to be caused by the commit "Fix repository discovery with ceiling_dirs at current directory"
https://github.com/libgit2/libgit2/commit/a200dc9e1d35d44aabda468966933f34dc7b702e
(I've bisected and then created a reversion patch)

May well be a libgit2 issue but I can only test with git-changebar.

**Comment by intact** [comment]
git_repository_open_ext need path to .git file (file with "gitdir: \<path>") or directory path (and not path to random file).

You can try https://gist.github.com/intact/f7374bb0c6743a9a378659594f09afc9 :)

**Comment by cjmayo** [comment]
That fixes it for me. Thanks!

**Comment by b4n** [comment]
Okay, patch looks sensible, and indeed it seems like I've been lucky it used to work.  @intact would you like to make a proper git-formatted patch with your name and all, or a PR?
