### ISSUE TITLE
Spellchecker - detect "underscore" or "low dash" ( _ ) as word separator

### ISSUE THREAD

**Issue by nkralpy** [geany/geany-plugins#496]
A lot of words are separated using underscore in source codes and other text. Please add that to the list of characters recognized as is_word_sep

static gboolean is_word_sep(gunichar c)
{
	return g_unichar_isspace(c) || g_unichar_ispunct(c);
}

**Comment by eht16** [comment]
#512 has an implementation of the requested feature.
Modifiying `is_word_sep()` doesn't help here, as we need Scintilla to know about the underscore.
For now, it works only for the literal underscore character, I hope this is enough.

**Comment by nkralpy** [comment]
I think that works. Thanks for implementing. :)

**Comment by 12345ieee** [comment]
I (not the issue OP) tested it, too and found #512 works perfectly.
Thank you for implementing this.
