### ISSUE TITLE
geany-plugin-markdown: can save preview into an html?

### ISSUE THREAD

**Issue by eexpress** [geany/geany-plugins#497]
The preview is perfect with multimarkdown and pandoc' markdown file. (some syntax of table different in multimarkdown and pandoc).

If we can use the WebKit preview' menu to save the result into an html file? Even convert into an pdf file with wkhtmltopdf. It seems quite easy to do it.

**Comment by codebrainz** [comment]
I added some code to save the rendered HTML into a file in #502. It's a menu item in the "Tools" menu.
