### ISSUE TITLE
Plugin is offering diff etc on files not placed inside a VCS working copy

### ISSUE THREAD

**Issue by frlan** [geany/geany-plugins#503]
1. Create a file in /tmp
2. Try to do a diff/* for that file

**Comment by nomadbyte** [comment]
Cannot reproduce since [v1.36](../releases/tag/1.36.0).

Likely related to #741 and #970. Fixed in #967 .

**Comment by eht16** [comment]
Cannot reproduce too, closing and assuming it was fixed by the mentioned change.
