### ISSUE TITLE
Wrap Lines In Overview Plugin

### ISSUE THREAD

**Issue by b4n** [geany/geany-plugins#506]
_Moved from geany/geany#1319, originally opened by @483768903474589 on November 23, 2016._

Hi

The lines do not wrap in the Overview plugin when line wrapping is enabled in the editor. Would making the lines wrap in the Overview be possible to implement?

I have the latest version of Geany.

Thanks
Fred

**Comment by codebrainz** [comment]
Duplicate of #321

**Comment by b4n** [comment]
@codebrainz oops, sorry, I didn't check for dupes indeed.

**Comment by 483768903474589** [comment]
Please implement this. Thanks.
