### ISSUE TITLE
[Line Operations] Leave Unique Lines

### ISSUE THREAD

**Issue by Forkest** [geany/geany-plugins#516]
I'm coming from AkelPad and this is what I'm missing. There is a function Remove Unique Lines already and I'm looking for exactly the opposite.

Example use case: insert one list, enter an empty line, insert another list, execute, see the lines unique to each list. The lists should be beforehand deduplicated for it to work correctly, of course.

I'm not sure how to name it better: Leave Unique Lines or Remove Non-Unique Lines.

**Comment by smostertdev** [comment]
Yes, I can see this being useful for finding the intersect of two lists. And I think that this function fits in the scope of this plugin. I will work on this when I get time.

**Comment by smostertdev** [comment]
I would like to clarify exactly what you are thinking. 

Currently "Remove Duplicate Lines, (ordered|sorted)" keeps the *first* occurrence of a repeating line.

The function you are suggesting would remove *all* occurrences of a repeating line?

Example | File | Result
 --- | --- | ---
ex.1 | cat<br>**dog**<br>cat<br>cat<br>cat<br>**tree** | **dog**<br>**tree**
ex.2 | cat<br>**dog**<br>cat<br>tree<br>cat<br>cat<br>tree | **dog**

<sub><sup>* no animals where harmed in the creation of this table</sup></sub>

**Comment by Forkest** [comment]
Glad you're interested in implementing it.

Yes, your understanding and example are correct.
