### ISSUE TITLE
Treebrowser - Create new file - Delete file issue.

### ISSUE THREAD

**Issue by endrigit** [geany/geany-plugins#518]
When creating new file ( if the plug-in setting is 'Open newly created file' ), the file opens immediately without giving the possibility to set a name.

When deleting existing file the Treeview duplicates all the existing files but not physically. It's just the Treeview somehow not refreshing correctly. Very annoying because it's difficult to distinguish which file exists and which not.

**Comment by vfaronov** [comment]
> When deleting existing file the Treeview duplicates all the existing files but not physically. It's just the Treeview somehow not refreshing correctly. Very annoying because it's difficult to distinguish which file exists and which not.

This is addressed by #525, should be fixed in the next release.

**Comment by LarsGit223** [comment]
As #525 is merged, can this be closed?

**Comment by codebrainz** [comment]
Closed by #525, @endrigit feel free to reopen/comment if you  still have the problem.
