### ISSUE TITLE
git-changebar: No diff displayed when first line in document deleted

### ISSUE THREAD

**Issue by techee** [geany/geany-plugins#532]
To reproduce, just delete the first line in a version-controlled document. I believe the reason is that changebar markers of deleted lines are always placed on a previous line and there's no previous line in this case.

This also affects #531 Because in this case it isn't possible to perform undo. Note that if this issue is fixed somehow, the code from #531 has to be updated too because right now it assumes the deleted line's marker is on the previous line.

**Comment by LarsGit223** [comment]
I think this can be closed (but didn't test), see https://github.com/geany/geany-plugins/pull/531#issuecomment-282009984.

**Comment by techee** [comment]
Yep, it works, closing.
