### ISSUE TITLE
[Spellcheck] Interrupt the spellchecker to crash Geany

### ISSUE THREAD

**Issue by 12345ieee** [geany/geany-plugins#547]
How-to:

* Start spell-checking a large document (I used a 4MB file that I can provide, if needed)
* Close said file while the spell-checking is still ongoing
* Geany crashes

Trace:
```
$ geany -v
...
SpellCheck-Message: Checking file "**redacted**" (using "en_US" (myspell)):
Errore di segmentazione
```

**Comment by eht16** [comment]
Oops. Thanks for reporting. Should be fixed in GIT master.

In theory there might be a possibility to crash again but this should be very rare and hard to trigger.

**Comment by 12345ieee** [comment]
I tested it a bit and indeed it seems fixed.

Thanks.
