### ISSUE TITLE
GeniusPaste doesn't work with some of the provided pastebins

### ISSUE THREAD

**Issue by techee** [geany/geany-plugins#548]
The following three of the provided services don't work:

dpaste.de
fpaste.org
tinypaste.com

Maybe some URL has to be adjusted in the configuration or if they don't have any API for this any more, they should be removed.

**Comment by b4n** [comment]
* *dpaste.de* is easy enough, basically needs using HTTPS
* *fpaste.org* trickier, they completely changed API, and the new one requires sending JSON.
* *tinypaste.com* yeah I know, the configuration for that pastebin even has a comment stating that it doesn't work.  I ported it from the pre-configurability era hoping someone would update if it they cared (I wasn't the original author of the plugin and didn't add that pastebin).  Apparently nobody did, so maybe I should just remove it.

Anyway, I have a patch for the 2 first I'll submit soon.

**Comment by b4n** [comment]
Well, here's the branch if anyone want to test early: https://github.com/b4n/geany-plugins/commits/geniuspaste/update-pastebins
I'll re-check and PR it later though.
