### ISSUE TITLE
treebrowser issue: Open externally and Open Terminal don't work on Windows 10

### ISSUE THREAD

**Issue by edwardsayer** [geany/geany-plugins#556]
The treebrowser context menu items "Open externally" and "Open Terminal" don't work on Windows 10.
It doesn't lunch any external application.
However, the "Open Externally" function in built-in plugin Filebrowser is working correctly.

**Comment by xiconet** [comment]
Hi,
Same kind of problem on Windows 7 : invalid argument when trying to open folder with command `explorer %d`

**Comment by SeriesOfUnlikelyExplanations** [comment]
Same thing here (on windows 10). Any update on this one?

**Comment by codebrainz** [comment]
Geany-Plugins package should ship `gspawn-win32-helper.exe` and `gspawn-win32-helper-console.exe` that is needed by GSpawn, which this plugin uses.

As a workaround, one can install the [msys2](https://www.msys2.org/) package `mingw-w64-i686-glib2` and copy the above executables from `C:\msys64\mingw32\bin` or even simpler, from the official builds like [this zip file](https://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.28/glib_2.28.8-1_win32.zip) in the `bin` directory to Geany's `bin` directory found by default at `C:\Program Files (x86)\Geany\bin`.

Probably the best long-term solution is for the plugin to use the `spawn.c` functions like Geany itself does.

**Comment by eht16** [comment]
#973 should fix the issue for TreeBrowser (ported the GSpawn code to our spawn API).

But @codebrainz is still right: there are more plugins using the GSpawn API and probably should be ported at some point. Until then, I think we should distribute the GSpawn helper binaries as well.
