### ISSUE TITLE
Addons: Hightlighting after Double-Click does not work on pasted/fileless content

### ISSUE THREAD

**Issue by RalphBike** [geany/geany-plugins#562]
The Hightlighting after Double-Click (in "addons") seems to require the content to be saved to a file. It does not work on content that has just been typed or pasted in a blank/unsaved tab.

**Comment by eht16** [comment]
Sorry, this got broke in https://github.com/geany/geany-plugins/pull/481.

I noticed this the other day but didn't got to debug it until now.
Thanks for the report and the reminder.

**Comment by RalphBike** [comment]
Has been rolled out via my linux distribution. Works! Thanks guys, great job!

**Comment by elextr** [comment]
Confirmed current Git
