### ISSUE TITLE
Spell check marks words in single quotes as misspelled

### ISSUE THREAD

**Issue by LadyAleena** [geany/geany-plugins#571]
When spell check is on, any word in single quotes is seen as misspelled. If the word is in double quotes it is not. Please see the screen shot.

Thanks for reading,
LA

![geanyspellcheck](https://cloud.githubusercontent.com/assets/123256/25632335/47424582-2f41-11e7-8066-cb5a42007f6a.png)

(Reported [here](https://github.com/geany/geany/issues/1486) first)

**Comment by codebrainz** [comment]
Have you tried latest version?

Related: https://github.com/geany/geany-plugins/issues/320, https://github.com/geany/geany-plugins/pull/322, https://github.com/geany/geany-plugins/issues/484, https://github.com/geany/geany-plugins/pull/487

**Comment by eht16** [comment]
As @codebrainz said, this should be fixed in the latest version.
You don't say which version of Geany you are using. If you are using at least Geany 1.30 and it still happens, please re-open.
Otherwise, just upgrade :).

**Comment by LadyAleena** [comment]
I wish I could get a version about 1.28, but Debian doesn't have 1.30 except for in its experimental release.
