### ISSUE TITLE
Git Changebar not visible

### ISSUE THREAD

**Issue by chrisspen** [geany/geany-plugins#572]
I've enabled the git-changebar plugin, but it seemingly has no effect. I assume I'm misunderstanding something, but the [doc page](https://plugins.geany.org/git-changebar.html) is virtually non-existent, and implies you should immediately see git markers for your git project once the plugin is enabled. Is there a specific process for "activating" the changebar?

I've created a project for my local git repo, and I see tabs for Symbols, Documents, Files, and Tree Browser, but none show any git markers.

**Comment by vfaronov** [comment]
You should see markers when the file you’re editing has uncommitted changes. It looks like this:

![git-changebar](https://cloud.githubusercontent.com/assets/300211/25781141/0fde9004-333e-11e7-803e-23b7a4568a14.png)

You should not be seeing anything special in the sidebar; only in the editor.

**Comment by black-silence** [comment]
Looks like it's broken again.

**Comment by chrisspen** [comment]
It's working for me. I just didn't realize the only thing it added was a narrow color-coded strip next to the line numbers. I thought it color coded the filenames or added icons in the Files/Documents/Tree Browser tabs. Adding a screenshot somewhere in the docs would help clarify this.
