### ISSUE TITLE
Directory diff ignores git setting

### ISSUE THREAD

**Issue by chrisspen** [geany/geany-plugins#573]
The docs state that if you have a visual diff tool installed, like meld, running VC->*->Diff will use that tool. This appears to work for VC->File->Diff, but not for VC->Directory->Diff, which spits out the default diff output.

Thinking that GeanyVC was using `git diff`, I tried overriding the `git diff` with:

    git config --global diff.external meld

but this has no effect, since GeanyVC appears to ignore git's `diff.external` setting, preventing the use of a visual diff tool.

**Comment by eht16** [comment]
FTR: external diff viewer for a directory is simply not implemented. It's only implemented for a file based diff.
Someone need to adapt the code from `vcdiff_file_activated` to `vcdiff_dir_activated`.
