### ISSUE TITLE
Split window does not react to all key presses

### ISSUE THREAD

**Issue by mmlacak** [geany/geany-plugins#577]
In split window "End" and "Home" buttons does not work. 
Also some shortcuts, like "Ctrl-S". Please check if there are
other keys and combinations which does not work properly.

Linux Mint 18.0 with latest patches, Geany 1.27 from repository.

$ geany -V
geany 1.27 (built on 2016-04-17 with GTK 2.24.30, GLib 2.48.0)

$ geany -v 
Geany-INFO: Geany 1.27, en_US.UTF-8
Geany-INFO: GTK 2.24.30, GLib 2.48.2
Geany-INFO: System data dir: /usr/share/geany
Geany-INFO: User config dir: /home/pero/.config/geany
Geany-INFO: System plugin path: /usr/lib/x86_64-linux-gnu/geany
Geany-INFO: Added filetype Scala (61).
Geany-INFO: Added filetype Genie (62).
Geany-INFO: Added filetype CUDA (63).
Geany-INFO: Added filetype Clojure (64).
Geany-INFO: Added filetype Graphviz (65).
Geany-INFO: Added filetype Cython (66).
Geany-INFO: Added filetype JSON (67).
Geany-INFO: Loaded:   /usr/lib/x86_64-linux-gnu/geany/treebrowser.so (TreeBrowser)
Geany-INFO: Loaded:   /usr/lib/x86_64-linux-gnu/geany/splitwindow.so (Split Window)
Geany-INFO: Loaded:   /usr/lib/x86_64-linux-gnu/geany/projectorganizer.so (Project Organizer)
Geany-INFO: Loaded:   /usr/lib/x86_64-linux-gnu/geany/overview.so (Overview)
Geany-INFO: Loaded:   /usr/lib/x86_64-linux-gnu/geany/geanymacro.so (Macros)
Geany-INFO: Loaded:   /usr/lib/x86_64-linux-gnu/geany/filebrowser.so (File Browser)
Geany-INFO: Loaded:   /usr/lib/x86_64-linux-gnu/geany/addons.so (Addons)
Geany-INFO: unknown : None (UTF-8)
Geany-INFO: Loaded /usr/share/geany/python.tags (Python), 5964 symbol(s).

**Comment by elextr** [comment]
This is a known issue.  There have been various proposals in the past to fix it, but none have been accepted yet.

**Comment by mmlacak** [comment]
Maybe then scrap split window, introduce split pane and make another copy of original editor pane?

**Comment by elextr** [comment]
Its not that simple, split window IS another instance of the editing pane.  But a lot of the code that performs the editing and other actions in Geany was written with the assumption that there is only one editor instance.  Thats the major issue.

**Comment by mmlacak** [comment]
Well then, maybe in Geany 2.0.
Anyway, thank you for prompt responses.

**Comment by LadyAleena** [comment]
This is still an issue two years later.
