### ISSUE TITLE
Macros and Numbered Bookmarks plugins crash Geany

### ISSUE THREAD

**Issue by mocallins** [geany/geany-plugins#585]
I've tried using on 2 different PC's Both Windows, 1 is 10 Enterprise and the other 8.1 Pro,  both 64bit.

When I select the "Macros" option in the plugin manager is when it crashes.

**Comment by codebrainz** [comment]
Confirmed on Windows 10 Pro x64 with Geany 1.30 and Windows 7 Professional SP1 x64 Geany 1.30.1.

**Comment by frlan** [comment]
Cannot reproduce. Please provide backtrace

**Comment by discorichardson** [comment]
I think Numbered Bookmarks crashes in the same way on windows.  I think they both create a folder to store settings then crash Geany.

**Comment by codebrainz** [comment]
Confirmed same issue with Numbered Bookmarks with same versions as above.

@discorichardson How do you know they both try and create folders before crashing? Any idea which folders? I hate debugging on Windows on release builds.

**Comment by codebrainz** [comment]
I tested loading/unloading all of the other plugins and these are the only two I found with this problem.

**Comment by eht16** [comment]
I've got a stack trace which reveals it crashes somewhere in GDK, the last relevant frame in the stack is
```
#2  0x66b065ee in plugin_init ()
   from C:\Program Files (x86)\geany\lib\geany\geanymacro.dll
```
which doesn't help much.

I just triggered a full debug build on my machine to get a better stack trace.

**Comment by eht16** [comment]
```
#2  0x66b065ee in plugin_init (data=0x6a3ae8e0 <geany_data>)
    at geanymacro.c:2219
```
which is
```c
k=gdk_keymap_get_entries_for_keyval(NULL,'0'+i,&gdkkmkResults,&iResults);
```
I'll have a look at this at the weekend except anyone is faster.

**Comment by discorichardson** [comment]
It looks like you've narrowed it down enough now.  

In both cases after clicking checkbox to activate the plugin a folder is successfully created, and then Geany crashes.  

The empty folders (on windows 7) are:
C:\Users\[username]\AppData\Roaming\geany\plugins\Geany_Numbered_Bookmarks
C:\Users\[username]\AppData\Roaming\geany\plugins\Geany_Macros

**Comment by codebrainz** [comment]
@eht16 Is it the same function for Numbered Bookmarks?

**Comment by elextr** [comment]
Just FYI, the following message occurs on enabling these plugins on Linux, so I think @eht16 is in the right area.

``` (geany:9266): Gdk-CRITICAL **: gdk_keymap_get_entries_for_keyval: assertion 'GDK_IS_KEYMAP (keymap)' failed ```

**Comment by b4n** [comment]
https://developer.gnome.org/gdk2/stable/gdk2-Keyboard-Handling.html#gdk-keymap-get-entries-for-keyval

> Note that passing `NULL` for `keymap` is deprecated and will stop to work in GTK+ 3.0. Use [`gdk_keymap_get_for_display()`](https://developer.gnome.org/gdk2/stable/gdk2-Keyboard-Handling.html#gdk-keymap-get-for-display) instead.

**Comment by eht16** [comment]
@codebrainz yes, exactly the same issue with Numbered Bookmarks.

@b4n to the rescue. Thanks, that was exactly the error.

Interestingly, on Windows I don't see the warning Lex posted.
But GeanyLua is also affected.

Anyway, it's easy to fix. Will do a PR.

**Comment by codebrainz** [comment]
It sounds more like a GDK bug, it's weird something deprecated should cause a runtime assertion failure, and especially there's no reason it should crash the whole process. Oh well, GTK+ isn't exactly known for stability anymore :)
