### ISSUE TITLE
Review string "translator_credits" 

### ISSUE THREAD

**Issue by frlan** [geany/geany-plugins#587]
Most likely the string doesn't make sense to be transalted

**Comment by b4n** [comment]
@frlan it's from the bundled Devhelp, but yes, usually these strings are meant to be translated, or rather replaced with the credits for that translation: it's a mean to show credit for the currently used translation, maintained directly inside that translation.

**Comment by frlan** [comment]
@b4n I even didn't find a usage of the particular piece of code. Maybe some ancient piece that can be removed anyway.

**Comment by eht16** [comment]
I cannot find the string in the current code, so it was probably removed in the meantime.
Do you agree to close this issue?
