### ISSUE TITLE
CommonMark plugin

### ISSUE THREAD

**Issue by sbrunov** [geany/geany-plugins#589]
Hello, Everyone!

It would be great to have the [CommonMark](http://commonmark.org/) plugin.

The rationale:
>  We propose a standard, unambiguous syntax specification for Markdown, along with a suite of comprehensive tests to validate Markdown implementations against this specification. We believe this is necessary, even essential, for the future of Markdown.
>
> That’s what we call CommonMark.
>
> — [CommonMark](http://commonmark.org/).

Best regards,
Sergey Brunov.

**Comment by elextr** [comment]
The plugins here are all provided by individual contributors.  I'm sure a well written plugin supporting commonmark would be welcome, if somebody wants to provide it.

**Comment by codebrainz** [comment]
@sbrunov what do you mean by "have the CommonMark plugin", specifically?

**Comment by codebrainz** [comment]
See PR #747, closing this issue since that supersedes this.

**Comment by cup** [comment]
https://github.com/geany/geany-plugins/issues/589
https://github.com/geany/geany-plugins/issues/651
https://github.com/geany/geany-plugins/pull/747
