### ISSUE TITLE
debugger plugin crashes geany 1.31 under macOS

### ISSUE THREAD

**Issue by silberzwiebel** [geany/geany-plugins#591]
I identified that the debugger plugin causes geany to not start, or if disabled and the enabled manually from the plugin manager, crashes geany.
[Here is the error message that is shown on the command line (and more information).](https://github.com/geany/geany/issues/1555#issuecomment-318613908)
Thanks for fixing!

**Comment by techee** [comment]
It's actually a problem that has to be fixed in Geany - see

https://github.com/geany/geany/pull/1625

Closing this one.

**Comment by silberzwiebel** [comment]
Many thanks for your in-depth investigation into this problem!
