### ISSUE TITLE
Markdown: Support for backticks

### ISSUE THREAD

**Issue by sej7278** [geany/geany-plugins#592]
I suspect most of us are using geany-plugin-markdown for editing Github content, so could we add support for the Github flavour of Markdown, including things like backticks for code blocks, which I guess would convert to HTML "pre" tags?

https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by codebrainz** [comment]
If/when it gets added to [Discount](http://www.pell.portland.or.us/~orc/Code/discount/) or [PEG-Markdown](https://github.com/jgm/peg-markdown), which the Markdown plugin uses, it will be possible supported.

**Comment by codebrainz** [comment]
I have added PR #747 to support CommonMark, anything beyond that should first be added there and it will trickle down to this plugin eventually.
