### ISSUE TITLE
Travis fails, needs updating to C++11

### ISSUE THREAD

**Issue by elextr** [geany/geany-plugins#596]
Geany now needs a C++11 compiler due to Scintilla 3.7.5 and therefore so does Geany Plugins since it uses the Geany compilation options, but Travis uses an old compiler so it fails.  For info see https://github.com/geany/geany/pull/1503.

**Comment by LarsGit223** [comment]
I think this can be closed, see https://github.com/geany/geany-plugins/pull/597#issuecomment-322063066.
