### ISSUE TITLE
[Split Window] Search is broken

### ISSUE THREAD

**Issue by nextl00p** [geany/geany-plugins#602]
It appears to only search the left window.
Using Geany 1.31

**Comment by elextr** [comment]
Split window is intended to be a display only window, no editing operations including search are intended to work.  A few simple editing operations do in fact work, but most do not.

There is no simple solution to the issue, many editing operations in Geany are written on the assumption of a single editing window, as that is the design of base Geany.  A plugin like split window adding a new window is not going to change the base implementation.  

An alternative implementation that effectively swapped the base window to the split window fixed most of the missing functionality but was reported to be unacceptably slow on GTK3 so the developer has not been willing to release it.

Alternative solutions are welcome.

**Comment by codebrainz** [comment]
Split window plugin is not part of this project, it's distributed with [Geany itself](https://github.com/geany/geany). Feel free to re-submit this bug there, but you'll likely find many existing reports like "[feature] is broken in split window" already.
