### ISSUE TITLE
ProjectOrganizer doesn't follow symlinks

### ISSUE THREAD

**Issue by samysadi** [geany/geany-plugins#603]
Hello,

It seems like the projectorganizer plugin isn't following symlinks for providing completion.

Can you have a look at this issue?

**Comment by Ruud68** [comment]
Hi, I am using symlinks to include a large library (Joomla).
I can add the symlinked directory to the project as external directory
Both code completion and crtl-clicking on a method in that symlinked library works just fine.
So I cannot reproduce your issue.

**Comment by samysadi** [comment]
Hello,
Yes, the issue seems not to be related to geany. I tested on another environment and it works just fine as you said.
So, I close the issue.
