### ISSUE TITLE
Workbench: open file handles not closed on directory scanning

### ISSUE THREAD

**Issue by eht16** [geany/geany-plugins#607]
@LarsGit223 the Workbench has the same bug as fixed for ProjectOrganizer in #605 (it looks like some of the ProjectOrganizer code was copied).

Interestingly, the change in 99dcc2344ebf23d40d5426035d0ae950b197cf14 is already in the Workbench plugin but the main change needs to be done here as well.

**Comment by LarsGit223** [comment]
Thanks for the notification. If I remember right the already fixed part was found by the guys during the code review. And yes, huge code parts are copied and modified from the ProjectOrganizer plugin. Basically everything regarding directory/file scanning.
