### ISSUE TITLE
create/rename/delete file in File Browser sidebar

### ISSUE THREAD

**Issue by medovina** [geany/geany-plugins#621]
I think it would be really nice if I could use the context menu in the File Browser sidebar to

- create an empty file
- rename a file
- delete a file (with confirmation)

I might be willing to work on implementing this.  Would you accept a patch with this functionality?

**Comment by elextr** [comment]
Try the treebrowser plugin from geany-plugins.

**Comment by medovina** [comment]
Aha - OK, I just tried it.  This functionality already exists there, so I will close this issue.  Thanks!
