### ISSUE TITLE
Addons: mark all not working

### ISSUE THREAD

**Issue by elextr** [geany/geany-plugins#638]
@eht16 When enabled "Mark all occurances of a word when double clicking it" no longer works.  (Fairly recent Git Geany and G-P GTK-3).  There have been various discussions and pull requests around the operation of finds mark all functionality IIRC, did something there break addons?

**Comment by codebrainz** [comment]
It doesn't work here with 1.32 (git >= 44f96d0) upon a quick test, unless I'm doing something wrong.

**Comment by elextr** [comment]
Further info, it works if Geany is started with Addons enabled, but doesn't work if Addons is enabled after Geany starts, and stops working when Addons is disabled and re-enabled.  

Disabling and re-enabling the preference seems to work ok if it was working, but won't start it working if it wasn't.

**Comment by eht16** [comment]
Uhhhh, this got broken more than a year ago in https://github.com/geany/geany-plugins/commit/26e6906ed5eeab0adf5c7ad0ea177f99a3e49ea5.

Good catch, thanks!
#639 should fix it, testing is welcome.
