### ISSUE TITLE
Travis fails randomly

### ISSUE THREAD

**Issue by b4n** [geany/geany-plugins#650]
For some reason I don't yet know, Travis fails fairly randomly building GP: I seen problems with `dh-marshal` (possibly due to out-of-tree build?  but why is it random?) and now with WebHelper's enums (there doesn't seem to be an error but the enum types are missing (although they are present in Git).

**Comment by b4n** [comment]
…and now it fails at _apt_ time: https://travis-ci.org/geany/geany-plugins/jobs/309394522

**Comment by LarsGit223** [comment]
Yes, starting dbus seems to be the start of all problems:
```
Setting up dbus (1.6.18-0ubuntu4.5) ...
runlevel:/var/run/utmp: No such file or directory
start: Job failed to start
invoke-rc.d: initscript dbus, action "start" failed.
dpkg: error processing package dbus (--configure):
```
I searched for ```runlevel:/var/run/utmp: No such file or directory``` but did not find anything meaningful yet.

**Comment by codebrainz** [comment]
At least the `runlevel` part was there before:

https://travis-ci.org/geany/geany-plugins/jobs/306153614#L1085

So I guess just need to figure out why DBus fails to start (and/or _why_ DBus is even being installed/started).

**Comment by b4n** [comment]
>At least the `runlevel` part was there before:
>
>https://travis-ci.org/geany/geany-plugins/jobs/306153614#L1085

Hum, interesting… maybe they added a `set -e` or alike in a new version, very possible as I think I remember Debian did that for startup scripts.

>  (and/or _why_ DBus is even being installed/started).

Because of GConf2, which we need for devhelp.  Fairly enough, we don't need this for GTK3 builds as devhelp is GTK2-only. But oddly enough we install the same thing on both builds, and everything seems to be the same but one fails and the other doesn't… I really don't understand anything about this issue yet.

**Comment by b4n** [comment]
I guess this is old enough that it doesn't matter, and I don't know of any current similar failure, so I'm gonna close this.  Please reopen if it makes sense.
