### ISSUE TITLE
Markdown: please add support to WebKitGTK+ 2.18+ 

### ISSUE THREAD

**Issue by sergiomb2** [geany/geany-plugins#655]
WebKitGTK+ 2.18+ use WebKit2 API [1]
WebKit1 API is deprecated and was removed from Fedora 27 , the main argument is that WebKit1 have many security issues that wasn't fixed and also won't be fixed . 

Thanks

**Comment by elextr** [comment]
As you note, the API is different and somebodys got to convert it, pull requests are welcome.

**Comment by codebrainz** [comment]
> the main argument is that WebKit1 have many security issues that wasn't fixed and also won't be fixed

Seeing as the Markdown preview isn't a general purpose browser but meant only to display local dynamically-generated text from memory (although in theory it can display remote Internet content), I don't see this as such a big deal.

**Comment by sergiomb2** [comment]
https://github.com/geany/geany-plugins/pull/656

**Comment by codebrainz** [comment]
Fixed in 4039a13882f4b9e2127f6e7b018bdbdffe36e2a2
