### ISSUE TITLE
Feature suggestion: Color picker/translator

### ISSUE THREAD

**Issue by LarsGit223** [geany/geany-plugins#663]
This issue is copied from the original feature request by @BarbzYHOOL geany, see https://github.com/geany/geany/issues/1669:

When you write CSS, html or maybe other markup languages, you often need to type colors. A very nice feature would be to have the same thing we got in modern browsers (like firefox) when you inspect an element :

    next to the RGB/RGBA color code there is a big dot representing the color (very useful)
    if you click on it, you have a color picker to change it and it changes the color code accordingly

Actually we are forced to open a color picker just to see what is the color code, so I open Gimp which is heavy and it's quite unpractical

Thank you :)

**Comment by elextr** [comment]
@LarsGit223 was there a point to simply copying the linked feature request?

**Comment by LarsGit223** [comment]
I copied the text to show the original feature request "on hand" and added the link to give access to the original full discussion. Nothing more. Or what do you mean?

**Comment by elextr** [comment]
Its just that you didn't need to copy to Geany-Plugins unless you had something to add to it, its just as likely to be found in Geany as in G-P :smile:

**Comment by LarsGit223** [comment]
Yeah, well but from reading the discussion it sounded like it is more likely to be implemented in G-P....and I will post a PR for it in Addons in a minute   :grimacing:

**Comment by elextr** [comment]
Oh well, ok, its not a problem, just not necessary :)

**Comment by LarsGit223** [comment]
This is released in geany-plugins 1.33 and can be closed.
