### ISSUE TITLE
gdb crashes scope plugin

### ISSUE THREAD

**Issue by J-Dunn** [geany/geany-plugins#665]
I tried to use the scope plugin on a trivial hello world. As soon as I start debugging an error box opens but fails to draw itself so I don't know what the error msg says. 

From that point NOTHING updates on the geany display. If I change desktop and come back the whole geany screen is blank, grey nothingness.

I can change tabs in the code editor but the window content does not display. I just see the tab it self change to show which is active. 

I selected the executable from 'setup progam' and set a breakpoint on main.c:3 

When I use Debugger | Run it all locks up. ;(

Source       : geany-1.32-1.fc26.src.rpm
Source       : geany-plugins-1.32-1.fc26.src.rpm

void main () {
  #include <stdio.h>
  printf ("%s","hello world.\n\r");
  return;
}

The example runs as expected from the command line. 

Does this plugin still work?

**Comment by elextr** [comment]
May be https://github.com/geany/geany/pull/1461

**Comment by J-Dunn** [comment]
indeed. fixed, many thanks.
