### ISSUE TITLE
checking for GEANY... no

### ISSUE THREAD

**Issue by J-Dunn** [geany/geany-plugins#666]
I have build and installed geany-master with the G_IO bug workaround. It is installed and running. 
```

# which geany
/usr/local/bin/geany

```

but when I try to build the plugins package from master it fails to find geany. 
```

./autogen.sh

......
checking for GEANY... no
configure: error: Package requirements (geany >= 1.29) were not met:

```
Package 'geany', required by 'virtual:world', not found

What's that about? Have I missed a step ?

thx

**Comment by elextr** [comment]
You have to specify `--with-geany-libs=` to configure/autogen.sh to specify which Geany to build against.

**Comment by J-Dunn** [comment]
thanks for the quick reply. I tried the following and it still can't find it.

./autogen.sh  --with-geany-libs=/usr/local/lib/geany

anyway, isn't this the point of pkgconfig mechanism to provide this sort of thing automatically? Do I need to run some pkgconfig utility or reboot , windows style?

**Comment by elextr** [comment]
The `--with-geany-libs=` needs to be the directory containing libgeany.so*, probably `/usr/local/lib` in your case.

**Comment by J-Dunn** [comment]
Indeed:
```
 ls  /usr/local/lib/
geany  libgeany.la  libgeany.so  libgeany.so.0  libgeany.so.0.0.0  pkgconfig

 ./autogen.sh  --with-geany-libs=/usr/local/lib/
.....
checking for GEANY... no
configure: error: Package requirements (geany >= 1.29) were not met:

```

grr.

**Comment by J-Dunn** [comment]
I worked around that one by installing --prefix=/usr   

now it gets through autogen but barfson VTE. 

```
./configure  --disable-all-plugins --enable-debugger --enable-scope
...
checking for VTE... no
configure: error: Package requirements (vte >= 0.24) were not met:

```


vte is installed at version 0.28 :(

Not going too smoothly today.

**Comment by J-Dunn** [comment]
OK , I fixed most of the anomalies by taking it from the top with make clean and a little manual clean up. 

debugging and scope to not seem to be included is "all-plugins", the reason it worked was because it was not building them. If I add them , I get the VTE problem again. The vte lib is in /usr/lib64 but that does not help:
```

export VTE_LIBS=/usr/lib64;./configure --prefix=/usr --enable-scope --enable-debugger
.....
checking for VTE... no
```

**Comment by elextr** [comment]
>  ./autogen.sh  --with-geany-libs=/usr/local/lib/

Oops sorry, `--with-geany-libdir=`

**Comment by J-Dunn** [comment]
thanks for the additional correction, however I did get around that one by using --prefix=/usr which puts it in /usr/lib64 on fedora 64. 

My persistent blocking issue is with VTE which seems to be a dep for debugger and scope but is not being detected. There does not seem to be an equivalent configure option for that.

Any suggestions?

**Comment by b4n** [comment]
Are the development files for VTE **< 2.9x** installed on your system?
You can see whether `pkg-config --modversion vte` gives you the version of the *vte* module, or if it can't find it, in which case you'll probably have to install it (libvte-devel or something)

**Comment by J-Dunn** [comment]
many thanks b4n for pointing out what I was missing. Sometimes errors msgs are more misleading than helpful.

I have now managed to install both the G_IO patched geany and geany-plugins.  Scope no longer locks up which is a great improvement. Not sure it's actually working but that's another story. 

Thanks to all for the help.

**Comment by neurotok** [comment]
sudo apt install libvte-dev and then run the ./configure
