### ISSUE TITLE
Unable to Capture Filter Input with geanyminiscript

### ISSUE THREAD

**Issue by doakey3** [geany/geany-plugins#692]
I am trying to use the addon "geanyminiscript" to edit selected text.

It's simple enough to run the addon, but I can't find any examples for how to get the filter input in my script. For example, in the dialog box, I can select "selection" as the filter input. How do I access this text from within my script? It would be nice to see some examples.

![screenshot](https://user-images.githubusercontent.com/16495887/36285583-5ef6dc72-1269-11e8-8797-80e671c5fbc6.png)

**Comment by elextr** [comment]
IIUC your script must be a filter, that is it reads its input from standard input and writes its results to standard output.

**Comment by doakey3** [comment]
I see. So for example, in python I might do:

```python
import sys
text = sys.stdin.read()

# text processing here

print(text)
```

Do you know if there is any way to link keyboard shortcuts to run specific scripts with mini-script? I would use [peasy](https://github.com/kugel-/peasy), but I can't seem to install it on my system.

**Comment by elextr** [comment]
> Do you know if there is any way to link keyboard shortcuts to run specific scripts with mini-script?

Doesn't appear to be.

For Peasy, post an issue on its github including your Geany version.

**Comment by codebrainz** [comment]
You could also use GeanyPy, which is part of this project, and is available in a number of distros' package managers.

**Comment by doakey3** [comment]
GeanyPy was what I used for a long time and it worked very well until Geany 1.32 when Arch Linux started using GTK 3 instead of 2.

I learned that custom python scripts can be used to process selected text by using `Edit > Format > Send Selection To > Set Custom Commands` This works very well for my purposes since these can be linked to a keyboard shortcut.
