### ISSUE TITLE
custom color scheme for geany

### ISSUE THREAD

**Issue by saiballo** [geany/geany-plugins#736]
Until version 1.32 I used a custom color scheme for interface. I run Geany with this command:

bash -c 'GTK2_RC_FILES=~/.config/geany/my_theme geany %F'

with 1.33 version this launcher does not work... any suggestion?

thank you

**Comment by elextr** [comment]
what OS? what version of GTK (near top of `help->debug messages`)

**Comment by saiballo** [comment]
Ubuntu 16.04

----------------------------
saibal android

Il gio 19 apr 2018, 10:54 elextr <notifications@github.com> ha scritto:

**Comment by elextr** [comment]
Please answer the second part of the question.  

It is likely that the distro has released version 1.33 of Geany as GTK3 so your GTK2 rc will not work.

**Comment by elextr** [comment]
Also please note you have posted this question to the geany-plugins issues, not to the Geany issues.

**Comment by saiballo** [comment]
I'm sorry for mistakes.

These are the infos:


10:49:22: Geany INFO		: Geany 1.33, it_IT.UTF-8
10:49:22: Geany INFO		: GTK 3.18.9, GLib 2.48.2

**Comment by codebrainz** [comment]
See https://github.com/geany/geany/issues/1833
