### ISSUE TITLE
Ctags problems with spaces in project name

### ISSUE THREAD

**Issue by v1993** [geany/geany-plugins#738]
find -L . -not -path '*/\.*' | ctags --totals --fields=fKsSt --extra=-fq --c-kinds=+p --sort=foldcase --excmd=number -L - -f /home/v/compile/2048 NG/2048 NG.tags (в каталоге: /home/v/compile/2048 NG/)
    ctags: Warning: cannot open source file "NG/2048" : No such file or directory
    ctags: Warning: cannot open source file "NG.tags" : No such file or directory
    ctags: Warning: ignoring null tag in ./cocos2d/templates/js-template-default/res/loading.js
    ctags: Warning: ignoring null tag in ./cocos2d/tests/js-tests/src/Presentation/Presentation.js
    ctags: Warning: ignoring null tag in ./cocos2d/web/template/res/loading.js
    ctags: Warning: ignoring null tag in ./cocos2d/web/CCBoot.js
    ctags: Warning: ignoring null tag in ./cocos2d/web/cocos2d/labels/CCLabelAtlasCanvasRenderCmd.js
    ctags: Warning: ignoring null tag in ./cocos2d/web/cocos2d/core/utils/BinaryLoader.js
    ctags: Warning: ignoring null tag in ./cocos2d/cocos/scripting/js-bindings/script/ccui/jsb_ccui_deprecated.js
    ctags: Warning: ignoring null tag in ./cocos2d/cocos/scripting/js-bindings/script/debugger/actors/webconsole.js
    ctags: Warning: ignoring null tag in ./cocos2d/cocos/scripting/js-bindings/script/jsb_boot.js
    ctags: Warning: ignoring null tag in ./cocos2d
So we have to single-quote `/home/v/compile/2048 NG/2048 NG.tags`.

**Comment by v1993** [comment]
Interesting… I launched correct version manually and discovered a bug in ctags!

    find -L . -not -path '*/\.*' | ctags --totals --fields=fKsSt --extra=-fq --c-kinds=+p --sort=foldcase --excmd=number -L - -f '/home/v/compile/2048 NG/2048 NG.tags'
    ctags: Warning: ignoring null tag in ./cocos2d/templates/js-template-default/res/loading.js
    ctags: Warning: ignoring null tag in ./cocos2d/tests/js-tests/src/Presentation/Presentation.js
    ctags: Warning: ignoring null tag in ./cocos2d/web/template/res/loading.js
    ctags: Warning: ignoring null tag in ./cocos2d/web/CCBoot.js
    ctags: Warning: ignoring null tag in ./cocos2d/web/cocos2d/labels/CCLabelAtlasCanvasRenderCmd.js
    ctags: Warning: ignoring null tag in ./cocos2d/web/cocos2d/core/utils/BinaryLoader.js
    ctags: Warning: ignoring null tag in ./cocos2d/cocos/scripting/js-bindings/script/ccui/jsb_ccui_deprecated.js
    ctags: Warning: ignoring null tag in ./cocos2d/cocos/scripting/js-bindings/script/debugger/actors/webconsole.js
    ctags: Warning: ignoring null tag in ./cocos2d/cocos/scripting/js-bindings/script/jsb_boot.js
    ctags: Warning: ignoring null tag in ./cocos2d/cocos/scripting/js-bindings/script/jsb_deprecated.js
    sort: cannot read: NG/2048: No such file or directory
    ctags: cannot sort tag file : No such file or directory

**Comment by elextr** [comment]
Why are you posting ctags problems on `geany/plugins`?

**Comment by v1993** [comment]
It is from geany's messages window, command is auto generated by `Project -> Generate tags`.

P.S.: geany side bug can be fixed, and new ctags is in development: https://github.com/universal-ctags/ctags.

**Comment by elextr** [comment]
and finally which plugin are you using?

**Comment by v1993** [comment]
It is `GeanyCTags`. I'm sorry for being so inaccurate!

**Comment by techee** [comment]
@v1993 Thanks for reporting the issue. I've added apostrophes around the generated tags file in #739 which should fix the issue in the plugin. Interestingly, I haven't been able to reproduce the problem itself here - even without the apostrophes tag generation worked fine with a project name containing spaces. But adding apostrophes around the name is definitely the right thing to do.

**Comment by techee** [comment]
This is hopefully fixed. Closing.
