### ISSUE TITLE
[markdown] Debian/Ubuntu Package issue

### ISSUE THREAD

**Issue by al-info** [geany/geany-plugins#743]
Hi,

It seems that i'm not in the good place to speak about distro specific issues... But if someone could just tell me where I should post ?

I'm using the markdown plugin daily for 2 years now (on GNU/Linux debian OS), and I'm very satisfied with it. At begining I just did "apt-get install geany-plugin-markdown" and it just worked. But since a few months ago I had to use a self-compiled version to make it work.

In debian sid package is geany-plugin-markdown is only 1.29 and not compatible with geany-plugins-common 1.33, and in Ubuntu 18.04 the package geany-plugin-markdown has been removed.

What's going on ?

**Comment by codebrainz** [comment]
They probably started building Geany and Geany-Plugins package against GTK+3 or else removed the version of WebkitGTK that the plugin uses.

**Comment by hyperair** [comment]
^ Both of the above happened.

**Comment by al-info** [comment]
Ok, thanks for the explanation. Does it means that plugin-markdown has become obselete and won't be maintained on the long-term ?

**Comment by codebrainz** [comment]
@al-info not really, the above linked #677 pull request is to fix it, it's just waiting for review from the other plugin developer or to be split off into a separated pull request.

**Comment by al-info** [comment]
:) glad to read that. Thanks again for this soft. I'll follow #677.
