### ISSUE TITLE
Geanyprj's Project dock is extremely small

### ISSUE THREAD

**Issue by YeldhamDev** [geany/geany-plugins#744]
![screenshot1](https://user-images.githubusercontent.com/30739239/39947903-22a65f44-5563-11e8-9121-bd9f7790e3bc.png)

**Comment by elextr** [comment]
Think its the Geanyprj sidebar tab.

**Comment by codebrainz** [comment]
Maybe [here](https://github.com/geany/geany-plugins/blob/1.33.0/geanyprj/src/sidebar.c#L452) needs to be replaced with:

```c
gtk_box_pack_start(GTK_BOX(file_view_vbox), scrollwin, TRUE, TRUE, 0);
```

**Comment by YeldhamDev** [comment]
Apologies, here's a better screenshot:
![screenshot1](https://user-images.githubusercontent.com/30739239/39954249-ccbf7a22-55ab-11e8-8469-01819f23f4e2.png)

**Comment by LarsGit223** [comment]
@codebrainz: yes, your suggested change fixes the issue. Posted a PR.
