### ISSUE TITLE
GeanyPy plugin missing dependency

### ISSUE THREAD

**Issue by detjensrobert** [geany/geany-plugins#745]
GeanyPy crashes on enable due to a missing dependency on `python-gtk2`.

Installing `python-gtk2` fixed the crash.

**Comment by elextr** [comment]
Yes, from Geanypy readme:

```
Dependencies
------------

To build GeanyPy you need the following dependencies:

* Python 2.6 or 2.7 and development files.
```

**Comment by codebrainz** [comment]
What is `python-gtk2`? It looks like the name of a Debian package?

- What was the error message when it crashed? (should show in Help->Debug messages)
- Where did you install GeanyPy from (ie. from source, distro repository, Windows installer)?
- What operating system are you using?
- What version of Geany?
- What version of GeanyPy?

The plugin itself definitively [depends on PyGTK+](https://github.com/geany/geany-plugins/blob/1.33.0/build/geanypy.m4#L5).

**Comment by detjensrobert** [comment]
D'oh.
Should included that info. Sorry.

OS: Ubuntu 16.04
Geany 1.27
geanypy installed through the repository / `geany-plugin-py` package

There was no error message generated that I saw, nothing was outputted to Debug Messages. I'm guessing it crashed before it outputted anything.
Running Geany from the command line outputted "Segmentation Fault" to the terminal when it crashed.

**Comment by elextr** [comment]
@detjensrobert ahh right, that package seems to be missing the dependency on pygtk, which presumably is the package you installed.  Geany devs don't make the packages, they are made by a friendly Ubuntu packager.  I doubt it will be fixed since Geany is now at version 1.33 and Ubuntu LTS 16.04 was recently replaced by 18.04 LTS.  You could check a newer Geany from the PPA https://launchpad.net/~geany-dev/+archive/ubuntu/ppa

**Comment by codebrainz** [comment]
Running `geany -v` from the command line, I'd expect some kind of output, most likely a Python `ImportError` or whatever.

It might be the same as [this bug](https://bugs.launchpad.net/ubuntu/+source/geany/+bug/1728348).

**Comment by detjensrobert** [comment]
Might be. Whatever the problem was, installing that gtk package solved it, so I'm good now.

**Comment by codebrainz** [comment]
Closing since we don't support the Ubuntu packages here.

@detjensrobert thanks for reporting, hopefully it will help anyone else who encounters this package bug.
