### ISSUE TITLE
Version check on macOS fails for 1.33

### ISSUE THREAD

**Issue by jrittenh** [geany/geany-plugins#752]
On startup, in Status window:

    Unable to perform version check.
    Error code: 6
    Error message: Unacceptable TLS certificate

Pretty sure it happened with earlier versions, definitely didn't work on 1.32 as I didn't get notified of 1.33, but definitely happens on startup for 1.33.

**Comment by techee** [comment]
Yep, can reproduce it here too. I don't think there's any problem with the code but rather with the bundled libraries enabling encryption and TLS. I suspect they are probably outdated and don't support some encryption modes. Every release I build Geany agains the latest version from the gtk-osx project so if it gets updated there, the problem should be fixed for Geany too.

**Comment by frlan** [comment]
I'm closing this one in favor of #761 -- no need to keep it open twice.
