### ISSUE TITLE
Debugger support for Geany 1.33

### ISSUE THREAD

**Issue by perezh** [geany/geany-plugins#753]
Hi all,
I noticed that I cannot use the scope plugin in 1.33. Is there any plans to provide any support for debugging with geany? I've read the forum and it seems to have a problem with glib, but I don't know if developers are working on it or if the plugin/gdb support is simply abandoned.

Thanks.

**Comment by LarsGit223** [comment]
Yes, there is a problem with the scope plugin in 1.33. But a PR to fix this has already been merged and will be included in the next geany release (if no problems pop up), see PR #1461.

Until then you could also use the debugger plugin.

**Comment by LarsGit223** [comment]
If you build the current master of geany and geany-plugins from source, then the scope plugin should be available. But only for GTK2.

**Comment by perezh** [comment]
Thanks for your quick reply. I'll give a try.
Regards!
