### ISSUE TITLE
debugger

### ISSUE THREAD

**Issue by A7medFCIH** [geany/geany-plugins#758]
there is no debugger plugin

**Comment by LarsGit223** [comment]
What do you mean?

Please describe your issue in more detail. Also, please mention what gtk and glib versions you are using and which operating system. Thanks.

**Comment by A7medFCIH** [comment]
yes, GTK 3.22.30, GLib 2.56.1
so please make it available as fast as possible.

**Comment by LarsGit223** [comment]
It is work in progress, please see #645. So it will hopefully be included in the next release.
If you need it now you could try to build geany plugins yourself (from repository pmjobin:debugger_gtk3)

**Comment by codebrainz** [comment]
Related to #756

**Comment by bxgaillard** [comment]
This is a PR waiting to be approved/merged regarding this issue: #791.
You can use that if you need the plugin.

**Comment by LarsGit223** [comment]
A little update: the scope debugger plugin is included in Geany-Plugins 1.35 (GTK2 & 3). The debugger plugin for GTK2 & 3 is included in the current master branch (so it will be in the next release 1.36 of Geany-Plugins).

**Comment by LarsGit223** [comment]
I close this now as the debugger plugin with GTK2 & 3 support was just released in Geany-Plugins 1.36.

**Comment by Nefor111** [comment]
> I close this now as the debugger plugin with GTK2 & 3 support was just released in Geany-Plugins 1.36.
 Geany 1.36.Arch linux - no debugger found,no plugin to choice.No compiled file in directory.VIA Pacman
 Geany 1.36.Debian 10 Buster -  no debugger found,no plugin to choice.No compiled file in directory. Builded from sources.
 Geany 1.36 Xubuntu 19.04 - no debugger found,no plugin to choice.No compiled file in directory. Builded from sources.

Issue not solved.

**Comment by manastalukdar** [comment]
Debugger plugin also not available on Windows 10 with Geany 1.36.

**Comment by elextr** [comment]
WFM, Linux Mint 19.1 == Ubuntu 18.04 LTS IIRC. Geany 1.37 (git >= 82590af4), en_AU.UTF-8 GTK 3.22.30, GLib 2.56.4 and Geany-plugins at https://github.com/geany/geany-plugins/commit/c156641259643ef4e32d067dd0b346e558a1a973.

@Nefor111 we are not responsible for the Arch packaging, ask there.  For the self builds, you need the appropriate _development_ package of VTE, and specifically 2.91 for GTK3.

@manastalukdar as noted above debugger needs VTE and that library is not available on windows AFAIK.
