### ISSUE TITLE
undo does not work in second window of split window

### ISSUE THREAD

**Issue by Yechoh** [geany/geany-plugins#770]
When using the split window plugin, when typing in the second window, pressing Ctrl-Z will undo in the original window instead of the selected second window.

**Comment by elextr** [comment]
Split window is a core plugin, its in the Geany repository, not the plugins repository.  

But please note there are already many "split window does not work like a full second pane" so this would likely just be a duplicate.

**Comment by codebrainz** [comment]
For example geany/geany#988, among many, many others. Closing as duplicate.
