### ISSUE TITLE
markdown: in html, generated TOC, the links are dead

### ISSUE THREAD

**Issue by VictorelPetrovich** [geany/geany-plugins#771]
I installed geany-plugins, and activated mardown plugin.
When I create an `.md` doc like this: 
```
# Test of TOC

**Contents**

1. [Introduction](#Introduction)
2. [Installation](#Installation)


# Introduction


asd;lfk asdklf ja;sldkfj a;ldfk j

(a full page like this) 


# Installation

asd;lfk asdklf ja;sldkfj a;ldfk j

(a full page like this) 

```

Then, in the side pane with Mardown Preview, the links in the table of contents do not work. 
(In my tests ,there were many pages of text in each section, to make sure it would navigate down if  the links in TOC work to work)
If I generate the `html` with `menu/tools/Export Markdown as Html...`, I get this: ( I did not change the template or any of the settings for Markdown plugin)

``` html
<html>
  <head>
    <style type="text/css">
      body {
        font-family: Serif;
        font-size: 12pt;
        background-color: #ffffff;
        color: #000000;
      }
      code {
        font-family: Mono;
        font-size: 12pt;
      }
    </style>
  </head>
  <body>
    <h1>Test of TOC</h1>

<p><strong>Contents</strong></p>

<ol>
<li><a href="#Introduction">Introduction</a></li>
<li><a href="#Installation">Installation</a></li>
</ol>

<h1>Introduction</h1>

<p>asd;lfk asdklf ja;sldkfj a;ldfk j</p>

<p>(a full page like this)</p>


<h1>Installation</h1>

<p>asd;lfk asdklf ja;sldkfj a;ldfk j</p>

<p>(a full page like this)</p>

  </body>
</html>
```
When I open this in a browser (Chrome), the links in TOC don't work either.
If I edit the html so that to have a
```html
<a name="Introduction"></a>
```
besides 
```html
<h1>Installation</h1>
```
then the links work, as expected.

So: is it a problem with my installation, or ...?

It's on Windows 7; I installed the plugins from https://plugins.geany.org/downloads.html
```
19:22:24: Geany INFO		: GTK 2.24.32, GLib 2.54.3
19:22:24: Geany INFO		: System data dir: C:\Program Files\Geany\data
19:22:24: Geany INFO		: User config dir: C:\Users\Admin\AppData\Roaming\geany
19:22:25: Geany INFO		: System plugin path: C:\Program Files\Geany\lib\geany
```

**Comment by VictorelPetrovich** [comment]
I did not mean to criticize. 
Now I see why I was under the (false?) impression that headings should be made anchor targets in the use case above:
I had downloaded textadept editor, and in it's doc [files](https://foicica.com/hg/textadept/file/b048357bd1be/doc) , after download of textadept, there was not only `manual.md` but also `manual.html` (exactly same as the online  [one](https://foicica.com/textadept/manual.html) )
That is where I found that style of TOC and references to headings, while the `manual.html` had correct anchors besides the referenced headings.
I don't know precisely how Textadept's author did the conversion .md->.html (I think [discount](http://www.pell.portland.or.us/~orc/Code/discount/).

> I don't believe either the original or CommonMark specs say anything about making headings as anchor targets.

You are right,  neither of them specify that.

The original author of Markdown, to make this 
 page  https://daringfireball.net/projects/markdown/syntax with TOC, had simply used inline html inside the `.md` filr 
 https://daringfireball.net/projects/markdown/syntax.text, like this:
```
*   [Overview](#overview)
...
<h2 id="overview">Overview</h2>
```

While the authors of https://spec.commonmark.org/0.28/ used [this](https://github.com/commonmark/CommonMark/blob/master/spec.txt) `.md` source , which skips the "Contents" part entirely: I guess they used a separate tool to get the TOC in the final html.

However: I still think it would be useful (as even the example pages of specifications above illustrate) to have some kind of automatic support for making a TOC. 
What do you think?

> Are you sure you're not using some non-standard extension from some other Markdown renderer?

Like I wrote above, I'm just using what geany and geany-plugins came with. I have no idea where to get a "non-standard extension from some other Markdown renderer ". Why do you ask?

**Comment by codebrainz** [comment]
> I don't know precisely how Textadept's author did the conversion .md->.html

It looks like a [custom lua script](https://foicica.com/hg/textadept/file/b048357bd1be/doc/markdowndoc.lua) which uses Discount. Maybe it generates the TOC in there?

>  I still think it would be useful (as even the example pages of specifications above illustrate) to have some kind of automatic support for making a TOC. What do you think?

I agree TOC support would be useful, but if it's not part of the standard, and not part of the Markdown rendering library, then it's not going to be in the plugin. There's a pull request #747 to switch to using libcmark, so if you can get this feature added there, it will just work in the future.

> I have no idea where to get a "non-standard extension from some other Markdown renderer ". Why do you ask?

I mean you're requesting a feature (TOC auto-generation) that is not part of any Markdown standard, but rather an extension provided by whatever other Markdown tool you got it from. It's quite common to get enhancement requests to add non-standard Markdown features where the poster assumes the feature is standard but it's just some custom extension (ex. Github markdown, StackOverflow markdown, etc). This plugin doesn't implement Markdown renderer/compiler by itself, it uses separate libraries to do it, so it's not really feasible to add any special extensions directly in this plugin.

**Comment by elextr** [comment]
Markdown standard is so wonderful everybody has their own :grin:

**Comment by VictorelPetrovich** [comment]
Thanks for the answer.
 I was going to close this issue myself too, as I was mistaken when posting it.

The renderer / converter of this plugin sticks to commonMark spec. I personally think there would be nothing wrong with giving the users an option to "break" the Cmark standard by supporting some  tables or code-highlight syntax (that commonmark.org has very slow progress, if any, on these questions).  
But there are technical and time problems - I get it.

Still, the name of this plugin - `Markdown` - suggests that this plugin does not have to be restricted to converting to `html` only; and already, showing a live preview of the `html` is not something implemented by [Cmark](https://github.com/commonmark/cmark) itself.

Instead, this plugin could, in principle, incorporate other extensions which have nothing to do with Markdown standard.
One of them could be:
- an option to  generate a TOC inside the `.md` file, based on the headings in this file, and then also adding some anchor tags with `id` beside each heading. It could be done at a button click / shortcut key (i.e, does not have to be done live, like the preview), so that not to make it slower, if that's is a problem
The job of the html previewer would remain as is.

Does it make sense? I could open a separate issue for this if yes.

For my own use, I prepared a method involving a sequence of 9 (!) regex substitutions, plus couple of copy-paste, that, after all applied,  result getting a TOC in the .md file which is functional in the .html file. Obviously, a bit tedious.

I could share them if anyone else needs it.

**Comment by codebrainz** [comment]
I don't disagree it would be a useful feature as well as other extensions being useful (ex. tables and such), but it's out of scope (and technically impractical - involving forking a 3rd party library), so no extensions aren't supported by the underlying Markdown compiler library will be supported by the plugin.

Feel free to let me know if you think I'm misunderstanding what you're proposing.

**Comment by VictorelPetrovich** [comment]
I guess the problem is that I write very long replies :)

> no extensions which aren't supported by the underlying Markdown compiler library will be supported by the plugin.

You are referring to table, code-highlight syntax and others. I only mentioned them in passing, but my main suggestion is in the second half of my previous reply. 
An extension that does some transformation of the `.md` file (of which generating TOC is an example) does not involve changing the library for producing the `.html` file.
