### ISSUE TITLE
Copy File Path

### ISSUE THREAD

**Issue by pqanc** [geany/geany-plugins#779]
I have installed geany-plugins 1.29, I think that I should have the 'Copy File Path' but I don't have it. Look this [info.](https://github.com/geany/geany-plugins/commit/3901b9d733deb3d0c5c6bfc06a0e91cef40389c6)

Or How I can copy file path?

**Comment by pqanc** [comment]
On Debian 9 Stable  all is very old XD. Anyhow, i have install all
official plugins, include geany-plugin-addons.

On Wed, 26 Sep 2018 23:21:23 -0700
elextr <notifications@github.com> wrote:

> WFM (on 1.34) 1.29 is a very old version, not sure if it has the
> feature, did you enable the addons plugin?
> 


---
PQ

**Comment by elextr** [comment]
Well if you have enabled (not just installed) the add-ons plugin and there isn't a `copy file path` in the tools menu then its not in that version.

**Comment by elextr** [comment]
Note the point of the comment that its an old version is that none of the project people are likely to have it available for testing.

**Comment by pqanc** [comment]
Oh! Thanks for your help. Active and on Tools menu appear. Please close
this issue.

**Comment by elextr** [comment]
Github lets you close issues you create (see button next to comment).
