### ISSUE TITLE
Scope debug plugin: using resources with relative path

### ISSUE THREAD

**Issue by perezh** [geany/geany-plugins#785]
Hi all,
I've successfully built the current master of geany and geany-plugins from source with the scope plugin. However, it seems that binaries are executed in a different way from geany when debugging. 

I've a program which opens a image file using a relative path (e.g., ./resources/file.png). When geany is used to execute it, it runs without any problem. When I run it using scope, the program raises an error stating that the file cannot be found. 

If I use an absolute path to the file, then I can run the program without errors from geany and from the debugger.

Thanks very much!

**Comment by perezh** [comment]
No, I didn't. It was empty. 
Anyway, I added the folder with the binary now and the error is still there.
Thanks

**Comment by LarsGit223** [comment]
This seems to work OK for me. I created a file in a folder ```program/test/test.txt``` and I could open it in a test program (via ```fopen ("./test/test.txt", "r");```. My working dir was set to the ```program``` folder. Are you sure you set the directory properly?

E.g. see the screenshot below:

![scope_set_workingdir_edited](https://user-images.githubusercontent.com/9009011/53367292-0a036780-3946-11e9-8703-5a53bff4c035.png)

Only setting the ```Executable``` is not enough.

**Comment by perezh** [comment]
Thanks for your reply. This is how the scope debugger works, but it is somehow unusual to set a working dir since running the binary in geany without debugging does not require it. At least, this does not seem the typical setup in other debuggers. Anyway, I think we can close this issue as it is the expected behaviour of the scope plugin. 
Kind regards!

**Comment by LarsGit223** [comment]
> since running the binary in geany without debugging does not require it

Of course not. But if the program uses a relative path then you need the correct working dir to be set.

Well, an alternative would be to use the directory of the binary, if the _"Working dir"_ is empty. But I think using the directory of the binary might not always be the correct working dir so I do not want to remove that option. Another option would be to use the current project's base path (if a project is open).

**Comment by perezh** [comment]
Yes, I fully agree. If working dir is empty, the default dir should be the directory of the binary. This can speed up working with geany.

**Comment by elextr** [comment]
> since running the binary in geany without debugging does not require it.

Actually it does, see `Build->Set Build Commands` its just that it defaults to the directory of the open document if nothing is specified.  Which is not always sensible. 

So using the directory of the specified executable as default when nothing is specified makes sense.
