### ISSUE TITLE
cannot install markdown plugin

### ISSUE THREAD

**Issue by RuinChristmas** [geany/geany-plugins#792]
The markdown preview plugin is not included when geany-plugins is installed from Linux Mint software manager.

I have tried to install by cloning and following directions in readme

`ruin@ruin-notebook:~/Desktop/geany-plugins$ ./configure --enable-markdown
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
`

Thank you for helping me figure out what I am doing wrong

**Comment by elextr** [comment]
Probably the system does not have the required (old) version of webkitgtk.  The next release of Geany-Plugins markdown will support webkit2gtk.

**Comment by elextr** [comment]
Sorry to be confusing, I was interrupted in answering and sent the half finished comment, and even after editing its still confusing.

So to be clear.

If I understand correctly the standard Geany supplied by Ubuntu (and thus Mint) is built against GTK-3, but the markdown plugin up to and including 1.33 required webkitgtk which is a GTK-2 version so it isn't compatible with the supplied GTK-3 Geany and thats likely why the markdown plugin isn't included in the software manager.

The current Git and therefore next release 1.34 will also work with webkit2gtk which is GTK-3.

if @RuinChristmas builds the git version of the markdown plugin against the standard supplied Geany it should work, no need to build a whole GTK-2 version like @Skif-off did.

The errors look like some missing build tools, and as I said I am told that apt can load the required tools if its asked for `build-deps` (never done it myself though).

**Comment by RuinChristmas** [comment]
I installed libwebkitgtk-1.0-0

Then I tried to install the markdown plugin with ./configure but same error message as above.

Then I uninstall and reinstall the geany-plugins from software manager.  Still markdown viewer is not installed.

Thanks again for your help in this matter I am not very advanced so I appreciate your patience.

**Comment by elextr** [comment]
@RuinChristmas what GTK version is you Geany using?  Open your Geany and do `Menu->Help->Debug messages` near the top it will say GTK version?

**Comment by RuinChristmas** [comment]
GTK 3.22.30, GLib 2.56.3

**Comment by elextr** [comment]
Ok, so thats a GTK-3 version of Geany (the 3 on the start of the GTK version), so the plugin build will try to build a GTK-3 version of markdown, which needs webkit2gtk, not webkitgtk which is a gtk-2 version of the library.

Its not possible to mix GTK-2 and GTK-3 in the same application.

**Comment by codebrainz** [comment]
@RuinChristmas could try:

```bash
$ autoreconf -fi
$ ./configure --enable-gtk3 --enable-markdown
```
If the first command fails, you probably don't have Autotools installed properly, which is required when compiling from Git source code.

**Comment by elextr** [comment]
Is `--enable-gtk3` a plugins option? I thought plugins got the GTK version from the specified Geany?

**Comment by b4n** [comment]
@elextr you're right, they do

**Comment by elextr** [comment]
@RuinChristmas did installing the libwebkit2gtk and development packages work for you?

**Comment by arielsbecker** [comment]
> Under Ubuntu 18.04 (Linux Mint 19 is based on 18.04) package `libwebkitgtk-1.0-0` is available (under 18.10 too). I builded and use GTK2-version of Geany + plugins (1.33, I made deb-files) and plugin `geany-plugin-markdown` works fine.

Hi! Do you still have those deb packages? I tried everything to compile, but it seems I'm out of luck.

**Comment by Skif-off** [comment]
@arielsbecker

Sorry, I use Geany with some patches and I am not sure that it will make you happy. But I returned default patches of Debian/Ubuntu packages: [try to compile](https://www.upload.ee/files/9263226/geany-133-with-gtk2.zip.html).

P.S. If you will have an error with GeanyLua then try [this](https://github.com/geany/geany-plugins/pull/778).

**Comment by RuinChristmas** [comment]
> @RuinChristmas did installing the libwebkit2gtk and development packages work for you?

No, sorry I have not tried that yet but I will.  I installed libwebkitgtk-1.0-0 and then didn't see your suggestion about the other.  I will give it a shot tomorrow.

**Comment by burnlawson** [comment]
@elextr I wasn't able to install libwebkitgtk2. I installed libwebkitgtk-1.0 via apt-get but couldn't do the same with v2, downloaded the tar.gz but the build commands were not working so I'm giving up on this mission.

**Comment by RuinChristmas** [comment]
@elextr I wasn't able to install libwebkitgtk2. I installed libwebkitgtk-1.0 via apt-get but couldn't do the same with v2, downloaded the tar.gz but the build commands were not working so I'm giving up on this mission.

**Comment by b4n** [comment]
@RuinChristmas it's *webkit2gtk*, not *webkitgtk2* if that matters: it's "WebKit2 for GTK" and not "WebKit for GTK2".
On Debian Stretch, the relevant package is *libwebkit2gtk-4.0-dev*.

**Comment by elextr** [comment]
@RuinChristmas did you mean to close or just hit the wrong button?

**Comment by RuinChristmas** [comment]
@b4n Thank you, i just mistyped but with your advice I was able to get libwebkit2gtk-4.0-dev via apt-get

@elextr and others thank your for your help.  I then did 

```
./configure  --enable-markdown
make
sudo make install
```

and it worked and I now have the markdown preview!
