### ISSUE TITLE
Scope breaks nightly with cppcheck 1.85

### ISSUE THREAD

**Issue by elextr** [geany/geany-plugins#794]
@LarsGit223 [This](https://github.com/geany/geany-plugins/blob/4d99fcd78c11a1615f42845c59637e7a89a2960c/scope/src/memory.c#L393) line seems to break nightlys with gcc 8, maybe needs parens around the argument to `sizeof`.

**Comment by b4n** [comment]
@elextr which nightlies?  The ones on nightly.geany.org currently break because of a cppcheck issue, which I believe to be a cppcheck bug because it builds fine, and always did build fine.

Yes, adding parentheses around might be a workaround, but it still looks like a cppcheck bug to me, unless indeed gcc 8 also fails and that's not a new bug but a new restriction coming from C11 or something -- which I would find odd, but well.

I'll try to investigate what I can, but the code does look legitimate to me.  A reasonable alternative could be using `MAX()` as it's what the code actually does IIUC:
```c
pointer_size = MAX(sizeof(void *), sizeof &memory_init);
```
but I don't see any good reason to change that line apart from working around a cppcheck bug yet.

**Comment by elextr** [comment]
@b4n, sorry to confuse I was just using "with gcc 8" as a way of identifying which nightlys failed, not that gcc failed. 

I didn't try to debug the failure, just identified the line, and noted the missing () on `sizeof`.  Sure `sizeof` doesn't need parens, its not a function, but for both human and software consumption its better to have them so the intention is clear and nobody has to remember the operator priority of anything more than +-*/ :)

**Comment by b4n** [comment]
@elextr OK

Well, looking at the cppcheck error ("AST broken, binary operator '>' doesn't have two operands") I would expect that it's the ternary operator that doesn't get parsed correctly, and thus that it'd likely help more to add parentheses around the test, rather than around `&memory_init`.  But well, as it's a bug, who knows :)

**Comment by elextr** [comment]
>  I would expect that it's the ternary operator that doesn't get parsed correctly,

Well, I was thinking the "suspicious" `sizeof` since thats whats on one side of the '>' operator, but as you say, its a bug, could be anything :grin:

I suppose `MAX` has clearer intention, just its a m-m-m-macro `<breaks out in hives>`

**Comment by b4n** [comment]
Reported upstream: https://trac.cppcheck.net/ticket/8870

**Comment by LarsGit223** [comment]
@elextr , @b4n: I wouldn't mind changing this because IMHO I would at least call it unusual or "kind of ugly" to not have sizeof with parentheses surrounding it.

But another question: what is the sense behind the comparsion in
```
pointer_size = sizeof(void *) > sizeof &memory_init ? sizeof(void *) :
sizeof &memory_init;
```
Can the size of that pointers ever be not equal??? :confused:

**Comment by b4n** [comment]
@LarsGit223 I think it's a case of over-carefulness: no, there is nothing guaranteeing the size of a data pointer and the size of a function pointer to be equal [1], but in practice I would expect this to always be the case, especially on platforms where GTK+ works.
But as the check is here, I'd keep it, maybe just changing it to a `MAX()` if anything.

[1] actually in theory pointer to different data types could be incompatible, but it's kinda irrelevant void* ought to be able to store pointers to any type, so there's little reasons for other pointers not to simply have the same size.

**Comment by LarsGit223** [comment]
> [1] actually in theory even pointers to different data types could be incompatible, but it's kinda irrelevant void* ought to be able to store pointers to any type, so there's little reasons for other pointers not to simply have the same size.

??? How could that ever be? An address is an address, no matter what data type it points to?

**Comment by b4n** [comment]
@LarsGit223 The C standard doesn't think it's that simple :)

**Comment by LarsGit223** [comment]
@b4n: 
> The C standard doesn't think it's that simple :)

Could you please explain what you mean? Ok, I have to specify the type of a pointer of course but that only matters for referencing it's contents or pointer arithmetics (e.g. ```pointer++```). So is this really a thing from the C standard? Or is it more something that can happen on non x86 compatible machines?

**Comment by LarsGit223** [comment]
@b4n: never mind. I found some detailed info at https://www.quora.com/What-is-the-size-of-a-pointer-in-C.

**Comment by elextr** [comment]
And although not a likely Geany target, things like GPUs and special processors do run C.  They separate program and data memory so the respective pointers are possibly not the same size.

But IIUC some POSIX functionality requires all pointers to be the same size, so anywhere Geany runs is likely to be one size fits all.

**Comment by b4n** [comment]
You found it yourself, but basically the thing is that the C standard doesn't enforce much on pointer sizes.  The only (IIRC) thing that it requires is that a pointer to `void` can hold any other *data* pointer, and that a cast back to the original type yields the same pointer (and that `intptr_t` has the same kind of properties).  Anything further is implementation defined.

As said, in most common situations (your computer, mine, etc.), all pointers can be happily casted between different types back and forth, even function pointers.  But the C standard allows this not to be the case.
The following *could* result in undefined behavior:
```C
float f1 = 4.2f;
float *fp = &f1;
int *ip = (int*)fp;
float f2 = *((float*)ip);
// whether f1 == f2 is implementation defined
```

But again, as @elextr just said, we probably don't really have to worry about that.  And yeah things like `dlsym()` basically require `void*` to be able to hold a function pointer as well.

**Comment by eht16** [comment]
```
The following packages have unmet dependencies:                                                                                                                                                                                
 pbuilder-satisfydepends-dummy : Depends: libwebkitgtk-dev (>= 1.1.18) which is a virtual package and is not provided by any available package                                                                                 
 or                                                                                                                                                                                                                            
                                          libwebkit-dev (>= 1.1.18) which is a virtual package and is not provided by any available package                                                                                    
                                                                                                                                                                                                                               
Unable to resolve dependencies!  Giving up...     
```

Webkit1 isn't available anymore and so `pbuilder` cannot install the build dependencies. This happens in such an early stage that it is not visible in the builds logs on nightly.geany.org.

I'm going to remove the Webkit related plugins from the Debian builds.
Note that those plugins are also already removed from the official Debian packages (https://salsa.debian.org/geany-team/geany-plugins/blob/master/debian/changelog#L9).

**Comment by elextr** [comment]
@eht16 how did those builds work before then? Did you update the Debian?

Anyway this can be closed fixed by #795

**Comment by codebrainz** [comment]
> I'm going to remove the Webkit related plugins from the Debian builds.

@eht16 the Markdown plugin should be ok: 4039a13882f4b9e2127f6e7b018bdbdffe36e2a2

**Comment by elextr** [comment]
> > I'm going to remove the Webkit related plugins from the Debian builds.

> @eht16 the Markdown plugin should be ok: 4039a13

@codebrainz IIUC the problem is that Debian no longer ships _any_ GTK2 version of webkit, so the nightly GTK2 builds using recent Debians fail due to no webkit available.

Of course markdown and other webkit based plugins should work when the nightlys are built against GTK#

**Comment by eht16** [comment]
Ah cool: https://metadata.ftp-master.debian.org/changelogs/main/g/geany-plugins/geany-plugins_1.33+dfsg-1_changelog

Then we will get GTK3 nightlies soon probably including Markdown after the sync.
Will do after Debian has the 1.34 release.
