### ISSUE TITLE
git-changebar not working on ubuntu 18.04 with 1.33+dfsg-1~17.10

### ISSUE THREAD

**Issue by laoshaw** [geany/geany-plugins#805]
on ubuntu 18.04 after added : sudo add-apt-repository ppa:geany-dev/ppa

an apt update will install 1.33 geany-plugins except for git-changebar that is broken:

```
The following packages have unmet dependencies:
 geany-plugin-git-changebar : Depends: libgit2-24 (>= 0.24.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

```
dpkg -l |grep libgit
ii  libgit2-26:amd64     0.26.0+dfsg.1-1.1ubuntu0.2      amd64        low-level Git library
```

**Comment by elextr** [comment]
Despite the name of the PPA, it isn't operated by the Geany project.  You need to report problems with the packages to the PPA.

**Comment by frlan** [comment]
@laoshaw Please report this bug to launchpad as this is a packaging issue.

**Comment by gsantner** [comment]
@frlan 
I downloaded the PPA package and noticed that this **still** happens to be the case. I rebuilt the git-changebar plugin from source and just swapped out the .so file from the .deb file.

Download: https://github.com/gsantner-extra/gs-debian/releases/download/upload/geany-plugin-git-changebar_1.34+dfsg-1.14.04_amd64.deb

I built from commit <https://github.com/geany/geany-plugins/tree/9694c624d6a3ff579dc03f84f24f4c99295f0027> and running it fine on Ubuntu 18.04 + Geany 1.34.1 (from PPA)

**Comment by elextr** [comment]
@gsantner to make the statement above clearer, the Geany project __does not__ operate the PPA, there is no point in reporting problems with it here.

**Comment by gsantner** [comment]
@elextr I know, and have known when posting.

I provided a working solution, not reported one.

**Comment by elextr** [comment]
@gsantner ok, just we get a lot of people who post about the PPA here.

Why did you need to download the deb to build from git? Building from git should work by itself.

**Comment by gsantner** [comment]
@elextr the ppa provides builds against dated packages of U14.04 that are not available in newer Ubuntu.

I did download it to keep structure and everything exactly same.


> ok, just we get a lot of people who post about the PPA here.

Why you don't tell **prominently** about "no ppa support" in readme, issue template or website? I mean don't get angry at people if it's not written at some relevant page at Geany itself. Doesn't matter what the PPA own description says or whom it is from.
Tell users in advance that it's not supported (and tell what is supported at the same time) and you get less such reports.

**Comment by gsantner** [comment]
@elextr the ppa provides builds against dated packages of U14.04 that are not available in newer Ubuntu.

I did download it to keep structure and everything exactly same.


> ok, just we get a lot of people who post about the PPA here.

Why you don't tell **prominently** about "no ppa support" in readme, issue template or website? I mean don't get angry at people if it's not written at some relevant page at Geany itself. Doesn't matter what the PPA own description says or whom it is from.
Tell users in advance that it's not supported (and tell what is supported at the same time) and you get less such reports.
