### ISSUE TITLE
scope: crash on modiyfing "Locals" without selection

### ISSUE THREAD

**Issue by LarsGit223** [geany/geany-plugins#825]
The following sequence of actions crashes Geany:
1. start debugging a program with the scope plugin
1. wait for a breakpoint
1. in the message window select _"Debug"_ and then select tab _"Locals"_
1. left click in the tabs content area (to prevent #824)
1. the local variables show up, but none of them is selected
1. right click inside the tab to show the context menu, select _"Modify"_
1. Geany crashes

Remark: the crash does not occur if the user first selects a variable to _"Modify"_.

**Comment by codebrainz** [comment]
I hope you used the Scope plugin to debug this crash in itself 😃
