### ISSUE TITLE
documentation: missing description for unit tests?

### ISSUE THREAD

**Issue by LarsGit223** [geany/geany-plugins#828]
I wanted to write some unit tests. I saw that there seems to be a unit test infrastructure using the check framework. But I did not find any documentation about how to build geany-plugins for unit testing.

So:
How do I build for unit-testing and how do I run the tests?

**Comment by elextr** [comment]
If you mean `make check` thats in autotools docs eg http://buildsystem-manual.sourceforge.net/Tests.html#Tests

**Comment by LarsGit223** [comment]
Thanks @elextr that helped me. I still got problems with building the test but I now know how to start the build. So I close this. I'll report my problems at the corresponding PR.
