### ISSUE TITLE
Bug: "Find" does not work in the right windows of split windows (side-by-side split)

### ISSUE THREAD

**Issue by 9527KGG** [geany/geany-plugins#833]
Bug report:

"Find" does not work in the right windows of split windows. It only works in the left windows. (side-by-side split)

OS: Xubuntu 18 LTS
Geany: 1.32

Thanks.

**Comment by elextr** [comment]
Although split window is a plugin, it is in the core Geany repository, not the Geany plugins repository, so it should be reported in that, where you will find (pun intended) that its already known and is a duplicate of issue [604](https://github.com/geany/geany/issues/604).

**Comment by 9527KGG** [comment]
Thanks. Close.
