### ISSUE TITLE
GeanyVC: no feedback / error reporting if commit failed

### ISSUE THREAD

**Issue by eht16** [geany/geany-plugins#837]
There is no feedback about a failed GIT commit at all.
No status bar message, no status window message, no message in Help->Debug Messages and no error dialog.

At least one the above should happen to tell the user that the commit did not happen.
IMO there should be a message in Help->Debug Messages at the very least but also some more visible feedback to the user like an error dialog or at least a status bar message.

The only trace you get is the GIT error output on stderr but I guess most people won't want Geany's stderr regularly :).

**Comment by eht16** [comment]
For easy testing: `touch .git/index.lock` in some GIT repository.

**Comment by elextr** [comment]
> The only trace you get is the GIT error output on stderr but I guess most people won't want Geany's stderr regularly :).

And for those starting Geany from a desktop menu/icon there is no stderr.
