### ISSUE TITLE
Pinned Tab

### ISSUE THREAD

**Issue by luigifab** [geany/geany-plugins#839]
Like the Firefox pinned tab functionality (https://support.mozilla.org/en-US/kb/pinned-tabs-keep-favorite-websites-open), is Geany can add the same feature with the projectorganizer plugin?

All pinned tab are shared with all projects.

(the Pinned Tab is very useful with the dead Tab Groups functionality)

**Comment by codebrainz** [comment]
> Oh sorry, I didn't see that second git repository

No worries, Github now makes it easy to move issues between repositories. done.

**Comment by andy5995** [comment]
@luigifab I'm working on a "Pinner" plugin in https://github.com/geany/geany-plugins/pull/1308
