### ISSUE TITLE
Select to matching brace

### ISSUE THREAD

**Issue by redman684** [geany/geany-plugins#840]
I love the "goto matching brace" command (ctrl-b), but it's too bad this can't be combined with selecting text.

A "select to matching brace" command would make it super easy to select blocks of code. ctrl-shift-b seems like a intuitive key combo for it. 

Some cursor movement can be combined with selecting text, pageup, ctrl-left, etc. Others can't: goto matching brace, goto next marker, etc. Maybe there could be more overall consistency? 
Or is there a reason against any cursor movement (while the shift is pressed) changing the selection?

**Comment by elextr** [comment]
1. Install Geany plugins.

2. check Tools->Plugin Manager->Extra Selection

3. click keybindings

4. select the "select to matching  brace" line

5. click change

6. type ctrl+shift+b

7. "ok" and "close" your way out

**Comment by redman684** [comment]
Wow, that covers my most wanted feature. ctrl+shift+b -> "select to matching brace". Even to the exact spelling. Thank you very much.
