### ISSUE TITLE
workbench: Changing options are not saved

### ISSUE THREAD

**Issue by frlan** [geany/geany-plugins#841]
When using the Tools->Workbench->Settings changed options are not saved to configuration file of workbench project

**Comment by frlan** [comment]
@LarsGit223 I think this is something for ;)

**Comment by LarsGit223** [comment]
@frlan: did you choose _"Tools->Workbench->Save"_? The settings are not saved automatically.

**Comment by frlan** [comment]
@LarsGit223  No I did not. Expectation for settings was, that it is saved automatically.

**Comment by LarsGit223** [comment]
Well, then everything works as-designed and it is not a bug. But you could change the label to "enhancement" if you like.

**Comment by frlan** [comment]
Done. While unexpected behaviour is a bug for me ;)

**Comment by LarsGit223** [comment]
> Done. While unexpected behaviour is a bug for me ;)

It is the expected behaviour (it works as implemented/expected by the author). But your expectations doesn't match the actual implementation ;-)

**Comment by LarsGit223** [comment]
@frlan: I now also removed the option _"Save project"_ and projects are also saved automatically if a workbench related project setting is changed. Also I fixed a little bug regarding this issue, see PR #877.
