### ISSUE TITLE
debugger plugin

### ISSUE THREAD

**Issue by horchi** [geany/geany-plugins#852]
only a few questions so far. I like to get the debugger plugin working, I don't have fond a packaged version for one of  the recent ubuntu releases - seems to be not supported by ubuntu anymore.

Therefore just compiled and installed the plugin from source naw.

At this point I like to use it, after I don't found a way (by a menu or button) to start a program inside of geany using this Plugin I defined a keybinding. At this point i can set breakpoints and start the program in the debugger - fine so far.

But how i can call all the gdb commads now? 

Thanks and best regards 
Jörg

**Comment by LarsGit223** [comment]
You can select the program to execute in the debugger panel under the target tab:

![debugger_panel_target](https://user-images.githubusercontent.com/9009011/57549257-55cd8680-7363-11e9-9bfd-0ead94759dd5.png)

(See label ```Target: /home/lars/test/program```)

Not sure if the debugger plugin allows entering commands for gdb. I did not find an option for that myself. Maybe someone else knows the solution.

Alternatively you can try the other debugger plugin called scope debugger. But if you got questions regarding that plugin, please open a new thread/issue.

For general information or introduction to a plugin from geany-plugins have a look at https://plugins.geany.org.

**Comment by horchi** [comment]
Thx, the general debugging seams to be working this way, but without to option to use gdb prompt directly it is to circuitous for me.

I checked this weekend around with geany for editing code and debugging - some geany options especially navigating in the source code by the object classes is very nice but below the line I'am much more efficient by using emacs as IDE. 

Thx and best regards

**Comment by LarsGit223** [comment]
Also see #336.

**Comment by laoshaw** [comment]
running ubuntu 18.04 + geany 1.34(newer than the default 1.32 from ubuntu 18.04) and still saw no debugger available under geany, based on https://askubuntu.com/questions/1068430/geany-plugin-debugger-missing-in-ubuntu-18-04 it's not supported, will it be sometime?

**Comment by codebrainz** [comment]
@laoshaw the link is talking about other plugins that use WebKit browser widget, and I don't think any of the debugger plugins use that. As far as I know all 3 of the debugger plugins work fine on Linux, perhaps they just didn't get packaged by the Ubuntu team.

**Comment by laoshaw** [comment]
maybe that's a wrong guess but debugger is not working for sure, as stated elsewhere: https://github.com/geany/geany-plugins/issues/758

**Comment by elextr** [comment]
@laoshaw please read the comments, #758 last comment notes that debugger has been updated and will be in the next release of Geany/Geany plugins.  So adding comments will make no difference.

**Comment by laoshaw** [comment]
I read that and am building from source, yes it will be fixed in future(next) release, but for now you get no debugger on recent releases.

**Comment by codebrainz** [comment]
You get them if you don't use packages from distros which disabled them.

**Comment by elextr** [comment]
And Geany doesn't do distro packaging, so its no use commenting here, you could comment to your distro, but they are likely to just say they won't package until after next release.

**Comment by laoshaw** [comment]
this is geany-plugins github where user visits often when they have doubts about plugins, I wrote here to share info in case someone will be looking for similar info, thanks for you working on this great software that I use often.
