### ISSUE TITLE
Compile Geany Plugins on Windows

### ISSUE THREAD

**Issue by ramisedhom** [geany/geany-plugins#887]
Thanks to advice how to compile Geany Plugins on Windows using MSYS2.

I did following steps:
1. Installed [MSYS2](http://www.msys2.org)
2. Downloaded https://github.com/geany/geany-plugins/archive/master.zip
3. From MSYS2 terminal, installed: intltool, autoconf, libtool and automake

> pacman -S intltool
> pacman -S autoconf
> pacman -S libtool
> pacman -S automake

4. Run: ./autogen.sh, it exist with error. Following is the output:

> You should add the contents of '/usr/share/aclocal/intltool.m4' to 'aclocal.m4'.
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force -I build/cache -I build -I build/bundled -I geanypy/m4 --install
> build/i18n.m4:15: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:1: _GP_GEANY_LIBDIR is expanded from...
> build/geany.m4:16: GP_GEANY_PKG_CONFIG_PATH_PUSH is expanded from...
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:26: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/gtk.m4:4: GP_CHECK_GTK_VERSION is expanded from...
> configure.ac:26: the top level
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:1: _GP_GEANY_LIBDIR is expanded from...
> build/geany.m4:16: GP_GEANY_PKG_CONFIG_PATH_PUSH is expanded from...
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:26: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/gtk.m4:4: GP_CHECK_GTK_VERSION is expanded from...
> configure.ac:26: the top level
> aclocal-1.16: installing 'build/cache/libtool.m4' from '/usr/share/aclocal/libtool.m4'
> aclocal-1.16: installing 'build/cache/ltoptions.m4' from '/usr/share/aclocal/ltoptions.m4'
> aclocal-1.16: installing 'build/cache/ltsugar.m4' from '/usr/share/aclocal/ltsugar.m4'
> aclocal-1.16: installing 'build/cache/ltversion.m4' from '/usr/share/aclocal/ltversion.m4'
> aclocal-1.16: installing 'build/cache/lt~obsolete.m4' from '/usr/share/aclocal/lt~obsolete.m4'
> aclocal-1.16: installing 'build/cache/nls.m4' from '/usr/share/aclocal/nls.m4'
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:1: _GP_GEANY_LIBDIR is expanded from...
> build/geany.m4:16: GP_GEANY_PKG_CONFIG_PATH_PUSH is expanded from...
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:26: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/gtk.m4:4: GP_CHECK_GTK_VERSION is expanded from...
> configure.ac:26: the top level
> autoreconf: configure.ac: tracing
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:1: _GP_GEANY_LIBDIR is expanded from...
> build/geany.m4:16: GP_GEANY_PKG_CONFIG_PATH_PUSH is expanded from...
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:26: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/gtk.m4:4: GP_CHECK_GTK_VERSION is expanded from...
> configure.ac:26: the top level
> autoreconf: running: libtoolize --copy --force
> libtoolize: putting auxiliary files in '.'.
> libtoolize: copying file './ltmain.sh'
> libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build/cache'.
> libtoolize: copying file 'build/cache/libtool.m4'
> libtoolize: copying file 'build/cache/ltoptions.m4'
> libtoolize: copying file 'build/cache/ltsugar.m4'
> libtoolize: copying file 'build/cache/ltversion.m4'
> libtoolize: copying file 'build/cache/lt~obsolete.m4'
> build/i18n.m4:15: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:1: _GP_GEANY_LIBDIR is expanded from...
> build/geany.m4:16: GP_GEANY_PKG_CONFIG_PATH_PUSH is expanded from...
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:26: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/gtk.m4:4: GP_CHECK_GTK_VERSION is expanded from...
> configure.ac:26: the top level
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:1: _GP_GEANY_LIBDIR is expanded from...
> build/geany.m4:16: GP_GEANY_PKG_CONFIG_PATH_PUSH is expanded from...
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:26: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/gtk.m4:4: GP_CHECK_GTK_VERSION is expanded from...
> configure.ac:26: the top level
> autoreconf: running: /usr/bin/autoconf --force
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:24: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/geany.m4:1: _GP_GEANY_LIBDIR is expanded from...
> build/geany.m4:16: GP_GEANY_PKG_CONFIG_PATH_PUSH is expanded from...
> build/geany.m4:31: GP_CHECK_GEANY is expanded from...
> configure.ac:24: the top level
> configure.ac:26: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd
> build/gtk.m4:4: GP_CHECK_GTK_VERSION is expanded from...
> configure.ac:26: the top level
> configure:13977: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> configure:14016: error: possibly undefined macro: AM_CONDITIONAL
> configure:14420: error: possibly undefined macro: AS_TR_SH
> configure:14420: error: possibly undefined macro: m4_tolower
> autoreconf: /usr/bin/autoconf failed with exit status: 1
> 
>

**Comment by Skif-off** [comment]
https://wiki.geany.org/howtos/win32/msys2 works fine for me (GTK2):
- One-time Setup
- GTK+2 compilation
- Plugins:
```sh
cd
curl -L -o geany-plugins-master.zip https://github.com/geany/geany/archive/master.zip
unzip geany-plugins-master.zip
cd geany-plugins-master
NOCONFIGURE=1 ./autogen.sh
./configure --prefix=/c/geany --with-geany-libdir=/c/geany/lib --disable-silent-rules
make -j2
make install
```
- Creating a GTK runtime bundle

**Comment by eht16** [comment]
Please re-open if you still have issues building Geany with the instructions in the wiki, as mentioned above.
