### ISSUE TITLE
JSON autoformater plugin

### ISSUE THREAD

**Issue by frlan** [geany/geany-plugins#891]
It would be awesome to have a plugin similar to XML Pretty printer to format JSON nicely

**Comment by elextr** [comment]
Set custom command `python3 -m json.tool`.

For more details see [here](https://docs.python.org/3/library/json.html#json-commandline)

**Comment by Skif-off** [comment]
[JSON Prettifier](https://plugins.geany.org/jsonprettifier.html)?

**Comment by frlan** [comment]
OK. Already plenty of solutions ;)

**Comment by eht16** [comment]
FTR: https://wiki.geany.org/config/json has details about configuring `python3 -m json.tool` as custom command.

**Comment by b4n** [comment]
…or [json_pp](https://metacpan.org/pod/distribution/JSON-PP/bin/json_pp)
