### ISSUE TITLE
Addons: Open Documents menu opens in wrong location when button in drop-down

### ISSUE THREAD

**Issue by PatrickGMM** [geany/geany-plugins#892]
Using Geany version 1.35 compiled under linux mint 19.1 cinnamon for GTK version 2.24.32. Using version 1.35 of the plugins pack compiled under the same config.

The problem occurs when the button for the Open Documents feature is rolled-up into the drop-down button (when the toolbar isn't wide enough to display the button). The button in this case has no parent window, so you need to get the window of the parent of the button for calculating the position of the Open Documents window in ao_popup_position_menu() in ao_doclist.c.

Attachment shows diff of how I fixed it on my machine (ao_doclist.c):

[ao_doclist.c-changes.txt](https://github.com/geany/geany-plugins/files/3475659/ao_doclist.c-changes.txt)

**Comment by PatrickGMM** [comment]
I added a pull request (#895) with a more robust solution to the issue.

**Comment by eht16** [comment]
Fixed via #895.
