### ISSUE TITLE
ProjectOrganizer: Adding a new file to a project directory

### ISSUE THREAD

**Issue by chrisgraham** [geany/geany-plugins#894]
It would be great to be able to right click on any directory in the organizer and have an option to create a new file (blank, or from one of the templates) in there. It'd ask a filename, and if a template had been chosen the default would be based on the name of that template.

**Comment by techee** [comment]
@chrisgraham I guess you are using some older version of the plugin - this feature has been added in https://github.com/geany/geany-plugins/pull/783. I'm closing this pull request, feel free to re-open it if you think something is missing.
