### ISSUE TITLE
SpellCheck always marks words as misspelled

### ISSUE THREAD

**Issue by rbrown-acertaralabs** [geany/geany-plugins#898]
Windows 10
Geany v1.34.1
Enchant v2.2.3
Downloaded `en_US.aff` and `en_US.dic` dictionary files from `https://cgit.freedesktop.org/libreoffice/dictionaries/tree/en`

The spell checker marks every single word as misspelled.  Screenshot of symptom, debug messages, and configuration:

![image](https://user-images.githubusercontent.com/17712548/63719133-80a3f380-c809-11e9-9a1d-1adff618e164.png)

Also, Windows OS language setting is "English US" which matches the dictionary:

![image](https://user-images.githubusercontent.com/17712548/63720161-d5e10480-c80b-11e9-90cd-9423917f9461.png)

**Comment by eht16** [comment]
Are you sure you downloaded the dictionary files correctly?
They should contain just plain text, no HTML or anything else.
I can reproduce the described behaviour if the dictionary files are invalid.
