### ISSUE TITLE
vimode: numbers can be inserted while in normal mode

### ISSUE THREAD

**Issue by PachequinPlusPlus** [geany/geany-plugins#899]
you can't type anything while in normal mode, but you do can put numbers which makes command like "3d", or "5G" impossible to use, not sure if it's just a bug on my end, but it's happening to me right now.

**Comment by techee** [comment]
What version of geany-plugins are you using? From the description to me this bug seems like https://github.com/geany/geany-plugins/pull/820 which should be fixed in newer versions.

**Comment by techee** [comment]
Assuming this is a duplicate of #820, closing.
