### ISSUE TITLE
Projectorganizer: Option to only index files included in source.

### ISSUE THREAD

**Issue by davemcdanel** [geany/geany-plugins#900]
It would be nice to have an option to only index files listed in the "external directory" that have an #include<...> directive.  This would reduce the amount of indexed files to only index files used in context.

**Comment by techee** [comment]
I'm not sure if this is a good idea - also files without the include directive may contain symbols you might be interested in. It would also require pre-parsing the files for include directives, is specific only to C/C++ so this is probably something I won't implement.
