### ISSUE TITLE
Fails to configure with ./autogen.sh

### ISSUE THREAD

**Issue by liborty** [geany/geany-plugins#902]
configure.ac:16: error: possibly undefined macro: AC_DISABLE_STATIC

**Comment by liborty** [comment]
configure.ac:16: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:17: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by codebrainz** [comment]
Do you have [`libtool`](https://www.gnu.org/software/libtool/) installed?

**Comment by liborty** [comment]
Ah, that was it, thanks Codebrainz!
