### ISSUE TITLE
vimode o/O not respecting indent settings

### ISSUE THREAD

**Issue by alukreis** [geany/geany-plugins#910]
Hi,

This ones a bit simpler, basically when I press o (lowercase) in vimode, in geany it sends the cursor to the very beginning of the newline below, in vim it would respect the auto indent and put the cursor where it should be, just like hitting return at the end of a line in geany vimode.

The same happens with O (uppercase), although it is the line above, which is correct, just without the indent again.

I again offer my services if this is something people want.

Thanks,

Lukas

**Comment by techee** [comment]
Thanks for reporting, should be fixed by #918.
