### ISSUE TITLE
No debugger in Geany 1.36

### ISSUE THREAD

**Issue by Nefor111** [geany/geany-plugins#913]
No debugger plugin can be found in Plugin Manager,no file installed.

On Arch linux - installed geany and geany-plugins via pacman
On Debian 10 - Installed via building from sources
On Ubuntu 19.04 - installed via building from sources
On Ubuntu Studio 19.04 - installed via building from sources.

No debugger at all.

Where is no errors on installation process,but ./configure describes me - debugger no

Sorry for my english.Waiting for help.

**Comment by LarsGit223** [comment]
First, let me inform you that there are two debugger plugins in the Geany-Plugins package you can choose from:
- the debugger plugin
- the scope plugin

If the configure script tells you that the debugger plugin is not enabled than a requirement to build the debugger plugin is missing. It could be that the VTE package is missing on your system.

Please follow one of the steps below, depending on your GTK version:
- if you are building for GTK2 please try ```sudo apt-get install libvte-dev```
- if you are building for GTK3 please try ```sudo apt-get install libvte-2.91-dev```

After that please run ```./configure``` again. Does it say ```yes``` now?

**Comment by Nefor111** [comment]
Okey,it's works for Debian and Ubuntu,but in Arch is no such thing like libvte at all...any way to do something?

**Comment by LarsGit223** [comment]
Hmmm...you could try to build ```libvte``` from source. But I have never done it, so I do not know how simple or difficult it is. Maybe you can ask somewhere in the Arch community if they know how to get it or build it on Arch. But without ```libvte``` you cannot build the debugger plugin or the scope plugin.

**Comment by Nefor111** [comment]
Well.Fixed.
For debian\ubuntu need to install libvte-dev for GTK2,libvte-2.91-dev - GTK3

For Arch - need to install package vte3.Then install geany via pacman,and install geany-plugins via building from sources,and it's works.

Thank you for help.But issue is installation via standart way in arch.I hope this will help for users who face this problems too.

Thank you for you help!!!

**Comment by LarsGit223** [comment]
You are welcome.

**Comment by codebrainz** [comment]
> But issue is installation via standart way in arch.

You could report a bug to whoever packages Geany for Arch. I think both Geany and Geany-Plugins packages should depend on VTE library so it gets installed automatically.

**Comment by Nefor111** [comment]
You right,but in Arch the issue it's about binary compiled without VTE. Dosen't matter you have VTE or not,in binary it's disabled.

**Comment by elextr** [comment]
If Geany is compiled when VTE headers are not available then VTE support in Geany must be disabled since it has no way of knowing what the interface to VTE is.  The Autotools build does that automatically.

You could report it to Arch to see if they can build their binary different.
