### ISSUE TITLE
When the "Markdown" plug-in is enabled, opening a markdown file containing "@@markdown@@" always freezes.

### ISSUE THREAD

**Issue by FuRuYa7** [geany/geany-plugins#936]
# When the "Markdown" plug-in is enabled, opening a markdown file containing "@@markdown@@" always freezes.

---
## usage environment

- Ubuntu-Budgie 20.04 LTS "Focal Fossa" - Alpha amd64 (20191125)
- $ uname -r
5.3.0-24-generic

- geany 1.37 (git >= 5cc69b3d) (Dec  9 2019 以降に次を使用してビルドGTK 3.24.12, GLib 2.63.1)
- libwebkit2gtk-4.0-dev/focal,now 2.26.2-1 amd64

I built and installed the Markdown plugin using webkit2gtk.

---
## Reproduction method:

Enable the "Markdown" plug-in in the "Geany" app.

$ geany test.md
Enter "@@markdown@@".

-> As soon as the last “@” was entered, the “Geany” app froze.

**Comment by FuRuYa7** [comment]
By the way, the character string "@@markdown@@" is a reserved word and is included in the file "~/.config/geany/plugins/markdown/template.html".  I think errors can occur, but freezing has a big impact.

**Comment by codebrainz** [comment]
Yeah, I don't plan to change it from being a special token (whatever it changes to would have same issue), but agree just freezing is not great. It's probably some kind of infinite recursion.

**Comment by FuRuYa7** [comment]
Thank you very much.
The string “@@markdown@@” is rarely used, so I don't think there is any problem.

This time, in order to introduce how to customize the “Markdown” plug-in, I pasted the contents of template.html into the Markdown file. Frozen near the end of the document. Since the document was lost, I regret not saving it frequently.
