### ISSUE TITLE
vimode: :[integer] doesn't jump to the line number

### ISSUE THREAD

**Issue by levu42** [geany/geany-plugins#937]
In Vi(m), :[integer] brings the cursor to this line number. This doesn't work with the vimode plugin.

Version: 1.36-2 (arch linux)

**Comment by techee** [comment]
Is it the same problem with the command window not disappearing like in #941 ? If so, we can close this bug report and continue the discussion there.

**Comment by techee** [comment]
I guess this is a duplicate of #941, closing.
