### ISSUE TITLE
debugger

### ISSUE THREAD

**Issue by dx24816** [geany/geany-plugins#938]
Hello, I use Ubuntu 18.04, and am trying to install the Geany Debugger plugin. However, when I checked the terminal, I see this. Is there a way to fix this, or is this intentional?
![image](https://user-images.githubusercontent.com/59266886/71492371-aa474880-2804-11ea-8764-74e0495a39bd.png)

**Comment by elextr** [comment]
Without further info its not possible to say what you are missing, post the whole configure.

But at a guess its likely to be a valid version of VTE development.

**Comment by LarsGit223** [comment]
If you are using gtk2, install VTE like this:
```
sudo apt-get install libvte-dev
```
If you are using gtk3, install VTE like this:
```
sudo apt-get install libvte-2.91-dev
```

**Comment by Ehlarm** [comment]
for me it's the same debugger issue on my Raspbian (Pi4) :(
@LarsGit223
"sudo apt-get install libvte-2.91-dev" doesn't helped too...

**Comment by LarsGit223** [comment]
@Ehlarm: please open a new issue and report your details there as this issue is about a different operating system so the problem fixes might differ and should not be mixed up.

**Comment by andy5995** [comment]
> If you are using gtk3, install VTE like this:
> 
> ```
> sudo apt-get install libvte-2.91-dev
> ```

Solved it for me, on Debian Buster

**Comment by elextr** [comment]
@andy5995 thanks, thats the expected fix as per posts above.

Closing, due to no response from the OP.
