### ISSUE TITLE
How to install the debugger on Debian for ARM?

### ISSUE THREAD

**Issue by fantauzzi** [geany/geany-plugins#942]
I have installed Geany and its plug-ins on a Raspberry Pi 4 running Debian "Buster" with:
`sudo apt install geany`
and
`sudo apt install geany-plugins`
but I find no evidence that a debugger was installed.

How do I install the debugger plug-in, and how do I check that it has been installed successfully?

```
~> geany --version
geany 1.33 (built on 2018-04-16 with GTK 3.22.29, GLib 2.56.1)
~> uname -a
Linux pi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
~> lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by elextr** [comment]
Debugger plugin was not ported to GTK3 until 1.36 I think.

**Comment by codebrainz** [comment]
There's also the Scope plugin, but I believe that was ported to GTK+3 in 1.34

**Comment by fantauzzi** [comment]
As a workaround, I have been able to build and install Geany and the debugger plugin from source. It also required to install libvte-2.91-dev as per [this issue](https://github.com/geany/geany-plugins/issues/913#issuecomment-536662437).

**Comment by elextr** [comment]
fixed
