### ISSUE TITLE
Debugger Plugin on Raspian (Pi4) doesn't work (not loaded)

### ISSUE THREAD

**Issue by Ehlarm** [geany/geany-plugins#957]
The other plugins are "visible", but not the "Debugger" and "DevHelp" items.

My Environment:

g++ & gdb (Raspbian 8.2.1-2)
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux arm 4.19.97-v7l+

The hint from @LarsGit223 doesn't work too (sudo apt-get install libvte-2.91-dev)

related to  #issue #938 

I would be very happy, if somebody has any suggestion for a stable running C/C++/C# developer environment on a Raspberry 4 with Raspbian (32-Bit Debian)? 64-Bit (e.g. Ubuntu or Manjaro) is not stable enough for me.

**Comment by LarsGit223** [comment]
For completeness please also report the gtk and glib version, you can find them in Geany's about dialog.

**Comment by elextr** [comment]
Electron, chrome, Node.js, V8 are all irrelevant, but the rather basic one, version of Geany might help?  

Are you building Geany from source?  If you are using the distros version then just adding libvte won't help if the distro built Geany without debugger.  

If you are building your own Geany post the configure output as I requested on #938

**Comment by Ehlarm** [comment]
sorry @elextr I'am not so familiar with this system (newbi). Geany v1.33 was pre-installed with the "newest" Raspbian Desktop (Debian Buster). I have installed the plugins in a normal manner with "sudo apt-get install geany-plugins".

**Comment by Ehlarm** [comment]
@LarsGit223 today this are Geanys debug messages:

08:52:08: Geany INFO: Geany 1.33, en_US.UTF-8
08:52:08: Geany INFO: GTK 3.24.5, GLib 2.58.3
08:52:08: Geany INFO: System data dir: /usr/share/geany
08:52:08: Geany INFO: User config dir: /home/pi/.config/geany
08:52:09: Geany INFO: Loaded GTK+ CSS theme '/usr/share/geany/geany.css'
08:52:09: Geany INFO: Loaded GTK+ CSS theme '/usr/share/geany/geany-3.20.css'
08:52:09: Geany INFO: System plugin path: /usr/lib/arm-linux-gnueabihf/geany
08:52:09: Geany INFO: Added filetype Graphviz (61).
08:52:09: Geany INFO: Added filetype CUDA (62).
08:52:09: Geany INFO: Added filetype Arduino (63).
08:52:09: Geany INFO: Added filetype Cython (64).
08:52:09: Geany INFO: Added filetype Scala (65).
08:52:09: Geany INFO: Added filetype JSON (66).
08:52:09: Geany INFO: Added filetype Genie (67).
08:52:09: Geany INFO: Added filetype Clojure (68).
08:52:09: Geany INFO: Loaded libvte from libvte-2.91.so
08:52:09: Geany INFO: Loaded:   /usr/lib/arm-linux-gnueabihf/geany/addons.so (Addons)
08:52:09: Geany INFO: /home/pi/projects/helloworld.cpp : C++ (UTF-8)
08:52:09: Geany INFO: Loaded /usr/share/geany/tags/std99.c.tags (C), 1619 symbol(s).

**Comment by elextr** [comment]
Geany 1.33 is a fairly old version, released before debugger was ported to gtk3.  So it would not build with a GTK3 version of Geany and so it isn't in the geany-plugins the distro provides.  I think its only 1.36 (ie the current release) plugins that includes a debugger thats gtk3 compatible.

Unless you can build it yourself you will have to wait for the distro to update it.

**Comment by Ehlarm** [comment]
@elextr thx for these infos. It makes sense 😉 I try to repair this Debugger Problem with a new installation of Geany 🤔

**Comment by Ehlarm** [comment]
today interim results on my Raspbian (Pi4):

+ now Geany 1.36 is running

12:21:27: Geany INFO: Geany 1.36, en_US.UTF-8
12:21:27: Geany INFO: GTK 3.24.5, GLib 2.58.3
12:21:27: Geany INFO: System data dir: /usr/local/share/geany
12:21:27: Geany INFO: User config dir: /home/pi/.config/geany
12:21:28: Geany INFO: Loaded GTK+ CSS theme '/usr/local/share/geany/geany.css'
12:21:28: Geany INFO: Loaded GTK+ CSS theme '/usr/local/share/geany/geany-3.20.css'
12:21:28: Geany INFO: System plugin path: /usr/local/lib/geany
12:21:28: Geany INFO: Added filetype Graphviz (61).
12:21:28: Geany INFO: Added filetype Groovy (62).
12:21:28: Geany INFO: Added filetype Swift (63).
12:21:28: Geany INFO: Added filetype Kotlin (64).
12:21:28: Geany INFO: Added filetype Nim (65).
12:21:28: Geany INFO: Added filetype CUDA (66).
12:21:28: Geany INFO: Added filetype Arduino (67).
12:21:28: Geany INFO: Added filetype Cython (68).
12:21:28: Geany INFO: Added filetype TypeScript (69).
12:21:28: Geany INFO: Added filetype Scala (70).
12:21:28: Geany INFO: Added filetype JSON (71).
12:21:28: Geany INFO: Added filetype Genie (72).
12:21:28: Geany INFO: Added filetype Clojure (73).
12:21:28: Geany INFO: Loaded libvte from libvte-2.91.so.0
12:21:28: Geany INFO: /home/pi/projects/helloworld.cpp : C++ (UTF-8)
12:21:28: Geany INFO: Loaded /usr/local/share/geany/tags/std99.c.tags (C), 1618 symbol(s).

+ next step: Installation of the (Debugger) plugins...

**Comment by Ehlarm** [comment]
hmmm... Please, I need a little help:

### Geany "Compilation" (after installation of):
+ autoconf
+ intltool
+ libtool
...
sudo ./autogen.sh
Warning: I am going to run configure with no arguments.
...
Install Geany in                       : /usr/local
Using GTK version                  : 3.24.5
Enable binary relocation          : no
Build with plugin support          : yes
Use (UNIX domain) socket support   : yes
**Use virtual terminal support (VTE)  : yes**
Build HTML documentation                : yes
Build PDF documentation                   : no
Build API documentation                    : no
Generate GtkDoc header                   : no
...
**Configuration is done OK**
Now type 'make' to compile.
...
sudo make
...
sudo make install
...
Geany 1.36 is up (look above to my last message) and running (F8 & F9 & F5) "Hello World"  :+1: 
-----------------------------------------------
### Next the plugins

geany-plugins-1.36

  Build Environment:
    Geany version:                1.36 (GTK3)
    Install prefix:               /usr/local
    Datadir:                      /usr/local/share/geany-plugins
    Libdir:                       /usr/local/lib/geany-plugins
    Docdir:                       /usr/local/share/doc/geany-plugins
    Plugins path:                 /usr/local/lib/geany

  Build Features:
    Unit tests:                   no
    Static code checking:         yes
    Extra C compiler warnings:    yes
    Extra linker options:         yes

  Plugins:
    Addons:                       yes
    Autoclose:                    yes
    Automark:                     yes
    CodeNav:                      yes
    Commander:                    yes
    **Debugger:                     no**
    Defineformat:                 yes
    DevHelp:                      no
    GeanyCtags:                   yes
    GeanyDoc:                     yes
    GeanyExtraSel:                yes
    GeanyGenDoc:                  no
    GeanyInsertNum:               yes
    LaTeX:                        yes
    GeanyLua:                     no
    GeanyMacro:                   yes
    GeanyMiniScript:              yes
    GeanyNumberedBookmarks:       yes
    GeanyPrj:                     yes
    Geanypy:                      no
    GeanyVC:                      yes
    GeanyPG:                      no
    GeniusPaste:                  no
    GitChangeBar:                 no
    keyrecord:                    yes
    LineOperations:               yes
    Lipsum:                       yes
    Markdown:                     no
    MultiTerm:                    no
    Overview:                     yes
    PairTagHighlighter:           yes
    PoHelper:                     yes
    Pretty Printer:               no
    ProjectOrganizer:             yes
    Scope:                        no
    Sendmail:                     yes
    ShiftColumn:                  yes
    Spellcheck:                   no
    TreeBrowser:                  yes
    Tableconvert:                 yes
    Updatechecker:                no
    Vimode:                       yes
    WebHelper:                    no
    Workbench:                    no
    XMLSnippets:                  yes

next try with: 

sudo ./configure --enable-all-plugins
...
checking for AUTOCLOSE... yes
checking for AUTOMARK... yes
checking for COMMANDER... yes
checking for UTILSLIB... no
**_configure: error: Plugin Debugger depends on utilslib VTE support which is not available_**
...
_??? What's going wrong ???_

**Comment by codebrainz** [comment]
Not an answer to your question, but I would not use `sudo` when compiling software. You might need it for the `make install` command depending what prefix you choose, but for all the steps before that, it's a pretty bad idea.

**Comment by LarsGit223** [comment]
@Ehlarm:
Was your output from Geany-Plugins truncated on copying it into this issue? There should be something like this on the end:
```
  Features:
    GeanyVC GtkSpell support:     no
    Markdown library:             peg-markdown
    Utility library:              yes
    Utility library VTE support:  yes
```

**Comment by LarsGit223** [comment]
@Ehlarm:
Did you try to re-install lib-vte with ```sudo apt-get install libvte-2.91-dev```? Did VTE installation work well - no error messages or so?

I re-checked compiling Geany and Geany-Plugins 1.36 on my Ubuntu machine. Works fine. All plugins depending on VTE are build, e.g. debugger and scope.

**Comment by elextr** [comment]
@Ehlarm just to emphasise what @LarsGit223 said, you need the `-dev` package of libvte to build debugger, but you don't need it to build geany (its majik), so the message on the geany build does not mean that its present.

**Comment by Ehlarm** [comment]
@codebrainz thx for the hint, you are right, I have installed too much packages ;)

**Comment by Ehlarm** [comment]
@LarsGit223 Yesterday, I did not see these messages (Utility library VTE support:  yes), unfortunately also not saved the output :(

**Comment by Ehlarm** [comment]
@LarsGit223 & @elextr now I have installed the libvte-2.91-dev without errors :)

[01 install libvte-2.91-dev OK.log](https://github.com/geany/geany-plugins/files/4254311/01.install.libvte-2.91-dev.OK.log)

then "auto removed" the old libs (OK)

[02 autoremove OK.log](https://github.com/geany/geany-plugins/files/4254332/02.autoremove.OK.log)

next try with "./configure (OK) :+1: 
[03 configure plugins OK with debigger and VTE.log](https://github.com/geany/geany-plugins/files/4254521/03.configure.plugins.OK.with.debigger.and.VTE.log)
...
geany-plugins-1.36

  Build Environment:
    Geany version:                1.36 (GTK3)
    Install prefix:               /usr/local
    Datadir:                      /usr/local/share/geany-plugins
    Libdir:                       /usr/local/lib/geany-plugins
    Docdir:                       /usr/local/share/doc/geany-plugins
    Plugins path:                 /usr/local/lib/geany

  Build Features:
    Unit tests:                   no
    Static code checking:         yes
    Extra C compiler warnings:    yes
    Extra linker options:         yes

  Plugins:
    Addons:                       yes
    Autoclose:                    yes
    Automark:                     yes
    CodeNav:                      yes
    Commander:                    yes
    **Debugger:                     yes**
    Defineformat:                 yes
    _DevHelp:                      no_
    GeanyCtags:                   yes
    GeanyDoc:                     yes
    GeanyExtraSel:                yes
    _GeanyGenDoc:                  no_
    GeanyInsertNum:               yes
    LaTeX:                        yes
    _GeanyLua:                     no_
    GeanyMacro:                   yes
    GeanyMiniScript:              yes
    GeanyNumberedBookmarks:       yes
    GeanyPrj:                     yes
    _Geanypy:                      no_
    GeanyVC:                      yes
    _GeanyPG:                      no_
    _GeniusPaste:                  no_
    _GitChangeBar:                 no_
    keyrecord:                    yes
    LineOperations:               yes
    Lipsum:                       yes
    _Markdown:                     no_
    _MultiTerm:                    no_
    Overview:                     yes
    PairTagHighlighter:           yes
    PoHelper:                     yes
    _Pretty Printer:               no_
    ProjectOrganizer:             yes
    **Scope:                        yes**
    Sendmail:                     yes
    ShiftColumn:                  yes
    _Spellcheck:                   no_
    TreeBrowser:                  yes
    Tableconvert:                 yes
    _Updatechecker:                no_
    Vimode:                       yes
    _WebHelper:                    no_
    _Workbench:                    no_
    XMLSnippets:                  yes

  Features:
    GeanyVC GtkSpell support:     no
    Markdown library:             peg-markdown
    Utility library:              yes
    **Utility library VTE support:  yes** :+1: 

pi@raspberrypi:~/geany-plugins-1.36 $

Curiously now i have a lot of the "yes" Plugins, but not all e.g. Debugger & Scope NOT :(

![Geany plugin list without Debugger](https://user-images.githubusercontent.com/53791784/75334596-6fa37000-5888-11ea-9b70-2ea40f0e16bc.png)

some file are not loaded :octopus: 

[07 Geany Debug Messages.log](https://github.com/geany/geany-plugins/files/4254891/07.Geany.Debug.Messages.log)
> **Failed to load "/usr/local/lib/geany/debugger.so" - ignoring plugin!**
> Failed to load "/usr/local/lib/geany/geanynumberedbookmarks.so" - ignoring plugin!
> Failed to load "/usr/local/lib/geany/scope.so" - ignoring plugin!
> Failed to load "/usr/local/lib/geany/treebrowser.so" - ignoring plugin!

The missing files exists and the permissions are "right" or not?
![missing plugin files exists](https://user-images.githubusercontent.com/53791784/75336033-b98d5580-588a-11ea-96cf-4d925af46114.png)

Hopefully you can help me again, please!  :)

---------------

Because there are lot of "NO" plugins, I try it with all plugins :(
[04 configure ALL plugins FALSE.log](https://github.com/geany/geany-plugins/files/4254527/04.configure.ALL.plugins.FALSE.log)
...
**checking whether the GTK version in use is compatible with plugin devhelp... no**
**configure: error: devhelp is not compatible with the GTK version in use**
pi@raspberrypi:~/geany-plugins-1.36 $

My GTK 3.24 Version is the "newest" for GNU/Linux.
My GLib 2.58 version is not the newest (2.60), but I guess this is not the problem?
I should maybe open a new issue here for the "devhelp" problem or I don't need this really?
Any suggestions for the "no" plugins?

**Comment by elextr** [comment]
Its missing libgeanypluginutils.so @LarsGit223 ??

**Comment by Ehlarm** [comment]
### I'm very happy (for the first) it's seems to work now!
![Geany with Debugger](https://user-images.githubusercontent.com/53791784/75346959-0b8ca600-58a0-11ea-999a-d62db8125743.png)

I don't exactly know what happened :dancer:  The other 3 missing plugins are also loaded (scope/treeview/geanynumberedbookmarks).

I have only 3 updates packages installed and then I shutdown the Raspberry for a while. After this pause, it run's :) :+1: 

![today update packages](https://user-images.githubusercontent.com/53791784/75346986-17786800-58a0-11ea-9b9e-283008b9f8b9.png)

**Guys I thank you very much for your support, I could never have done it alone !!!**

I've learned a lot and look forward to learning more with Geany and the Raspberry :)

Now only the "no" plugins like the "devhelp" are open (see above), but maybe not so important for me in the moment, if you have a good tip, I would be glad :)
