### ISSUE TITLE
Bookmark sidebar does not always match actual bookmarks

### ISSUE THREAD

**Issue by dbkaynor** [geany/geany-plugins#964]
When clearing the bookmarks using the Documents/Remove Markers option the actual bookmarks are cleared but the sidebar list is not. Also sometimes the same bookmark gets listed multiple times in the sidebar list.

**Comment by eht16** [comment]
Remove Markers just removes any markers, this can be also markers for search highlights and maybe more.
It is not intended that this option also clears the bookmark list.

Could you provide more details for the second problem? When exactly does it happen, steps to reproduce?

**Comment by dbkaynor** [comment]
The issue with bookmarks gets listed multiple times in the sidebar list only happens when the numbed bookmark plugin is installed. I will provide more info when I am able to get it.
