### ISSUE TITLE
Installing the Markdown plugin on Ubuntu

### ISSUE THREAD

**Issue by dandv** [geany/geany-plugins#982]
The [plugins install page](https://plugins.geany.org/install.html) says to search for plugins with `apt-cache search geany`. When I run that command on Ubuntu 20, it doesn't show any markdown plugins. How can I install the plugin?

**Comment by elextr** [comment]
You probably can't, the markdown plugin took a while to become GTK3 capable, so from when Debian/Ubuntu switched to GTK3 and the release with markdown GTK3 compatible its not available.

When Debian/Ubuntu catches up with a recent version of Geany-plugins it should appear again (assuming the package maintainer for those distros remembers to re-enable it if its manual).

**Comment by liborty** [comment]
It is never there

**Comment by elextr** [comment]
I am informed that Ubuntu 20.04 has Geany 1.36 which should have the GTK-3 markdown plugin, so the issue needs to be raised with Ubuntu as this project does not make the packages.
