### ISSUE TITLE
Cannot use Geany commands with Vimode normal mode on macos

### ISSUE THREAD

**Issue by sporklpony** [geany/geany-plugins#991]
Geany keybindings, like <primary>o to open a file do not seem to work in Vimode's normal mode on macos. As far as I know, <super>o should not overlap with any of Vimode's keybindings, but it seems to interpret it as just "o" as it creates a new line and enters insert mode.

The Geany keybindings do work fine while in insert mode on macos. I have not yet tested visual mode, line visual mode, or replace mode.

Thank you!

**Comment by techee** [comment]
I assume you mean `Command+O` and not `o` alone (`o` is a valid vim command). Indeed, the Command key isn't handled right now - I tried to fix this issue in #1099.
