### ISSUE TITLE
Clusters don't get deleted

### ISSUE THREAD

**Issue by pveentjer** [geany/geany-plugins#997]
So there are some very old clusters I want to delete. I go to the cluster details and hit delete, but the entries are not removed.

![image](https://user-images.githubusercontent.com/105243/90020068-fd98d900-dcb7-11ea-8835-badeddde094c.png)

**Comment by pveentjer** [comment]
Sorry. I was on the wrong screen.

**Comment by codebrainz** [comment]
Haha, I was so confused. @pveentjer coffee first, then Github 😉 

Related: #998
